window.SSRM_3D_PLACE_NAVIGATION_OBJECT_BRIDGE_TRACE = [
  {
    "trip": 1,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "object_id": "spring_pool",
    "object_name": "spring pool",
    "start": "cairn_ridge",
    "goal": "spring_hollow",
    "path": [
      "cairn_ridge",
      "smoke_watch",
      "drum_court",
      "roof_ring",
      "storage_yard",
      "spring_hollow"
    ],
    "route_cost": 28.125713,
    "hazard": 0.184,
    "sensory_alignment": 0.34053,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 2,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "object_id": "fire_hearth",
    "object_name": "fire hearth",
    "start": "tool_bend",
    "goal": "central_hearth",
    "path": [
      "tool_bend",
      "central_hearth"
    ],
    "route_cost": 3.421806,
    "hazard": 0.1,
    "sensory_alignment": 0.342042,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 3,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "object_id": "herb_garden",
    "object_name": "bitter herb garden",
    "start": "nursery_nest",
    "goal": "herb_slope",
    "path": [
      "nursery_nest",
      "central_hearth",
      "drum_court",
      "herb_slope"
    ],
    "route_cost": 8.805234,
    "hazard": 0.113333,
    "sensory_alignment": 0.470424,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 4,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "object_id": "grain_store",
    "object_name": "grain store",
    "start": "grain_shade",
    "goal": "grain_shade",
    "path": [
      "grain_shade"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.792432,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 5,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "object_id": "fire_hearth",
    "object_name": "fire hearth",
    "start": "smoke_watch",
    "goal": "central_hearth",
    "path": [
      "smoke_watch",
      "drum_court",
      "central_hearth"
    ],
    "route_cost": 9.683543,
    "hazard": 0.14,
    "sensory_alignment": 0.883273,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 6,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "object_id": "archive_stone",
    "object_name": "marked archive stone",
    "start": "loom_room",
    "goal": "archive_knoll",
    "path": [
      "loom_room",
      "nursery_nest",
      "central_hearth",
      "tool_bend",
      "archive_knoll"
    ],
    "route_cost": 11.646773,
    "hazard": 0.1,
    "sensory_alignment": 0.919998,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 7,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "object_id": "grain_store",
    "object_name": "grain store",
    "start": "storage_yard",
    "goal": "grain_shade",
    "path": [
      "storage_yard",
      "grain_shade"
    ],
    "route_cost": 5.286193,
    "hazard": 0.1,
    "sensory_alignment": 0.648165,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 8,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "object_id": "archive_stone",
    "object_name": "marked archive stone",
    "start": "archive_knoll",
    "goal": "archive_knoll",
    "path": [
      "archive_knoll"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.704411,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 9,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "object_id": "spring_pool",
    "object_name": "spring pool",
    "start": "spring_hollow",
    "goal": "spring_hollow",
    "path": [
      "spring_hollow"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.757688,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 10,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "object_id": "fire_hearth",
    "object_name": "fire hearth",
    "start": "central_hearth",
    "goal": "central_hearth",
    "path": [
      "central_hearth"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.802057,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 11,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "object_id": "herb_garden",
    "object_name": "bitter herb garden",
    "start": "herb_slope",
    "goal": "herb_slope",
    "path": [
      "herb_slope"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.919363,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 12,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "object_id": "spring_pool",
    "object_name": "spring pool",
    "start": "grain_shade",
    "goal": "spring_hollow",
    "path": [
      "grain_shade",
      "storage_yard",
      "spring_hollow"
    ],
    "route_cost": 11.142911,
    "hazard": 0.19,
    "sensory_alignment": 0.412908,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 13,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "object_id": "fire_hearth",
    "object_name": "fire hearth",
    "start": "central_hearth",
    "goal": "central_hearth",
    "path": [
      "central_hearth"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.38211,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 14,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "object_id": "nursery_mat",
    "object_name": "reed nursery mat",
    "start": "archive_knoll",
    "goal": "nursery_nest",
    "path": [
      "archive_knoll",
      "tool_bend",
      "central_hearth",
      "nursery_nest"
    ],
    "route_cost": 8.767402,
    "hazard": 0.106667,
    "sensory_alignment": 0.547006,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 15,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "object_id": "grain_store",
    "object_name": "grain store",
    "start": "grain_shade",
    "goal": "grain_shade",
    "path": [
      "grain_shade"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.369342,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 16,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "object_id": "archive_stone",
    "object_name": "marked archive stone",
    "start": "archive_knoll",
    "goal": "archive_knoll",
    "path": [
      "archive_knoll"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.349518,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 17,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "object_id": "spring_pool",
    "object_name": "spring pool",
    "start": "spring_hollow",
    "goal": "spring_hollow",
    "path": [
      "spring_hollow"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.793377,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 18,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "object_id": "clay_cistern",
    "object_name": "clay cistern",
    "start": "central_hearth",
    "goal": "storage_yard",
    "path": [
      "central_hearth",
      "roof_ring",
      "storage_yard"
    ],
    "route_cost": 5.870257,
    "hazard": 0.065,
    "sensory_alignment": 0.471379,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 19,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "object_id": "herb_garden",
    "object_name": "bitter herb garden",
    "start": "herb_slope",
    "goal": "herb_slope",
    "path": [
      "herb_slope"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.503827,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 20,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "object_id": "grain_store",
    "object_name": "grain store",
    "start": "spring_hollow",
    "goal": "grain_shade",
    "path": [
      "spring_hollow",
      "storage_yard",
      "grain_shade"
    ],
    "route_cost": 11.32349,
    "hazard": 0.19,
    "sensory_alignment": 0.340463,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 21,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "object_id": "fire_hearth",
    "object_name": "fire hearth",
    "start": "central_hearth",
    "goal": "central_hearth",
    "path": [
      "central_hearth"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.37472,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 22,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "object_id": "nursery_mat",
    "object_name": "reed nursery mat",
    "start": "nursery_nest",
    "goal": "nursery_nest",
    "path": [
      "nursery_nest"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.912615,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 23,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "object_id": "grain_store",
    "object_name": "grain store",
    "start": "grain_shade",
    "goal": "grain_shade",
    "path": [
      "grain_shade"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.869237,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 24,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "object_id": "route_cairn",
    "object_name": "route cairn",
    "start": "archive_knoll",
    "goal": "cairn_ridge",
    "path": [
      "archive_knoll",
      "cairn_ridge"
    ],
    "route_cost": 9.614387,
    "hazard": 0.31,
    "sensory_alignment": 0.340142,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 25,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "object_id": "spring_pool",
    "object_name": "spring pool",
    "start": "spring_hollow",
    "goal": "spring_hollow",
    "path": [
      "spring_hollow"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.340976,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 26,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "object_id": "fire_hearth",
    "object_name": "fire hearth",
    "start": "storage_yard",
    "goal": "central_hearth",
    "path": [
      "storage_yard",
      "roof_ring",
      "central_hearth"
    ],
    "route_cost": 6.158766,
    "hazard": 0.065,
    "sensory_alignment": 0.341368,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 27,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "object_id": "herb_garden",
    "object_name": "bitter herb garden",
    "start": "herb_slope",
    "goal": "herb_slope",
    "path": [
      "herb_slope"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.465233,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 28,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "object_id": "grain_store",
    "object_name": "grain store",
    "start": "grain_shade",
    "goal": "grain_shade",
    "path": [
      "grain_shade"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.49756,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 29,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "object_id": "fire_hearth",
    "object_name": "fire hearth",
    "start": "central_hearth",
    "goal": "central_hearth",
    "path": [
      "central_hearth"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.875698,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 30,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "object_id": "archive_stone",
    "object_name": "marked archive stone",
    "start": "nursery_nest",
    "goal": "archive_knoll",
    "path": [
      "nursery_nest",
      "central_hearth",
      "tool_bend",
      "archive_knoll"
    ],
    "route_cost": 8.844709,
    "hazard": 0.106667,
    "sensory_alignment": 0.770586,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 31,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "object_id": "grain_store",
    "object_name": "grain store",
    "start": "grain_shade",
    "goal": "grain_shade",
    "path": [
      "grain_shade"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.654409,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 32,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "object_id": "archive_stone",
    "object_name": "marked archive stone",
    "start": "cairn_ridge",
    "goal": "archive_knoll",
    "path": [
      "cairn_ridge",
      "archive_knoll"
    ],
    "route_cost": 9.66576,
    "hazard": 0.31,
    "sensory_alignment": 0.710446,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 33,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "object_id": "spring_pool",
    "object_name": "spring pool",
    "start": "spring_hollow",
    "goal": "spring_hollow",
    "path": [
      "spring_hollow"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.752037,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 34,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "object_id": "fire_hearth",
    "object_name": "fire hearth",
    "start": "central_hearth",
    "goal": "central_hearth",
    "path": [
      "central_hearth"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.796977,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 35,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "object_id": "herb_garden",
    "object_name": "bitter herb garden",
    "start": "herb_slope",
    "goal": "herb_slope",
    "path": [
      "herb_slope"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.752401,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 36,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "object_id": "spring_pool",
    "object_name": "spring pool",
    "start": "grain_shade",
    "goal": "spring_hollow",
    "path": [
      "grain_shade",
      "storage_yard",
      "spring_hollow"
    ],
    "route_cost": 11.024886,
    "hazard": 0.19,
    "sensory_alignment": 0.694094,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 37,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "object_id": "fire_hearth",
    "object_name": "fire hearth",
    "start": "central_hearth",
    "goal": "central_hearth",
    "path": [
      "central_hearth"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.642651,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 38,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "object_id": "nursery_mat",
    "object_name": "reed nursery mat",
    "start": "archive_knoll",
    "goal": "nursery_nest",
    "path": [
      "archive_knoll",
      "tool_bend",
      "central_hearth",
      "nursery_nest"
    ],
    "route_cost": 8.761494,
    "hazard": 0.106667,
    "sensory_alignment": 0.541026,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 39,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "object_id": "grain_store",
    "object_name": "grain store",
    "start": "grain_shade",
    "goal": "grain_shade",
    "path": [
      "grain_shade"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.366658,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 40,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "object_id": "archive_stone",
    "object_name": "marked archive stone",
    "start": "archive_knoll",
    "goal": "archive_knoll",
    "path": [
      "archive_knoll"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.347992,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 41,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "object_id": "spring_pool",
    "object_name": "spring pool",
    "start": "spring_hollow",
    "goal": "spring_hollow",
    "path": [
      "spring_hollow"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.798512,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 42,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "object_id": "clay_cistern",
    "object_name": "clay cistern",
    "start": "central_hearth",
    "goal": "storage_yard",
    "path": [
      "central_hearth",
      "roof_ring",
      "storage_yard"
    ],
    "route_cost": 5.582283,
    "hazard": 0.065,
    "sensory_alignment": 0.766494,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 43,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "object_id": "herb_garden",
    "object_name": "bitter herb garden",
    "start": "herb_slope",
    "goal": "herb_slope",
    "path": [
      "herb_slope"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.798185,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 44,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "object_id": "grain_store",
    "object_name": "grain store",
    "start": "spring_hollow",
    "goal": "grain_shade",
    "path": [
      "spring_hollow",
      "storage_yard",
      "grain_shade"
    ],
    "route_cost": 11.33338,
    "hazard": 0.19,
    "sensory_alignment": 0.476317,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 45,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "object_id": "fire_hearth",
    "object_name": "fire hearth",
    "start": "central_hearth",
    "goal": "central_hearth",
    "path": [
      "central_hearth"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.371809,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 46,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "object_id": "nursery_mat",
    "object_name": "reed nursery mat",
    "start": "nursery_nest",
    "goal": "nursery_nest",
    "path": [
      "nursery_nest"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.913953,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 47,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "object_id": "grain_store",
    "object_name": "grain store",
    "start": "grain_shade",
    "goal": "grain_shade",
    "path": [
      "grain_shade"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.865643,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 48,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "object_id": "route_cairn",
    "object_name": "route cairn",
    "start": "archive_knoll",
    "goal": "cairn_ridge",
    "path": [
      "archive_knoll",
      "cairn_ridge"
    ],
    "route_cost": 8.802958,
    "hazard": 0.31,
    "sensory_alignment": 0.340014,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 49,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "object_id": "spring_pool",
    "object_name": "spring pool",
    "start": "spring_hollow",
    "goal": "spring_hollow",
    "path": [
      "spring_hollow"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.511763,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 50,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "object_id": "fire_hearth",
    "object_name": "fire hearth",
    "start": "storage_yard",
    "goal": "central_hearth",
    "path": [
      "storage_yard",
      "roof_ring",
      "central_hearth"
    ],
    "route_cost": 5.917693,
    "hazard": 0.065,
    "sensory_alignment": 0.466454,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 51,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "object_id": "herb_garden",
    "object_name": "bitter herb garden",
    "start": "herb_slope",
    "goal": "herb_slope",
    "path": [
      "herb_slope"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.341515,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 52,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "object_id": "grain_store",
    "object_name": "grain store",
    "start": "grain_shade",
    "goal": "grain_shade",
    "path": [
      "grain_shade"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.492021,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 53,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "object_id": "fire_hearth",
    "object_name": "fire hearth",
    "start": "central_hearth",
    "goal": "central_hearth",
    "path": [
      "central_hearth"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.872315,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 54,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "object_id": "loom_frame",
    "object_name": "reed loom frame",
    "start": "nursery_nest",
    "goal": "loom_room",
    "path": [
      "nursery_nest",
      "loom_room"
    ],
    "route_cost": 2.807944,
    "hazard": 0.08,
    "sensory_alignment": 0.438568,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 55,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "object_id": "grain_store",
    "object_name": "grain store",
    "start": "grain_shade",
    "goal": "grain_shade",
    "path": [
      "grain_shade"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.660643,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 56,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "object_id": "archive_stone",
    "object_name": "marked archive stone",
    "start": "cairn_ridge",
    "goal": "archive_knoll",
    "path": [
      "cairn_ridge",
      "archive_knoll"
    ],
    "route_cost": 10.048351,
    "hazard": 0.31,
    "sensory_alignment": 0.912952,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 57,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "object_id": "spring_pool",
    "object_name": "spring pool",
    "start": "spring_hollow",
    "goal": "spring_hollow",
    "path": [
      "spring_hollow"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.458108,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 58,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "object_id": "shelter_roof",
    "object_name": "woven shelter roof",
    "start": "central_hearth",
    "goal": "roof_ring",
    "path": [
      "central_hearth",
      "roof_ring"
    ],
    "route_cost": 1.004226,
    "hazard": 0.05,
    "sensory_alignment": 0.502496,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 59,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "object_id": "herb_garden",
    "object_name": "bitter herb garden",
    "start": "herb_slope",
    "goal": "herb_slope",
    "path": [
      "herb_slope"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.746696,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 60,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "object_id": "spring_pool",
    "object_name": "spring pool",
    "start": "grain_shade",
    "goal": "spring_hollow",
    "path": [
      "grain_shade",
      "storage_yard",
      "spring_hollow"
    ],
    "route_cost": 11.031482,
    "hazard": 0.19,
    "sensory_alignment": 0.700185,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 61,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "object_id": "fire_hearth",
    "object_name": "fire hearth",
    "start": "central_hearth",
    "goal": "central_hearth",
    "path": [
      "central_hearth"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.648903,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 62,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "object_id": "nursery_mat",
    "object_name": "reed nursery mat",
    "start": "loom_room",
    "goal": "nursery_nest",
    "path": [
      "loom_room",
      "nursery_nest"
    ],
    "route_cost": 2.689223,
    "hazard": 0.08,
    "sensory_alignment": 0.535087,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 63,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "object_id": "grain_store",
    "object_name": "grain store",
    "start": "grain_shade",
    "goal": "grain_shade",
    "path": [
      "grain_shade"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.396815,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 64,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "object_id": "archive_stone",
    "object_name": "marked archive stone",
    "start": "archive_knoll",
    "goal": "archive_knoll",
    "path": [
      "archive_knoll"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.435031,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 65,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "object_id": "spring_pool",
    "object_name": "spring pool",
    "start": "spring_hollow",
    "goal": "spring_hollow",
    "path": [
      "spring_hollow"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.917982,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 66,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "object_id": "shelter_roof",
    "object_name": "woven shelter roof",
    "start": "roof_ring",
    "goal": "roof_ring",
    "path": [
      "roof_ring"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.919458,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 67,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "object_id": "herb_garden",
    "object_name": "bitter herb garden",
    "start": "herb_slope",
    "goal": "herb_slope",
    "path": [
      "herb_slope"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.803247,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 68,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "object_id": "grain_store",
    "object_name": "grain store",
    "start": "spring_hollow",
    "goal": "grain_shade",
    "path": [
      "spring_hollow",
      "storage_yard",
      "grain_shade"
    ],
    "route_cost": 11.158204,
    "hazard": 0.19,
    "sensory_alignment": 0.481663,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 69,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "object_id": "fire_hearth",
    "object_name": "fire hearth",
    "start": "central_hearth",
    "goal": "central_hearth",
    "path": [
      "central_hearth"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.369018,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 70,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "object_id": "nursery_mat",
    "object_name": "reed nursery mat",
    "start": "nursery_nest",
    "goal": "nursery_nest",
    "path": [
      "nursery_nest"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.818276,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 71,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "object_id": "grain_store",
    "object_name": "grain store",
    "start": "grain_shade",
    "goal": "grain_shade",
    "path": [
      "grain_shade"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.595209,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 72,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "object_id": "route_cairn",
    "object_name": "route cairn",
    "start": "archive_knoll",
    "goal": "cairn_ridge",
    "path": [
      "archive_knoll",
      "cairn_ridge"
    ],
    "route_cost": 8.788959,
    "hazard": 0.31,
    "sensory_alignment": 0.487985,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 73,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "object_id": "spring_pool",
    "object_name": "spring pool",
    "start": "spring_hollow",
    "goal": "spring_hollow",
    "path": [
      "spring_hollow"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.517508,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 74,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "object_id": "clay_cistern",
    "object_name": "clay cistern",
    "start": "roof_ring",
    "goal": "storage_yard",
    "path": [
      "roof_ring",
      "storage_yard"
    ],
    "route_cost": 4.899928,
    "hazard": 0.08,
    "sensory_alignment": 0.340003,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 75,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "object_id": "herb_garden",
    "object_name": "bitter herb garden",
    "start": "herb_slope",
    "goal": "herb_slope",
    "path": [
      "herb_slope"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.342222,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 76,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "object_id": "grain_store",
    "object_name": "grain store",
    "start": "grain_shade",
    "goal": "grain_shade",
    "path": [
      "grain_shade"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.486546,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 77,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "object_id": "fire_hearth",
    "object_name": "fire hearth",
    "start": "central_hearth",
    "goal": "central_hearth",
    "path": [
      "central_hearth"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.606933,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 78,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "object_id": "loom_frame",
    "object_name": "reed loom frame",
    "start": "nursery_nest",
    "goal": "loom_room",
    "path": [
      "nursery_nest",
      "loom_room"
    ],
    "route_cost": 2.774402,
    "hazard": 0.08,
    "sensory_alignment": 0.728848,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 79,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "object_id": "grain_store",
    "object_name": "grain store",
    "start": "grain_shade",
    "goal": "grain_shade",
    "path": [
      "grain_shade"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.897541,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 80,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "object_id": "archive_stone",
    "object_name": "marked archive stone",
    "start": "cairn_ridge",
    "goal": "archive_knoll",
    "path": [
      "cairn_ridge",
      "archive_knoll"
    ],
    "route_cost": 10.04705,
    "hazard": 0.31,
    "sensory_alignment": 0.914258,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 81,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "object_id": "spring_pool",
    "object_name": "spring pool",
    "start": "spring_hollow",
    "goal": "spring_hollow",
    "path": [
      "spring_hollow"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.453105,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 82,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "object_id": "clay_cistern",
    "object_name": "clay cistern",
    "start": "storage_yard",
    "goal": "storage_yard",
    "path": [
      "storage_yard"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.774387,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 83,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "object_id": "herb_garden",
    "object_name": "bitter herb garden",
    "start": "herb_slope",
    "goal": "herb_slope",
    "path": [
      "herb_slope"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.740937,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 84,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "object_id": "spring_pool",
    "object_name": "spring pool",
    "start": "grain_shade",
    "goal": "spring_hollow",
    "path": [
      "grain_shade",
      "storage_yard",
      "spring_hollow"
    ],
    "route_cost": 11.252167,
    "hazard": 0.19,
    "sensory_alignment": 0.910434,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 85,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "object_id": "fire_hearth",
    "object_name": "fire hearth",
    "start": "central_hearth",
    "goal": "central_hearth",
    "path": [
      "central_hearth"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.892775,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 86,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "object_id": "nursery_mat",
    "object_name": "reed nursery mat",
    "start": "loom_room",
    "goal": "nursery_nest",
    "path": [
      "loom_room",
      "nursery_nest"
    ],
    "route_cost": 2.692563,
    "hazard": 0.08,
    "sensory_alignment": 0.344111,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 87,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "object_id": "grain_store",
    "object_name": "grain store",
    "start": "grain_shade",
    "goal": "grain_shade",
    "path": [
      "grain_shade"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.400592,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 88,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "object_id": "archive_stone",
    "object_name": "marked archive stone",
    "start": "archive_knoll",
    "goal": "archive_knoll",
    "path": [
      "archive_knoll"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.439711,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 89,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "object_id": "spring_pool",
    "object_name": "spring pool",
    "start": "spring_hollow",
    "goal": "spring_hollow",
    "path": [
      "spring_hollow"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.917177,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 90,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "object_id": "clay_cistern",
    "object_name": "clay cistern",
    "start": "storage_yard",
    "goal": "storage_yard",
    "path": [
      "storage_yard"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.777413,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 91,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "object_id": "herb_garden",
    "object_name": "bitter herb garden",
    "start": "herb_slope",
    "goal": "herb_slope",
    "path": [
      "herb_slope"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.917233,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 92,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "object_id": "grain_store",
    "object_name": "grain store",
    "start": "spring_hollow",
    "goal": "grain_shade",
    "path": [
      "spring_hollow",
      "storage_yard",
      "grain_shade"
    ],
    "route_cost": 11.535426,
    "hazard": 0.19,
    "sensory_alignment": 0.777067,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 93,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "object_id": "fire_hearth",
    "object_name": "fire hearth",
    "start": "central_hearth",
    "goal": "central_hearth",
    "path": [
      "central_hearth"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.393575,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 94,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "object_id": "nursery_mat",
    "object_name": "reed nursery mat",
    "start": "nursery_nest",
    "goal": "nursery_nest",
    "path": [
      "nursery_nest"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.81347,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 95,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "object_id": "grain_store",
    "object_name": "grain store",
    "start": "grain_shade",
    "goal": "grain_shade",
    "path": [
      "grain_shade"
    ],
    "route_cost": 0.0,
    "hazard": 0.0,
    "sensory_alignment": 0.589001,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  },
  {
    "trip": 96,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "object_id": "route_cairn",
    "object_name": "route cairn",
    "start": "archive_knoll",
    "goal": "cairn_ridge",
    "path": [
      "archive_knoll",
      "cairn_ridge"
    ],
    "route_cost": 8.775176,
    "hazard": 0.31,
    "sensory_alignment": 0.493478,
    "arrived": true,
    "object_interacted_after_arrival": true,
    "travel_spent": true,
    "social_wayfinding": true
  }
];
