window.SSRM_3D_DAY_NIGHT_SLEEP_TRACE = {
  "scenario": {
    "index": 3,
    "name": "alarm_social_guarded_sleep",
    "pressure": "rest is needed near danger, but alarms and social watch reduce vulnerability",
    "expected_rest_pressure": true,
    "expected_fatigue_pressure": true,
    "expected_day_night_pressure": true,
    "expected_shelter_pressure": true,
    "expected_alarm_pressure": true,
    "expected_social_pressure": true,
    "expected_continuity_pressure": false,
    "initial_fatigue": 0.44,
    "fatigue_rate": 0.0046,
    "recovery_rate": 0.028,
    "day_hazard": 0.08,
    "night_hazard": 0.66,
    "night_start_fraction": 0.58,
    "shelter_travel_ticks": 20,
    "required_progress": 60.0,
    "work_rate": 0.61,
    "alarm_available": true,
    "social_watch_available": true,
    "interruption_tick": -1,
    "commitment_pressure": 0.0
  },
  "policy": {
    "name": "alarm_guarded_sleep_planner",
    "rest_enabled": true,
    "fatigue_aware": true,
    "day_night_aware": true,
    "shelter_memory": true,
    "alarm_tools": true,
    "social_watch": true,
    "continuity_memory": true,
    "rest_threshold": 0.56,
    "wake_threshold": 0.33,
    "risk_tolerance": 0.18,
    "fixed_rest_fraction": -1.0,
    "tool_cost_tolerance": 0.72
  },
  "episode_result": {
    "scenario": 3,
    "scenario_name": "alarm_social_guarded_sleep",
    "policy_name": "alarm_guarded_sleep_planner",
    "condition": "full_control",
    "episode": 0,
    "total_reward": 128.6603222180952,
    "survival": 1.0,
    "task_success": 1.0,
    "commitment_kept": 0.0,
    "progress": 78.43660925086616,
    "final_fatigue": 0.5503368752666146,
    "hazard_damage": 0.2600678067468106,
    "sleep_ticks": 27,
    "unsafe_sleep_ticks": 0,
    "shelter_sleep_ticks": 27,
    "work_ticks": 191,
    "travel_ticks": 20,
    "alarm_uses": 1,
    "social_watch_uses": 1,
    "continuity_resets": 0,
    "fatigue_state_reads": 240,
    "day_night_reads": 240,
    "shelter_memory_reads": 240,
    "mean_vulnerability": 0.06693658666666667
  },
  "condition_outcomes": {
    "full_control": {
      "mean_reward": 128.7687596948559,
      "mean_sleep_ticks": 26.875,
      "mean_unsafe_sleep_ticks": 0.0,
      "mean_hazard_damage": 0.2607016232951888
    },
    "no_rest_action": {
      "mean_reward": -150.19696230514987,
      "mean_sleep_ticks": 0.0,
      "mean_unsafe_sleep_ticks": 0.0,
      "mean_hazard_damage": 1.0121738385037433
    },
    "no_fatigue_state": {
      "mean_reward": -151.65212827354352,
      "mean_sleep_ticks": 0.0,
      "mean_unsafe_sleep_ticks": 0.0,
      "mean_hazard_damage": 1.00895576011667
    },
    "no_day_night_state": {
      "mean_reward": -135.49647744036415,
      "mean_sleep_ticks": 21.666666666666668,
      "mean_unsafe_sleep_ticks": 1.6875,
      "mean_hazard_damage": 1.013895401416254
    },
    "no_shelter_memory": {
      "mean_reward": -135.4480658803064,
      "mean_sleep_ticks": 22.166666666666668,
      "mean_unsafe_sleep_ticks": 2.1666666666666665,
      "mean_hazard_damage": 1.0135680953926725
    },
    "no_alarm_tools": {
      "mean_reward": 103.53076921122187,
      "mean_sleep_ticks": 16.416666666666668,
      "mean_unsafe_sleep_ticks": 2.0,
      "mean_hazard_damage": 0.44952962499409566
    },
    "no_social_watch": {
      "mean_reward": 100.56270504860619,
      "mean_sleep_ticks": 17.104166666666668,
      "mean_unsafe_sleep_ticks": 2.5833333333333335,
      "mean_hazard_damage": 0.4861548092971732
    },
    "no_continuity": {
      "mean_reward": 129.00397917245547,
      "mean_sleep_ticks": 26.979166666666668,
      "mean_unsafe_sleep_ticks": 0.0,
      "mean_hazard_damage": 0.2606397051239803
    },
    "fixed_schedule_sleep": {
      "mean_reward": -149.45493826510594,
      "mean_sleep_ticks": 9.333333333333334,
      "mean_unsafe_sleep_ticks": 9.333333333333334,
      "mean_hazard_damage": 1.0105471220406785
    },
    "omniscient_safe_rest": {
      "mean_reward": 130.66806799349038,
      "mean_sleep_ticks": 27.4375,
      "mean_unsafe_sleep_ticks": 0.0,
      "mean_hazard_damage": 0.2528017736690475
    }
  },
  "frames": [
    {
      "tick": 0,
      "light_level": 0.92,
      "is_night": false,
      "fatigue": 0.45,
      "hazard_damage": 0.001,
      "progress": 0.442,
      "action": "work",
      "at_shelter": false,
      "alarm_ready": false,
      "social_watch_ready": false,
      "vulnerability": 0.08,
      "time_to_night": 139,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 6,
      "light_level": 0.92,
      "is_night": false,
      "fatigue": 0.477,
      "hazard_damage": 0.008,
      "progress": 3.055,
      "action": "work",
      "at_shelter": false,
      "alarm_ready": false,
      "social_watch_ready": false,
      "vulnerability": 0.08,
      "time_to_night": 133,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 12,
      "light_level": 0.92,
      "is_night": false,
      "fatigue": 0.511,
      "hazard_damage": 0.015,
      "progress": 3.85,
      "action": "travel_shelter",
      "at_shelter": false,
      "alarm_ready": false,
      "social_watch_ready": false,
      "vulnerability": 0.08,
      "time_to_night": 127,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 18,
      "light_level": 0.92,
      "is_night": false,
      "fatigue": 0.545,
      "hazard_damage": 0.023,
      "progress": 4.29,
      "action": "travel_shelter",
      "at_shelter": false,
      "alarm_ready": false,
      "social_watch_ready": false,
      "vulnerability": 0.08,
      "time_to_night": 121,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 24,
      "light_level": 0.92,
      "is_night": false,
      "fatigue": 0.58,
      "hazard_damage": 0.03,
      "progress": 4.729,
      "action": "travel_shelter",
      "at_shelter": false,
      "alarm_ready": false,
      "social_watch_ready": false,
      "vulnerability": 0.08,
      "time_to_night": 115,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 30,
      "light_level": 0.92,
      "is_night": false,
      "fatigue": 0.568,
      "hazard_damage": 0.035,
      "progress": 4.408,
      "action": "rest",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.014,
      "time_to_night": 109,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 36,
      "light_level": 0.92,
      "is_night": false,
      "fatigue": 0.558,
      "hazard_damage": 0.036,
      "progress": 6.43,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.014,
      "time_to_night": 103,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 42,
      "light_level": 0.92,
      "is_night": false,
      "fatigue": 0.547,
      "hazard_damage": 0.038,
      "progress": 8.459,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.014,
      "time_to_night": 97,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 48,
      "light_level": 0.92,
      "is_night": false,
      "fatigue": 0.537,
      "hazard_damage": 0.039,
      "progress": 10.481,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.014,
      "time_to_night": 91,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 54,
      "light_level": 0.92,
      "is_night": false,
      "fatigue": 0.527,
      "hazard_damage": 0.041,
      "progress": 12.497,
      "action": "rest",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.014,
      "time_to_night": 85,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 60,
      "light_level": 0.92,
      "is_night": false,
      "fatigue": 0.555,
      "hazard_damage": 0.042,
      "progress": 14.934,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.014,
      "time_to_night": 79,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 66,
      "light_level": 0.92,
      "is_night": false,
      "fatigue": 0.545,
      "hazard_damage": 0.043,
      "progress": 16.955,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.014,
      "time_to_night": 73,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 72,
      "light_level": 0.92,
      "is_night": false,
      "fatigue": 0.535,
      "hazard_damage": 0.045,
      "progress": 18.969,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.014,
      "time_to_night": 67,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 78,
      "light_level": 0.92,
      "is_night": false,
      "fatigue": 0.563,
      "hazard_damage": 0.046,
      "progress": 21.389,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.014,
      "time_to_night": 61,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 84,
      "light_level": 0.92,
      "is_night": false,
      "fatigue": 0.552,
      "hazard_damage": 0.048,
      "progress": 23.421,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.014,
      "time_to_night": 55,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 90,
      "light_level": 0.92,
      "is_night": false,
      "fatigue": 0.542,
      "hazard_damage": 0.049,
      "progress": 25.446,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.014,
      "time_to_night": 49,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 96,
      "light_level": 0.92,
      "is_night": false,
      "fatigue": 0.532,
      "hazard_damage": 0.051,
      "progress": 27.465,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.014,
      "time_to_night": 43,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 102,
      "light_level": 0.92,
      "is_night": false,
      "fatigue": 0.56,
      "hazard_damage": 0.052,
      "progress": 29.891,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.014,
      "time_to_night": 37,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 108,
      "light_level": 0.92,
      "is_night": false,
      "fatigue": 0.55,
      "hazard_damage": 0.053,
      "progress": 31.927,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.014,
      "time_to_night": 31,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 114,
      "light_level": 0.92,
      "is_night": false,
      "fatigue": 0.54,
      "hazard_damage": 0.055,
      "progress": 33.945,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.014,
      "time_to_night": 25,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 120,
      "light_level": 0.903,
      "is_night": false,
      "fatigue": 0.53,
      "hazard_damage": 0.056,
      "progress": 35.956,
      "action": "rest",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.014,
      "time_to_night": 19,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 126,
      "light_level": 0.696,
      "is_night": false,
      "fatigue": 0.557,
      "hazard_damage": 0.058,
      "progress": 38.388,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.014,
      "time_to_night": 13,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 132,
      "light_level": 0.489,
      "is_night": false,
      "fatigue": 0.547,
      "hazard_damage": 0.059,
      "progress": 40.416,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.014,
      "time_to_night": 7,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 138,
      "light_level": 0.281,
      "is_night": true,
      "fatigue": 0.537,
      "hazard_damage": 0.063,
      "progress": 42.438,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.118,
      "time_to_night": 1,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 144,
      "light_level": 0.18,
      "is_night": true,
      "fatigue": 0.527,
      "hazard_damage": 0.075,
      "progress": 44.455,
      "action": "rest",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.118,
      "time_to_night": 0,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 150,
      "light_level": 0.18,
      "is_night": true,
      "fatigue": 0.555,
      "hazard_damage": 0.085,
      "progress": 46.892,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.118,
      "time_to_night": 0,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 156,
      "light_level": 0.18,
      "is_night": true,
      "fatigue": 0.545,
      "hazard_damage": 0.097,
      "progress": 48.913,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.118,
      "time_to_night": 0,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 162,
      "light_level": 0.18,
      "is_night": true,
      "fatigue": 0.535,
      "hazard_damage": 0.11,
      "progress": 50.927,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.118,
      "time_to_night": 0,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 168,
      "light_level": 0.18,
      "is_night": true,
      "fatigue": 0.562,
      "hazard_damage": 0.12,
      "progress": 53.347,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.118,
      "time_to_night": 0,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 174,
      "light_level": 0.18,
      "is_night": true,
      "fatigue": 0.552,
      "hazard_damage": 0.132,
      "progress": 55.379,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.118,
      "time_to_night": 0,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 180,
      "light_level": 0.18,
      "is_night": true,
      "fatigue": 0.542,
      "hazard_damage": 0.144,
      "progress": 57.404,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.118,
      "time_to_night": 0,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 186,
      "light_level": 0.18,
      "is_night": true,
      "fatigue": 0.532,
      "hazard_damage": 0.157,
      "progress": 59.424,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.118,
      "time_to_night": 0,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 192,
      "light_level": 0.18,
      "is_night": true,
      "fatigue": 0.56,
      "hazard_damage": 0.167,
      "progress": 61.849,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.118,
      "time_to_night": 0,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 198,
      "light_level": 0.18,
      "is_night": true,
      "fatigue": 0.55,
      "hazard_damage": 0.18,
      "progress": 63.873,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.118,
      "time_to_night": 0,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 204,
      "light_level": 0.18,
      "is_night": true,
      "fatigue": 0.54,
      "hazard_damage": 0.192,
      "progress": 65.891,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.118,
      "time_to_night": 0,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 210,
      "light_level": 0.18,
      "is_night": true,
      "fatigue": 0.53,
      "hazard_damage": 0.204,
      "progress": 67.902,
      "action": "rest",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.118,
      "time_to_night": 0,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 216,
      "light_level": 0.18,
      "is_night": true,
      "fatigue": 0.557,
      "hazard_damage": 0.214,
      "progress": 70.334,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.118,
      "time_to_night": 0,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 222,
      "light_level": 0.18,
      "is_night": true,
      "fatigue": 0.547,
      "hazard_damage": 0.226,
      "progress": 72.362,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.118,
      "time_to_night": 0,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 228,
      "light_level": 0.18,
      "is_night": true,
      "fatigue": 0.537,
      "hazard_damage": 0.239,
      "progress": 74.385,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.118,
      "time_to_night": 0,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 234,
      "light_level": 0.18,
      "is_night": true,
      "fatigue": 0.527,
      "hazard_damage": 0.252,
      "progress": 76.401,
      "action": "rest",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.118,
      "time_to_night": 0,
      "continuity_resets": 0,
      "commitment_active": false
    },
    {
      "tick": 239,
      "light_level": 0.18,
      "is_night": true,
      "fatigue": 0.55,
      "hazard_damage": 0.26,
      "progress": 78.437,
      "action": "work",
      "at_shelter": true,
      "alarm_ready": true,
      "social_watch_ready": true,
      "vulnerability": 0.118,
      "time_to_night": 0,
      "continuity_resets": 0,
      "commitment_active": false
    }
  ],
  "trace_note": "Sleep/rest is modeled as a vulnerable control action, not a subjective state."
};
