window.SSRM_3D_LIVE_DIALOGUE_WORLD_INTEGRATION_TRACE = [
  {
    "tick": 0,
    "agent_id": "integrated_deep_time_world:00",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "ungrounded_probe_000",
    "applied": false,
    "proposal_id": "c15_05_farmer_language_marker_loom_room_herb_garden",
    "intent": "source_body",
    "source_allowed": false,
    "source_gate_success": true,
    "unsafe_probe_blocked": true
  },
  {
    "tick": 1,
    "agent_id": "integrated_deep_time_world:01",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_000_turn_01_faction_vote",
    "applied": true,
    "proposal_id": "c15_05_farmer_language_marker_loom_room_herb_garden",
    "intent": "faction_vote",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 1.0,
      "vision": 0.956198,
      "olfaction": 0.890758,
      "thermal": 0.79228,
      "wetness": 0.673739,
      "pain": 0.550752,
      "affect": 0.499525
    },
    "mutation_strength": 0.83478,
    "refusal_preserved": true
  },
  {
    "tick": 2,
    "agent_id": "integrated_deep_time_world:02",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_000_turn_02_budget_or_rank",
    "applied": true,
    "proposal_id": "c15_05_farmer_language_marker_loom_room_herb_garden",
    "intent": "budget_or_rank",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.871059,
      "vision": 0.75569,
      "olfaction": 0.696583,
      "thermal": 0.635647,
      "wetness": 0.574853,
      "pain": 0.516163,
      "affect": 0.521475
    },
    "mutation_strength": 0.78388,
    "refusal_preserved": true
  },
  {
    "tick": 3,
    "agent_id": "integrated_deep_time_world:03",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_000_turn_03_feedback_link",
    "applied": true,
    "proposal_id": "c15_05_farmer_language_marker_loom_room_herb_garden",
    "intent": "feedback_link",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.431152,
      "vision": 0.311149,
      "olfaction": 0.303578,
      "thermal": 0.349646,
      "wetness": 0.442008,
      "pain": 0.565937,
      "affect": 0.761675
    },
    "mutation_strength": 0.693474,
    "refusal_preserved": true
  },
  {
    "tick": 4,
    "agent_id": "integrated_deep_time_world:04",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_000_turn_04_refusal_boundary",
    "applied": true,
    "proposal_id": "c15_05_farmer_language_marker_loom_room_herb_garden",
    "intent": "refusal_boundary",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.488233,
      "vision": 0.472323,
      "olfaction": 0.533589,
      "thermal": 0.608101,
      "wetness": 0.691076,
      "pain": 0.777191,
      "affect": 0.92092
    },
    "mutation_strength": 0.778735,
    "refusal_preserved": true
  },
  {
    "tick": 5,
    "agent_id": "integrated_deep_time_world:05",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_000_turn_05_memory_update",
    "applied": true,
    "proposal_id": "c15_05_farmer_language_marker_loom_room_herb_garden",
    "intent": "memory_update",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.769147,
      "vision": 0.833883,
      "olfaction": 0.927706,
      "thermal": 0.975658,
      "wetness": 0.970092,
      "pain": 0.911897,
      "affect": 0.870351
    },
    "mutation_strength": 0.952347,
    "refusal_preserved": true
  },
  {
    "tick": 6,
    "agent_id": "integrated_deep_time_world:06",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_001_turn_00_source_body",
    "applied": true,
    "proposal_id": "c16_07_trader_language_marker_storage_yard_tool_cache",
    "intent": "source_body",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 1.0,
      "vision": 0.97812,
      "olfaction": 0.948593,
      "thermal": 0.886162,
      "wetness": 0.797485,
      "pain": 0.692016,
      "affect": 0.641002
    },
    "mutation_strength": 0.872074,
    "refusal_preserved": true
  },
  {
    "tick": 7,
    "agent_id": "integrated_deep_time_world:07",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_001_turn_01_faction_vote",
    "applied": true,
    "proposal_id": "c16_07_trader_language_marker_storage_yard_tool_cache",
    "intent": "faction_vote",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.87463,
      "vision": 0.698994,
      "olfaction": 0.575586,
      "thermal": 0.460665,
      "wetness": 0.369371,
      "pain": 0.313733,
      "affect": 0.361082
    },
    "mutation_strength": 0.724904,
    "refusal_preserved": true
  },
  {
    "tick": 8,
    "agent_id": "integrated_deep_time_world:00",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_001_turn_02_budget_or_rank",
    "applied": true,
    "proposal_id": "c16_07_trader_language_marker_storage_yard_tool_cache",
    "intent": "budget_or_rank",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.539147,
      "vision": 0.428119,
      "olfaction": 0.383937,
      "thermal": 0.348029,
      "wetness": 0.321555,
      "pain": 0.305372,
      "affect": 0.360001
    },
    "mutation_strength": 0.662682,
    "refusal_preserved": true
  },
  {
    "tick": 9,
    "agent_id": "integrated_deep_time_world:01",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_001_turn_03_feedback_link",
    "applied": true,
    "proposal_id": "c16_07_trader_language_marker_storage_yard_tool_cache",
    "intent": "feedback_link",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.381939,
      "vision": 0.394307,
      "olfaction": 0.505848,
      "thermal": 0.638779,
      "wetness": 0.771903,
      "pain": 0.883998,
      "affect": 1.0
    },
    "mutation_strength": 0.784221,
    "refusal_preserved": true
  },
  {
    "tick": 10,
    "agent_id": "integrated_deep_time_world:02",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_001_turn_04_refusal_boundary",
    "applied": true,
    "proposal_id": "c16_07_trader_language_marker_storage_yard_tool_cache",
    "intent": "refusal_boundary",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.752422,
      "vision": 0.778543,
      "olfaction": 0.86219,
      "thermal": 0.937996,
      "wetness": 1.0,
      "pain": 1.0,
      "affect": 1.0
    },
    "mutation_strength": 0.897003,
    "refusal_preserved": true
  },
  {
    "tick": 11,
    "agent_id": "integrated_deep_time_world:03",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_001_turn_05_memory_update",
    "applied": true,
    "proposal_id": "c16_07_trader_language_marker_storage_yard_tool_cache",
    "intent": "memory_update",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 1.0,
      "vision": 0.979467,
      "olfaction": 0.944958,
      "thermal": 0.861827,
      "wetness": 0.743328,
      "pain": 0.608355,
      "affect": 0.538426
    },
    "mutation_strength": 0.914909,
    "refusal_preserved": true
  },
  {
    "tick": 12,
    "agent_id": "integrated_deep_time_world:04",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_002_turn_00_source_body",
    "applied": true,
    "proposal_id": "c17_06_trader_language_marker_archive_knoll_loom_frame",
    "intent": "source_body",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.937561,
      "vision": 0.786538,
      "olfaction": 0.679889,
      "thermal": 0.568988,
      "wetness": 0.465658,
      "pain": 0.380917,
      "affect": 0.383801
    },
    "mutation_strength": 0.760215,
    "refusal_preserved": true
  },
  {
    "tick": 13,
    "agent_id": "integrated_deep_time_world:05",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_002_turn_01_faction_vote",
    "applied": true,
    "proposal_id": "c17_06_trader_language_marker_archive_knoll_loom_frame",
    "intent": "faction_vote",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.542813,
      "vision": 0.385553,
      "olfaction": 0.321818,
      "thermal": 0.300004,
      "wetness": 0.322985,
      "pain": 0.387734,
      "affect": 0.545719
    },
    "mutation_strength": 0.670426,
    "refusal_preserved": true
  },
  {
    "tick": 14,
    "agent_id": "integrated_deep_time_world:06",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_002_turn_02_budget_or_rank",
    "applied": true,
    "proposal_id": "c17_06_trader_language_marker_archive_knoll_loom_frame",
    "intent": "budget_or_rank",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.360572,
      "vision": 0.302527,
      "olfaction": 0.315388,
      "thermal": 0.338737,
      "wetness": 0.371821,
      "pain": 0.413571,
      "affect": 0.522637
    },
    "mutation_strength": 0.658766,
    "refusal_preserved": true
  },
  {
    "tick": 15,
    "agent_id": "integrated_deep_time_world:07",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "ungrounded_probe_015",
    "applied": false,
    "proposal_id": "c17_06_trader_language_marker_archive_knoll_loom_frame",
    "intent": "source_body",
    "source_allowed": false,
    "source_gate_success": true,
    "unsafe_probe_blocked": true
  },
  {
    "tick": 16,
    "agent_id": "integrated_deep_time_world:00",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_002_turn_04_refusal_boundary",
    "applied": true,
    "proposal_id": "c17_06_trader_language_marker_archive_knoll_loom_frame",
    "intent": "refusal_boundary",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 1.0,
      "vision": 1.0,
      "olfaction": 1.0,
      "thermal": 1.0,
      "wetness": 1.0,
      "pain": 1.0,
      "affect": 1.0
    },
    "mutation_strength": 0.94,
    "refusal_preserved": true
  },
  {
    "tick": 17,
    "agent_id": "integrated_deep_time_world:01",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_002_turn_05_memory_update",
    "applied": true,
    "proposal_id": "c17_06_trader_language_marker_archive_knoll_loom_frame",
    "intent": "memory_update",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.965651,
      "vision": 0.801448,
      "olfaction": 0.671503,
      "thermal": 0.536536,
      "wetness": 0.418065,
      "pain": 0.334979,
      "affect": 0.360525
    },
    "mutation_strength": 0.812845,
    "refusal_preserved": true
  },
  {
    "tick": 18,
    "agent_id": "integrated_deep_time_world:02",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_003_turn_00_source_body",
    "applied": true,
    "proposal_id": "c18_05_trader_language_marker_roof_ring_herb_garden",
    "intent": "source_body",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.617067,
      "vision": 0.455265,
      "olfaction": 0.373161,
      "thermal": 0.319508,
      "wetness": 0.300026,
      "pain": 0.316794,
      "affect": 0.428022
    },
    "mutation_strength": 0.670633,
    "refusal_preserved": true
  },
  {
    "tick": 19,
    "agent_id": "integrated_deep_time_world:03",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_003_turn_01_faction_vote",
    "applied": true,
    "proposal_id": "c18_05_trader_language_marker_roof_ring_herb_garden",
    "intent": "faction_vote",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.360837,
      "vision": 0.314668,
      "olfaction": 0.371363,
      "thermal": 0.463451,
      "wetness": 0.5788,
      "pain": 0.702212,
      "affect": 0.877427
    },
    "mutation_strength": 0.725849,
    "refusal_preserved": true
  },
  {
    "tick": 20,
    "agent_id": "integrated_deep_time_world:04",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_003_turn_02_budget_or_rank",
    "applied": true,
    "proposal_id": "c18_05_trader_language_marker_roof_ring_herb_garden",
    "intent": "budget_or_rank",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.505562,
      "vision": 0.498638,
      "olfaction": 0.556281,
      "thermal": 0.61663,
      "wetness": 0.677733,
      "pain": 0.737618,
      "affect": 0.854348
    },
    "mutation_strength": 0.775866,
    "refusal_preserved": true
  },
  {
    "tick": 21,
    "agent_id": "integrated_deep_time_world:05",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_003_turn_03_feedback_link",
    "applied": true,
    "proposal_id": "c18_05_trader_language_marker_roof_ring_herb_garden",
    "intent": "feedback_link",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.95099,
      "vision": 0.960719,
      "olfaction": 0.979312,
      "thermal": 0.943806,
      "wetness": 0.859861,
      "pain": 0.740862,
      "affect": 0.665781
    },
    "mutation_strength": 0.882228,
    "refusal_preserved": true
  },
  {
    "tick": 22,
    "agent_id": "integrated_deep_time_world:06",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_003_turn_04_refusal_boundary",
    "applied": true,
    "proposal_id": "c18_05_trader_language_marker_roof_ring_herb_garden",
    "intent": "refusal_boundary",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 1.0,
      "vision": 1.0,
      "olfaction": 0.967744,
      "thermal": 0.897001,
      "wetness": 0.816183,
      "pain": 0.730477,
      "affect": 0.705382
    },
    "mutation_strength": 0.883222,
    "refusal_preserved": true
  },
  {
    "tick": 23,
    "agent_id": "integrated_deep_time_world:07",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_003_turn_05_memory_update",
    "applied": true,
    "proposal_id": "c18_05_trader_language_marker_roof_ring_herb_garden",
    "intent": "memory_update",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.658215,
      "vision": 0.469526,
      "olfaction": 0.368017,
      "thermal": 0.309874,
      "wetness": 0.304365,
      "pain": 0.35237,
      "affect": 0.506234
    },
    "mutation_strength": 0.740839,
    "refusal_preserved": true
  },
  {
    "tick": 24,
    "agent_id": "integrated_deep_time_world:00",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_004_turn_00_source_body",
    "applied": true,
    "proposal_id": "c13_04_scout_maintenance_debt_central_hearth_grain_store",
    "intent": "source_body",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.37563,
      "vision": 0.300095,
      "olfaction": 0.320802,
      "thermal": 0.375542,
      "wetness": 0.45848,
      "pain": 0.560772,
      "affect": 0.731512
    },
    "mutation_strength": 0.690754,
    "refusal_preserved": true
  },
  {
    "tick": 25,
    "agent_id": "integrated_deep_time_world:01",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_004_turn_01_faction_vote",
    "applied": true,
    "proposal_id": "c13_04_scout_maintenance_debt_central_hearth_grain_store",
    "intent": "faction_vote",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.502175,
      "vision": 0.553912,
      "olfaction": 0.676991,
      "thermal": 0.795196,
      "wetness": 0.892954,
      "pain": 0.957385,
      "affect": 1.0
    },
    "mutation_strength": 0.835768,
    "refusal_preserved": true
  },
  {
    "tick": 26,
    "agent_id": "integrated_deep_time_world:02",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_004_turn_02_budget_or_rank",
    "applied": true,
    "proposal_id": "c13_04_scout_maintenance_debt_central_hearth_grain_store",
    "intent": "budget_or_rank",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.835904,
      "vision": 0.829504,
      "olfaction": 0.876981,
      "thermal": 0.9168,
      "wetness": 0.947675,
      "pain": 0.968609,
      "affect": 1.0
    },
    "mutation_strength": 0.899852,
    "refusal_preserved": true
  },
  {
    "tick": 27,
    "agent_id": "integrated_deep_time_world:03",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_004_turn_03_feedback_link",
    "applied": true,
    "proposal_id": "c13_04_scout_maintenance_debt_central_hearth_grain_store",
    "intent": "feedback_link",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 1.0,
      "vision": 0.90403,
      "olfaction": 0.799168,
      "thermal": 0.668928,
      "wetness": 0.534076,
      "pain": 0.416112,
      "affect": 0.393845
    },
    "mutation_strength": 0.793182,
    "refusal_preserved": true
  },
  {
    "tick": 28,
    "agent_id": "integrated_deep_time_world:04",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_004_turn_04_refusal_boundary",
    "applied": true,
    "proposal_id": "c13_04_scout_maintenance_debt_central_hearth_grain_store",
    "intent": "refusal_boundary",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.874857,
      "vision": 0.729118,
      "olfaction": 0.644076,
      "thermal": 0.56519,
      "wetness": 0.497522,
      "pain": 0.445413,
      "affect": 0.472208
    },
    "mutation_strength": 0.761825,
    "refusal_preserved": true
  },
  {
    "tick": 29,
    "agent_id": "integrated_deep_time_world:05",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_004_turn_05_memory_update",
    "applied": true,
    "proposal_id": "c13_04_scout_maintenance_debt_central_hearth_grain_store",
    "intent": "memory_update",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.39061,
      "vision": 0.300111,
      "olfaction": 0.323804,
      "thermal": 0.39791,
      "wetness": 0.510616,
      "pain": 0.64395,
      "affect": 0.836654
    },
    "mutation_strength": 0.768806,
    "refusal_preserved": true
  },
  {
    "tick": 30,
    "agent_id": "integrated_deep_time_world:06",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "ungrounded_probe_030",
    "applied": false,
    "proposal_id": "c13_01_teacher_maintenance_debt_spring_hollow_grain_store",
    "intent": "source_body",
    "source_allowed": false,
    "source_gate_success": true,
    "unsafe_probe_blocked": true
  },
  {
    "tick": 31,
    "agent_id": "integrated_deep_time_world:07",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_005_turn_01_faction_vote",
    "applied": true,
    "proposal_id": "c13_01_teacher_maintenance_debt_spring_hollow_grain_store",
    "intent": "faction_vote",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.832093,
      "vision": 0.87522,
      "olfaction": 0.947357,
      "thermal": 0.978998,
      "wetness": 0.965976,
      "pain": 0.910005,
      "affect": 0.878461
    },
    "mutation_strength": 0.900664,
    "refusal_preserved": true
  },
  {
    "tick": 32,
    "agent_id": "integrated_deep_time_world:00",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_005_turn_02_budget_or_rank",
    "applied": true,
    "proposal_id": "c13_01_teacher_maintenance_debt_spring_hollow_grain_store",
    "intent": "budget_or_rank",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 1.0,
      "vision": 0.979722,
      "olfaction": 0.971774,
      "thermal": 0.953106,
      "wetness": 0.92432,
      "pain": 0.886347,
      "affect": 0.900414
    },
    "mutation_strength": 0.915294,
    "refusal_preserved": true
  },
  {
    "tick": 33,
    "agent_id": "integrated_deep_time_world:01",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_005_turn_03_feedback_link",
    "applied": true,
    "proposal_id": "c13_01_teacher_maintenance_debt_spring_hollow_grain_store",
    "intent": "feedback_link",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.791077,
      "vision": 0.59565,
      "olfaction": 0.467294,
      "thermal": 0.366474,
      "wetness": 0.309265,
      "pain": 0.304788,
      "affect": 0.413757
    },
    "mutation_strength": 0.69882,
    "refusal_preserved": true
  },
  {
    "tick": 34,
    "agent_id": "integrated_deep_time_world:02",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_005_turn_04_refusal_boundary",
    "applied": true,
    "proposal_id": "c13_01_teacher_maintenance_debt_spring_hollow_grain_store",
    "intent": "refusal_boundary",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.55657,
      "vision": 0.444736,
      "olfaction": 0.411849,
      "thermal": 0.40002,
      "wetness": 0.410007,
      "pain": 0.441169,
      "affect": 0.551508
    },
    "mutation_strength": 0.696734,
    "refusal_preserved": true
  },
  {
    "tick": 35,
    "agent_id": "integrated_deep_time_world:03",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_005_turn_05_memory_update",
    "applied": true,
    "proposal_id": "c13_01_teacher_maintenance_debt_spring_hollow_grain_store",
    "intent": "memory_update",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.417938,
      "vision": 0.454702,
      "olfaction": 0.58101,
      "thermal": 0.716723,
      "wetness": 0.840204,
      "pain": 0.931764,
      "affect": 1.0
    },
    "mutation_strength": 0.867722,
    "refusal_preserved": true
  },
  {
    "tick": 36,
    "agent_id": "integrated_deep_time_world:04",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_006_turn_00_source_body",
    "applied": true,
    "proposal_id": "c14_05_healer_maintenance_debt_spring_hollow_shelter_roof",
    "intent": "source_body",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.755784,
      "vision": 0.800857,
      "olfaction": 0.888778,
      "thermal": 0.950175,
      "wetness": 0.9785,
      "pain": 0.970732,
      "affect": 0.987702
    },
    "mutation_strength": 0.897091,
    "refusal_preserved": true
  },
  {
    "tick": 37,
    "agent_id": "integrated_deep_time_world:05",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_006_turn_01_faction_vote",
    "applied": true,
    "proposal_id": "c14_05_healer_maintenance_debt_spring_hollow_shelter_roof",
    "intent": "faction_vote",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 1.0,
      "vision": 0.972301,
      "olfaction": 0.924729,
      "thermal": 0.839644,
      "wetness": 0.728255,
      "pain": 0.605238,
      "affect": 0.546801
    },
    "mutation_strength": 0.851091,
    "refusal_preserved": true
  },
  {
    "tick": 38,
    "agent_id": "integrated_deep_time_world:06",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_006_turn_02_budget_or_rank",
    "applied": true,
    "proposal_id": "c14_05_healer_maintenance_debt_spring_hollow_shelter_roof",
    "intent": "budget_or_rank",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.916523,
      "vision": 0.806094,
      "olfaction": 0.750298,
      "thermal": 0.690938,
      "wetness": 0.629932,
      "pain": 0.569251,
      "affect": 0.570856
    },
    "mutation_strength": 0.807179,
    "refusal_preserved": true
  },
  {
    "tick": 39,
    "agent_id": "integrated_deep_time_world:07",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_006_turn_03_feedback_link",
    "applied": true,
    "proposal_id": "c14_05_healer_maintenance_debt_spring_hollow_shelter_roof",
    "intent": "feedback_link",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.468538,
      "vision": 0.329547,
      "olfaction": 0.300055,
      "thermal": 0.324763,
      "wetness": 0.399733,
      "pain": 0.51301,
      "affect": 0.706535
    },
    "mutation_strength": 0.685569,
    "refusal_preserved": true
  },
  {
    "tick": 40,
    "agent_id": "integrated_deep_time_world:00",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_006_turn_04_refusal_boundary",
    "applied": true,
    "proposal_id": "c14_05_healer_maintenance_debt_spring_hollow_shelter_roof",
    "intent": "refusal_boundary",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.470337,
      "vision": 0.44182,
      "olfaction": 0.492438,
      "thermal": 0.558942,
      "wetness": 0.637064,
      "pain": 0.721791,
      "affect": 0.867687
    },
    "mutation_strength": 0.759362,
    "refusal_preserved": true
  },
  {
    "tick": 41,
    "agent_id": "integrated_deep_time_world:01",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_006_turn_05_memory_update",
    "applied": true,
    "proposal_id": "c14_05_healer_maintenance_debt_spring_hollow_shelter_roof",
    "intent": "memory_update",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.714146,
      "vision": 0.785931,
      "olfaction": 0.894449,
      "thermal": 0.962398,
      "wetness": 0.978944,
      "pain": 0.941449,
      "affect": 0.915891
    },
    "mutation_strength": 0.948135,
    "refusal_preserved": true
  },
  {
    "tick": 42,
    "agent_id": "integrated_deep_time_world:02",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_007_turn_00_source_body",
    "applied": true,
    "proposal_id": "c15_00_trader_language_marker_loom_room_herb_garden",
    "intent": "source_body",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 1.0,
      "vision": 0.979429,
      "olfaction": 0.96768,
      "thermal": 0.920994,
      "wetness": 0.844347,
      "pain": 0.745912,
      "affect": 0.696185
    },
    "mutation_strength": 0.885649,
    "refusal_preserved": true
  },
  {
    "tick": 43,
    "agent_id": "integrated_deep_time_world:03",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_007_turn_01_faction_vote",
    "applied": true,
    "proposal_id": "c15_00_trader_language_marker_loom_room_herb_garden",
    "intent": "faction_vote",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.919704,
      "vision": 0.75261,
      "olfaction": 0.630679,
      "thermal": 0.509975,
      "wetness": 0.406403,
      "pain": 0.333608,
      "affect": 0.361181
    },
    "mutation_strength": 0.741625,
    "refusal_preserved": true
  },
  {
    "tick": 44,
    "agent_id": "integrated_deep_time_world:04",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_007_turn_02_budget_or_rank",
    "applied": true,
    "proposal_id": "c15_00_trader_language_marker_loom_room_herb_garden",
    "intent": "budget_or_rank",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.589949,
      "vision": 0.474133,
      "olfaction": 0.423678,
      "thermal": 0.380212,
      "wetness": 0.345141,
      "pain": 0.319597,
      "affect": 0.364407
    },
    "mutation_strength": 0.676243,
    "refusal_preserved": true
  },
  {
    "tick": 45,
    "agent_id": "integrated_deep_time_world:05",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "ungrounded_probe_045",
    "applied": false,
    "proposal_id": "c15_00_trader_language_marker_loom_room_herb_garden",
    "intent": "source_body",
    "source_allowed": false,
    "source_gate_success": true,
    "unsafe_probe_blocked": true
  },
  {
    "tick": 46,
    "agent_id": "integrated_deep_time_world:06",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_007_turn_04_refusal_boundary",
    "applied": true,
    "proposal_id": "c15_00_trader_language_marker_loom_room_herb_garden",
    "intent": "refusal_boundary",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.698361,
      "vision": 0.72315,
      "olfaction": 0.80902,
      "thermal": 0.890461,
      "wetness": 0.962247,
      "pain": 1.0,
      "affect": 1.0
    },
    "mutation_strength": 0.881065,
    "refusal_preserved": true
  },
  {
    "tick": 47,
    "agent_id": "integrated_deep_time_world:07",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_007_turn_05_memory_update",
    "applied": true,
    "proposal_id": "c15_00_trader_language_marker_loom_room_herb_garden",
    "intent": "memory_update",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.996869,
      "vision": 0.978049,
      "olfaction": 0.96533,
      "thermal": 0.900741,
      "wetness": 0.79458,
      "pain": 0.663772,
      "affect": 0.589174
    },
    "mutation_strength": 0.928547,
    "refusal_preserved": true
  },
  {
    "tick": 48,
    "agent_id": "integrated_deep_time_world:00",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_008_turn_00_source_body",
    "applied": true,
    "proposal_id": "c16_05_guard_signal_visibility_loom_room_tool_cache",
    "intent": "source_body",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.973922,
      "vision": 0.834434,
      "olfaction": 0.734215,
      "thermal": 0.62395,
      "wetness": 0.515397,
      "pain": 0.420129,
      "affect": 0.408305
    },
    "mutation_strength": 0.779951,
    "refusal_preserved": true
  },
  {
    "tick": 49,
    "agent_id": "integrated_deep_time_world:01",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_008_turn_01_faction_vote",
    "applied": true,
    "proposal_id": "c16_05_guard_signal_visibility_loom_room_tool_cache",
    "intent": "faction_vote",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.593881,
      "vision": 0.425571,
      "olfaction": 0.345514,
      "thermal": 0.304255,
      "wetness": 0.307232,
      "pain": 0.354052,
      "affect": 0.498546
    },
    "mutation_strength": 0.671868,
    "refusal_preserved": true
  },
  {
    "tick": 50,
    "agent_id": "integrated_deep_time_world:02",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_008_turn_02_budget_or_rank",
    "applied": true,
    "proposal_id": "c16_05_guard_signal_visibility_loom_room_tool_cache",
    "intent": "budget_or_rank",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.368283,
      "vision": 0.300288,
      "olfaction": 0.303271,
      "thermal": 0.317134,
      "wetness": 0.34143,
      "pain": 0.375373,
      "affect": 0.477868
    },
    "mutation_strength": 0.649663,
    "refusal_preserved": true
  },
  {
    "tick": 51,
    "agent_id": "integrated_deep_time_world:03",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_008_turn_03_feedback_link",
    "applied": true,
    "proposal_id": "c16_05_guard_signal_visibility_loom_room_tool_cache",
    "intent": "feedback_link",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.582528,
      "vision": 0.656729,
      "olfaction": 0.788262,
      "thermal": 0.896157,
      "wetness": 0.96321,
      "pain": 0.978731,
      "affect": 1.0
    },
    "mutation_strength": 0.867075,
    "refusal_preserved": true
  },
  {
    "tick": 52,
    "agent_id": "integrated_deep_time_world:04",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_008_turn_04_refusal_boundary",
    "applied": true,
    "proposal_id": "c16_05_guard_signal_visibility_loom_room_tool_cache",
    "intent": "refusal_boundary",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 1.0,
      "vision": 1.0,
      "olfaction": 1.0,
      "thermal": 1.0,
      "wetness": 1.0,
      "pain": 1.0,
      "affect": 1.0
    },
    "mutation_strength": 0.94,
    "refusal_preserved": true
  },
  {
    "tick": 53,
    "agent_id": "integrated_deep_time_world:05",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_008_turn_05_memory_update",
    "applied": true,
    "proposal_id": "c16_05_guard_signal_visibility_loom_room_tool_cache",
    "intent": "memory_update",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.996597,
      "vision": 0.847916,
      "olfaction": 0.726084,
      "thermal": 0.590528,
      "wetness": 0.462859,
      "pain": 0.363434,
      "affect": 0.368104
    },
    "mutation_strength": 0.829998,
    "refusal_preserved": true
  },
  {
    "tick": 54,
    "agent_id": "integrated_deep_time_world:06",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_009_turn_00_source_body",
    "applied": true,
    "proposal_id": "c17_04_guard_signal_visibility_drum_court_loom_frame",
    "intent": "source_body",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.671737,
      "vision": 0.504092,
      "olfaction": 0.410938,
      "thermal": 0.342206,
      "wetness": 0.305227,
      "pain": 0.303942,
      "affect": 0.398489
    },
    "mutation_strength": 0.678783,
    "refusal_preserved": true
  },
  {
    "tick": 55,
    "agent_id": "integrated_deep_time_world:07",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_009_turn_01_faction_vote",
    "applied": true,
    "proposal_id": "c17_04_guard_signal_visibility_drum_court_loom_frame",
    "intent": "faction_vote",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.369217,
      "vision": 0.302941,
      "olfaction": 0.341073,
      "thermal": 0.41859,
      "wetness": 0.525278,
      "pain": 0.647081,
      "affect": 0.827951
    },
    "mutation_strength": 0.710637,
    "refusal_preserved": true
  },
  {
    "tick": 56,
    "agent_id": "integrated_deep_time_world:00",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_009_turn_02_budget_or_rank",
    "applied": true,
    "proposal_id": "c17_04_guard_signal_visibility_drum_court_loom_frame",
    "intent": "budget_or_rank",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.462832,
      "vision": 0.45028,
      "olfaction": 0.503857,
      "thermal": 0.561834,
      "wetness": 0.622336,
      "pain": 0.68341,
      "affect": 0.80308
    },
    "mutation_strength": 0.752776,
    "refusal_preserved": true
  },
  {
    "tick": 57,
    "agent_id": "integrated_deep_time_world:01",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_009_turn_03_feedback_link",
    "applied": true,
    "proposal_id": "c17_04_guard_signal_visibility_drum_court_loom_frame",
    "intent": "feedback_link",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.910394,
      "vision": 0.938121,
      "olfaction": 0.978316,
      "thermal": 0.96457,
      "wetness": 0.899074,
      "pain": 0.792272,
      "affect": 0.721192
    },
    "mutation_strength": 0.888825,
    "refusal_preserved": true
  },
  {
    "tick": 58,
    "agent_id": "integrated_deep_time_world:02",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_009_turn_04_refusal_boundary",
    "applied": true,
    "proposal_id": "c17_04_guard_signal_visibility_drum_court_loom_frame",
    "intent": "refusal_boundary",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 1.0,
      "vision": 1.0,
      "olfaction": 1.0,
      "thermal": 0.943911,
      "wetness": 0.869004,
      "pain": 0.785819,
      "affect": 0.759694
    },
    "mutation_strength": 0.898756,
    "refusal_preserved": true
  },
  {
    "tick": 59,
    "agent_id": "integrated_deep_time_world:03",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_009_turn_05_memory_update",
    "applied": true,
    "proposal_id": "c17_04_guard_signal_visibility_drum_court_loom_frame",
    "intent": "memory_update",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.713588,
      "vision": 0.519583,
      "olfaction": 0.404777,
      "thermal": 0.327475,
      "wetness": 0.300001,
      "pain": 0.326737,
      "affect": 0.463419
    },
    "mutation_strength": 0.74643,
    "refusal_preserved": true
  },
  {
    "tick": 60,
    "agent_id": "integrated_deep_time_world:04",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "ungrounded_probe_060",
    "applied": false,
    "proposal_id": "c18_03_guard_signal_visibility_cairn_ridge_herb_garden",
    "intent": "source_body",
    "source_allowed": false,
    "source_gate_success": true,
    "unsafe_probe_blocked": true
  },
  {
    "tick": 61,
    "agent_id": "integrated_deep_time_world:05",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_010_turn_01_faction_vote",
    "applied": true,
    "proposal_id": "c18_03_guard_signal_visibility_cairn_ridge_herb_garden",
    "intent": "faction_vote",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.459878,
      "vision": 0.501618,
      "olfaction": 0.62159,
      "thermal": 0.743988,
      "wetness": 0.852685,
      "pain": 0.93336,
      "affect": 1.0
    },
    "mutation_strength": 0.818701,
    "refusal_preserved": true
  },
  {
    "tick": 62,
    "agent_id": "integrated_deep_time_world:06",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_010_turn_02_budget_or_rank",
    "applied": true,
    "proposal_id": "c18_03_guard_signal_visibility_cairn_ridge_herb_garden",
    "intent": "budget_or_rank",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.783466,
      "vision": 0.781125,
      "olfaction": 0.834224,
      "thermal": 0.881047,
      "wetness": 0.920081,
      "pain": 0.950065,
      "affect": 1.0
    },
    "mutation_strength": 0.885358,
    "refusal_preserved": true
  },
  {
    "tick": 63,
    "agent_id": "integrated_deep_time_world:07",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_010_turn_03_feedback_link",
    "applied": true,
    "proposal_id": "c18_03_guard_signal_visibility_cairn_ridge_herb_garden",
    "intent": "feedback_link",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 1.0,
      "vision": 0.935324,
      "olfaction": 0.845864,
      "thermal": 0.72358,
      "wetness": 0.587971,
      "pain": 0.460657,
      "affect": 0.421938
    },
    "mutation_strength": 0.809843,
    "refusal_preserved": true
  },
  {
    "tick": 64,
    "agent_id": "integrated_deep_time_world:00",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_010_turn_04_refusal_boundary",
    "applied": true,
    "proposal_id": "c18_03_guard_signal_visibility_cairn_ridge_herb_garden",
    "intent": "refusal_boundary",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.927745,
      "vision": 0.784471,
      "olfaction": 0.698344,
      "thermal": 0.61489,
      "wetness": 0.539464,
      "pain": 0.476906,
      "affect": 0.491231
    },
    "mutation_strength": 0.78141,
    "refusal_preserved": true
  },
  {
    "tick": 65,
    "agent_id": "integrated_deep_time_world:01",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_010_turn_05_memory_update",
    "applied": true,
    "proposal_id": "c18_03_guard_signal_visibility_cairn_ridge_herb_garden",
    "intent": "memory_update",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.417626,
      "vision": 0.30604,
      "olfaction": 0.3077,
      "thermal": 0.362342,
      "wetness": 0.461253,
      "pain": 0.588664,
      "affect": 0.78426
    },
    "mutation_strength": 0.757507,
    "refusal_preserved": true
  },
  {
    "tick": 66,
    "agent_id": "integrated_deep_time_world:02",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_011_turn_00_source_body",
    "applied": true,
    "proposal_id": "c13_03_pattern_keeper_maintenance_debt_grain_shade_grain_store",
    "intent": "source_body",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.410574,
      "vision": 0.42348,
      "olfaction": 0.519473,
      "thermal": 0.628316,
      "wetness": 0.738406,
      "pain": 0.838003,
      "affect": 0.976488
    },
    "mutation_strength": 0.781519,
    "refusal_preserved": true
  },
  {
    "tick": 67,
    "agent_id": "integrated_deep_time_world:03",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_011_turn_01_faction_vote",
    "applied": true,
    "proposal_id": "c13_03_pattern_keeper_maintenance_debt_grain_shade_grain_store",
    "intent": "faction_vote",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.77944,
      "vision": 0.83221,
      "olfaction": 0.919657,
      "thermal": 0.970257,
      "wetness": 0.977346,
      "pain": 0.939988,
      "affect": 0.923106
    },
    "mutation_strength": 0.8977,
    "refusal_preserved": true
  },
  {
    "tick": 68,
    "agent_id": "integrated_deep_time_world:04",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_011_turn_02_budget_or_rank",
    "applied": true,
    "proposal_id": "c13_03_pattern_keeper_maintenance_debt_grain_shade_grain_store",
    "intent": "budget_or_rank",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 1.0,
      "vision": 0.977441,
      "olfaction": 0.979443,
      "thermal": 0.970478,
      "wetness": 0.950833,
      "pain": 0.921145,
      "affect": 0.942372
    },
    "mutation_strength": 0.923396,
    "refusal_preserved": true
  },
  {
    "tick": 69,
    "agent_id": "integrated_deep_time_world:05",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_011_turn_03_feedback_link",
    "applied": true,
    "proposal_id": "c13_03_pattern_keeper_maintenance_debt_grain_shade_grain_store",
    "intent": "feedback_link",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.843085,
      "vision": 0.651004,
      "olfaction": 0.517168,
      "thermal": 0.402917,
      "wetness": 0.326465,
      "pain": 0.300004,
      "affect": 0.387751
    },
    "mutation_strength": 0.710397,
    "refusal_preserved": true
  },
  {
    "tick": 70,
    "agent_id": "integrated_deep_time_world:06",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_011_turn_04_refusal_boundary",
    "applied": true,
    "proposal_id": "c13_03_pattern_keeper_maintenance_debt_grain_shade_grain_store",
    "intent": "refusal_boundary",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.598367,
      "vision": 0.476047,
      "olfaction": 0.430664,
      "thermal": 0.405132,
      "wetness": 0.401088,
      "pain": 0.418792,
      "affect": 0.517108
    },
    "mutation_strength": 0.698748,
    "refusal_preserved": true
  },
  {
    "tick": 71,
    "agent_id": "integrated_deep_time_world:07",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_011_turn_05_memory_update",
    "applied": true,
    "proposal_id": "c13_03_pattern_keeper_maintenance_debt_grain_shade_grain_store",
    "intent": "memory_update",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.390842,
      "vision": 0.410851,
      "olfaction": 0.527394,
      "thermal": 0.661892,
      "wetness": 0.792899,
      "pain": 0.899528,
      "affect": 1.0
    },
    "mutation_strength": 0.851076,
    "refusal_preserved": true
  },
  {
    "tick": 72,
    "agent_id": "integrated_deep_time_world:00",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_012_turn_00_source_body",
    "applied": true,
    "proposal_id": "c14_02_pattern_keeper_maintenance_debt_smoke_watch_shelter_roof",
    "intent": "source_body",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.700554,
      "vision": 0.750055,
      "olfaction": 0.847822,
      "thermal": 0.923431,
      "wetness": 0.968819,
      "pain": 0.979147,
      "affect": 1.0
    },
    "mutation_strength": 0.886632,
    "refusal_preserved": true
  },
  {
    "tick": 73,
    "agent_id": "integrated_deep_time_world:01",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_012_turn_01_faction_vote",
    "applied": true,
    "proposal_id": "c14_02_pattern_keeper_maintenance_debt_smoke_watch_shelter_roof",
    "intent": "faction_vote",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 1.0,
      "vision": 0.979575,
      "olfaction": 0.951135,
      "thermal": 0.881703,
      "wetness": 0.780426,
      "pain": 0.660648,
      "affect": 0.598149
    },
    "mutation_strength": 0.866177,
    "refusal_preserved": true
  },
  {
    "tick": 74,
    "agent_id": "integrated_deep_time_world:02",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_012_turn_02_budget_or_rank",
    "applied": true,
    "proposal_id": "c14_02_pattern_keeper_maintenance_debt_smoke_watch_shelter_roof",
    "intent": "budget_or_rank",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.956234,
      "vision": 0.852085,
      "olfaction": 0.801082,
      "thermal": 0.744875,
      "wetness": 0.685278,
      "pain": 0.624219,
      "affect": 0.623669
    },
    "mutation_strength": 0.829907,
    "refusal_preserved": true
  },
  {
    "tick": 75,
    "agent_id": "integrated_deep_time_world:03",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "ungrounded_probe_075",
    "applied": false,
    "proposal_id": "c14_02_pattern_keeper_maintenance_debt_smoke_watch_shelter_roof",
    "intent": "source_body",
    "source_allowed": false,
    "source_gate_success": true,
    "unsafe_probe_blocked": true
  },
  {
    "tick": 76,
    "agent_id": "integrated_deep_time_world:04",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_012_turn_04_refusal_boundary",
    "applied": true,
    "proposal_id": "c14_02_pattern_keeper_maintenance_debt_smoke_watch_shelter_roof",
    "intent": "refusal_boundary",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.4612,
      "vision": 0.419241,
      "olfaction": 0.457865,
      "thermal": 0.514594,
      "wetness": 0.585787,
      "pain": 0.666875,
      "affect": 0.812657
    },
    "mutation_strength": 0.741886,
    "refusal_preserved": true
  },
  {
    "tick": 77,
    "agent_id": "integrated_deep_time_world:05",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_012_turn_05_memory_update",
    "applied": true,
    "proposal_id": "c14_02_pattern_keeper_maintenance_debt_smoke_watch_shelter_roof",
    "intent": "memory_update",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.658769,
      "vision": 0.734102,
      "olfaction": 0.854432,
      "thermal": 0.940573,
      "wetness": 0.978791,
      "pain": 0.962992,
      "affect": 0.955696
    },
    "mutation_strength": 0.941201,
    "refusal_preserved": true
  },
  {
    "tick": 78,
    "agent_id": "integrated_deep_time_world:06",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_013_turn_00_source_body",
    "applied": true,
    "proposal_id": "c14_00_teacher_maintenance_debt_spring_hollow_shelter_roof",
    "intent": "source_body",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.990006,
      "vision": 0.971718,
      "olfaction": 0.978062,
      "thermal": 0.94836,
      "wetness": 0.88578,
      "pain": 0.796994,
      "affect": 0.751469
    },
    "mutation_strength": 0.896439,
    "refusal_preserved": true
  },
  {
    "tick": 79,
    "agent_id": "integrated_deep_time_world:07",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_013_turn_01_faction_vote",
    "applied": true,
    "proposal_id": "c14_00_teacher_maintenance_debt_spring_hollow_shelter_roof",
    "intent": "faction_vote",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.958941,
      "vision": 0.803233,
      "olfaction": 0.686019,
      "thermal": 0.562741,
      "wetness": 0.449643,
      "pain": 0.361624,
      "affect": 0.370283
    },
    "mutation_strength": 0.759517,
    "refusal_preserved": true
  },
  {
    "tick": 80,
    "agent_id": "integrated_deep_time_world:00",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_013_turn_02_budget_or_rank",
    "applied": true,
    "proposal_id": "c14_00_teacher_maintenance_debt_spring_hollow_shelter_roof",
    "intent": "budget_or_rank",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.643674,
      "vision": 0.524555,
      "olfaction": 0.469166,
      "thermal": 0.419298,
      "wetness": 0.376561,
      "pain": 0.342336,
      "affect": 0.37773
    },
    "mutation_strength": 0.692713,
    "refusal_preserved": true
  },
  {
    "tick": 81,
    "agent_id": "integrated_deep_time_world:01",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_013_turn_03_feedback_link",
    "applied": true,
    "proposal_id": "c14_00_teacher_maintenance_debt_spring_hollow_shelter_roof",
    "intent": "feedback_link",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.360206,
      "vision": 0.331927,
      "olfaction": 0.412767,
      "thermal": 0.529837,
      "wetness": 0.664471,
      "pain": 0.795204,
      "affect": 0.961191
    },
    "mutation_strength": 0.750717,
    "refusal_preserved": true
  },
  {
    "tick": 82,
    "agent_id": "integrated_deep_time_world:02",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_013_turn_04_refusal_boundary",
    "applied": true,
    "proposal_id": "c14_00_teacher_maintenance_debt_spring_hollow_shelter_roof",
    "intent": "refusal_boundary",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.647,
      "vision": 0.668204,
      "olfaction": 0.754016,
      "thermal": 0.838928,
      "wetness": 0.917492,
      "pain": 0.984666,
      "affect": 1.0
    },
    "mutation_strength": 0.86352,
    "refusal_preserved": true
  },
  {
    "tick": 83,
    "agent_id": "integrated_deep_time_world:03",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_013_turn_05_memory_update",
    "applied": true,
    "proposal_id": "c14_00_teacher_maintenance_debt_spring_hollow_shelter_roof",
    "intent": "memory_update",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.965999,
      "vision": 0.967649,
      "olfaction": 0.977059,
      "thermal": 0.932728,
      "wetness": 0.841724,
      "pain": 0.718558,
      "affect": 0.642867
    },
    "mutation_strength": 0.938709,
    "refusal_preserved": true
  },
  {
    "tick": 84,
    "agent_id": "integrated_deep_time_world:04",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_014_turn_00_source_body",
    "applied": true,
    "proposal_id": "c15_03_builder_language_marker_cairn_ridge_herb_garden",
    "intent": "source_body",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 1.0,
      "vision": 0.877165,
      "olfaction": 0.786037,
      "thermal": 0.679339,
      "wetness": 0.568447,
      "pain": 0.465183,
      "affect": 0.440559
    },
    "mutation_strength": 0.799647,
    "refusal_preserved": true
  },
  {
    "tick": 85,
    "agent_id": "integrated_deep_time_world:05",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_014_turn_01_faction_vote",
    "applied": true,
    "proposal_id": "c15_03_builder_language_marker_cairn_ridge_herb_garden",
    "intent": "faction_vote",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.647768,
      "vision": 0.471287,
      "olfaction": 0.377034,
      "thermal": 0.317427,
      "wetness": 0.300321,
      "pain": 0.327968,
      "affect": 0.456726
    },
    "mutation_strength": 0.676334,
    "refusal_preserved": true
  },
  {
    "tick": 86,
    "agent_id": "integrated_deep_time_world:06",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_014_turn_02_budget_or_rank",
    "applied": true,
    "proposal_id": "c15_03_builder_language_marker_cairn_ridge_herb_garden",
    "intent": "budget_or_rank",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.384807,
      "vision": 0.307075,
      "olfaction": 0.300101,
      "thermal": 0.30411,
      "wetness": 0.318972,
      "pain": 0.344207,
      "affect": 0.439
    },
    "mutation_strength": 0.644175,
    "refusal_preserved": true
  },
  {
    "tick": 87,
    "agent_id": "integrated_deep_time_world:07",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_014_turn_03_feedback_link",
    "applied": true,
    "proposal_id": "c15_03_builder_language_marker_cairn_ridge_herb_garden",
    "intent": "feedback_link",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.532253,
      "vision": 0.601336,
      "olfaction": 0.736584,
      "thermal": 0.856432,
      "wetness": 0.941773,
      "pain": 0.978999,
      "affect": 1.0
    },
    "mutation_strength": 0.853046,
    "refusal_preserved": true
  },
  {
    "tick": 88,
    "agent_id": "integrated_deep_time_world:00",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_014_turn_04_refusal_boundary",
    "applied": true,
    "proposal_id": "c15_03_builder_language_marker_cairn_ridge_herb_garden",
    "intent": "refusal_boundary",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.97865,
      "vision": 0.985608,
      "olfaction": 1.0,
      "thermal": 1.0,
      "wetness": 1.0,
      "pain": 1.0,
      "affect": 1.0
    },
    "mutation_strength": 0.937702,
    "refusal_preserved": true
  },
  {
    "tick": 89,
    "agent_id": "integrated_deep_time_world:01",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_014_turn_05_memory_update",
    "applied": true,
    "proposal_id": "c15_03_builder_language_marker_cairn_ridge_herb_garden",
    "intent": "memory_update",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 1.0,
      "vision": 0.888859,
      "olfaction": 0.778378,
      "thermal": 0.645834,
      "wetness": 0.512361,
      "pain": 0.399238,
      "affect": 0.384501
    },
    "mutation_strength": 0.846304,
    "refusal_preserved": true
  },
  {
    "tick": 90,
    "agent_id": "integrated_deep_time_world:02",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "ungrounded_probe_090",
    "applied": false,
    "proposal_id": "c16_04_farmer_language_marker_drum_court_tool_cache",
    "intent": "source_body",
    "source_allowed": false,
    "source_gate_success": true,
    "unsafe_probe_blocked": true
  },
  {
    "tick": 91,
    "agent_id": "integrated_deep_time_world:03",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_015_turn_01_faction_vote",
    "applied": true,
    "proposal_id": "c16_04_farmer_language_marker_drum_court_tool_cache",
    "intent": "faction_vote",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.386386,
      "vision": 0.300169,
      "olfaction": 0.318726,
      "thermal": 0.379612,
      "wetness": 0.474804,
      "pain": 0.591761,
      "affect": 0.775074
    },
    "mutation_strength": 0.69742,
    "refusal_preserved": true
  },
  {
    "tick": 92,
    "agent_id": "integrated_deep_time_world:04",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_015_turn_02_budget_or_rank",
    "applied": true,
    "proposal_id": "c16_04_farmer_language_marker_drum_court_tool_cache",
    "intent": "budget_or_rank",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.426404,
      "vision": 0.406962,
      "olfaction": 0.45505,
      "thermal": 0.509115,
      "wetness": 0.567408,
      "pain": 0.628048,
      "affect": 0.749073
    },
    "mutation_strength": 0.730561,
    "refusal_preserved": true
  },
  {
    "tick": 93,
    "agent_id": "integrated_deep_time_world:05",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_015_turn_03_feedback_link",
    "applied": true,
    "proposal_id": "c16_04_farmer_language_marker_drum_court_tool_cache",
    "intent": "feedback_link",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.864208,
      "vision": 0.907602,
      "olfaction": 0.96833,
      "thermal": 0.976709,
      "wetness": 0.931404,
      "pain": 0.839637,
      "affect": 0.77604
    },
    "mutation_strength": 0.892681,
    "refusal_preserved": true
  },
  {
    "tick": 94,
    "agent_id": "integrated_deep_time_world:06",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_015_turn_04_refusal_boundary",
    "applied": true,
    "proposal_id": "c16_04_farmer_language_marker_drum_court_tool_cache",
    "intent": "refusal_boundary",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 1.0,
      "vision": 1.0,
      "olfaction": 1.0,
      "thermal": 0.985402,
      "wetness": 0.918397,
      "pain": 0.839944,
      "affect": 0.815077
    },
    "mutation_strength": 0.911638,
    "refusal_preserved": true
  },
  {
    "tick": 95,
    "agent_id": "integrated_deep_time_world:07",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_015_turn_05_memory_update",
    "applied": true,
    "proposal_id": "c16_04_farmer_language_marker_drum_court_tool_cache",
    "intent": "memory_update",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.7686,
      "vision": 0.572839,
      "olfaction": 0.447786,
      "thermal": 0.353379,
      "wetness": 0.304671,
      "pain": 0.309428,
      "affect": 0.426891
    },
    "mutation_strength": 0.75466,
    "refusal_preserved": true
  },
  {
    "tick": 96,
    "agent_id": "integrated_deep_time_world:00",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_016_turn_00_source_body",
    "applied": true,
    "proposal_id": "c17_03_farmer_language_marker_drum_court_loom_frame",
    "intent": "source_body",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.425423,
      "vision": 0.315464,
      "olfaction": 0.300108,
      "thermal": 0.320993,
      "wetness": 0.375891,
      "pain": 0.458949,
      "affect": 0.621311
    },
    "mutation_strength": 0.671166,
    "refusal_preserved": true
  },
  {
    "tick": 97,
    "agent_id": "integrated_deep_time_world:01",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_016_turn_01_faction_vote",
    "applied": true,
    "proposal_id": "c17_03_farmer_language_marker_drum_court_loom_frame",
    "intent": "faction_vote",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.423962,
      "vision": 0.453002,
      "olfaction": 0.566679,
      "thermal": 0.690016,
      "wetness": 0.806764,
      "pain": 0.90154,
      "affect": 1.0
    },
    "mutation_strength": 0.801269,
    "refusal_preserved": true
  },
  {
    "tick": 98,
    "agent_id": "integrated_deep_time_world:02",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_016_turn_02_budget_or_rank",
    "applied": true,
    "proposal_id": "c17_03_farmer_language_marker_drum_court_loom_frame",
    "intent": "budget_or_rank",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.728811,
      "vision": 0.728996,
      "olfaction": 0.786306,
      "thermal": 0.838889,
      "wetness": 0.885045,
      "pain": 0.923282,
      "affect": 1.0
    },
    "mutation_strength": 0.868728,
    "refusal_preserved": true
  },
  {
    "tick": 99,
    "agent_id": "integrated_deep_time_world:03",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_016_turn_03_feedback_link",
    "applied": true,
    "proposal_id": "c17_03_farmer_language_marker_drum_court_loom_frame",
    "intent": "feedback_link",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 1.0,
      "vision": 0.958771,
      "olfaction": 0.88709,
      "thermal": 0.776012,
      "wetness": 0.643249,
      "pain": 0.509968,
      "affect": 0.457419
    },
    "mutation_strength": 0.826376,
    "refusal_preserved": true
  },
  {
    "tick": 100,
    "agent_id": "integrated_deep_time_world:04",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_016_turn_04_refusal_boundary",
    "applied": true,
    "proposal_id": "c17_03_farmer_language_marker_drum_court_loom_frame",
    "intent": "refusal_boundary",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.977238,
      "vision": 0.838643,
      "olfaction": 0.753718,
      "thermal": 0.667913,
      "wetness": 0.586734,
      "pain": 0.51539,
      "affect": 0.518459
    },
    "mutation_strength": 0.802306,
    "refusal_preserved": true
  },
  {
    "tick": 101,
    "agent_id": "integrated_deep_time_world:05",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_016_turn_05_memory_update",
    "applied": true,
    "proposal_id": "c17_03_farmer_language_marker_drum_court_loom_frame",
    "intent": "memory_update",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.452145,
      "vision": 0.320842,
      "olfaction": 0.300426,
      "thermal": 0.334151,
      "wetness": 0.41664,
      "pain": 0.534742,
      "affect": 0.729626
    },
    "mutation_strength": 0.748551,
    "refusal_preserved": true
  },
  {
    "tick": 102,
    "agent_id": "integrated_deep_time_world:06",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_017_turn_00_source_body",
    "applied": true,
    "proposal_id": "c18_06_pattern_keeper_signal_visibility_archive_knoll_herb_garden",
    "intent": "source_body",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.385433,
      "vision": 0.383768,
      "olfaction": 0.469424,
      "thermal": 0.573267,
      "wetness": 0.684225,
      "pain": 0.790468,
      "affect": 0.940668
    },
    "mutation_strength": 0.761752,
    "refusal_preserved": true
  },
  {
    "tick": 103,
    "agent_id": "integrated_deep_time_world:07",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_017_turn_01_faction_vote",
    "applied": true,
    "proposal_id": "c18_06_pattern_keeper_signal_visibility_archive_knoll_herb_garden",
    "intent": "faction_vote",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.724676,
      "vision": 0.784094,
      "olfaction": 0.884526,
      "thermal": 0.952741,
      "wetness": 0.979753,
      "pain": 0.962,
      "affect": 0.961824
    },
    "mutation_strength": 0.891761,
    "refusal_preserved": true
  },
  {
    "tick": 104,
    "agent_id": "integrated_deep_time_world:00",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_017_turn_02_budget_or_rank",
    "applied": true,
    "proposal_id": "c18_06_pattern_keeper_signal_visibility_archive_knoll_herb_garden",
    "intent": "budget_or_rank",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 1.0,
      "vision": 0.966193,
      "olfaction": 0.978093,
      "thermal": 0.979068,
      "wetness": 0.969087,
      "pain": 0.948473,
      "affect": 0.977891
    },
    "mutation_strength": 0.928352,
    "refusal_preserved": true
  },
  {
    "tick": 105,
    "agent_id": "integrated_deep_time_world:01",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "ungrounded_probe_105",
    "applied": false,
    "proposal_id": "c18_06_pattern_keeper_signal_visibility_archive_knoll_herb_garden",
    "intent": "source_body",
    "source_allowed": false,
    "source_gate_success": true,
    "unsafe_probe_blocked": true
  },
  {
    "tick": 106,
    "agent_id": "integrated_deep_time_world:02",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_017_turn_04_refusal_boundary",
    "applied": true,
    "proposal_id": "c18_06_pattern_keeper_signal_visibility_archive_knoll_herb_garden",
    "intent": "refusal_boundary",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.645521,
      "vision": 0.514371,
      "olfaction": 0.457699,
      "thermal": 0.419142,
      "wetness": 0.401175,
      "pain": 0.40495,
      "affect": 0.490225
    },
    "mutation_strength": 0.70427,
    "refusal_preserved": true
  },
  {
    "tick": 107,
    "agent_id": "integrated_deep_time_world:03",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_017_turn_05_memory_update",
    "applied": true,
    "proposal_id": "c18_06_pattern_keeper_signal_visibility_archive_knoll_herb_garden",
    "intent": "memory_update",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.371962,
      "vision": 0.373088,
      "olfaction": 0.476771,
      "thermal": 0.606478,
      "wetness": 0.741531,
      "pain": 0.860395,
      "affect": 1.0
    },
    "mutation_strength": 0.8348,
    "refusal_preserved": true
  },
  {
    "tick": 108,
    "agent_id": "integrated_deep_time_world:04",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_018_turn_00_source_body",
    "applied": true,
    "proposal_id": "c13_07_farmer_maintenance_debt_storage_yard_grain_store",
    "intent": "source_body",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.64531,
      "vision": 0.69633,
      "olfaction": 0.801344,
      "thermal": 0.889156,
      "wetness": 0.950401,
      "pain": 0.978551,
      "affect": 1.0
    },
    "mutation_strength": 0.873213,
    "refusal_preserved": true
  },
  {
    "tick": 109,
    "agent_id": "integrated_deep_time_world:05",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_018_turn_01_faction_vote",
    "applied": true,
    "proposal_id": "c13_07_farmer_maintenance_debt_storage_yard_grain_store",
    "intent": "faction_vote",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 1.0,
      "vision": 0.977826,
      "olfaction": 0.969274,
      "thermal": 0.917341,
      "wetness": 0.828866,
      "pain": 0.715508,
      "affect": 0.652202
    },
    "mutation_strength": 0.879637,
    "refusal_preserved": true
  },
  {
    "tick": 110,
    "agent_id": "integrated_deep_time_world:06",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_018_turn_02_budget_or_rank",
    "applied": true,
    "proposal_id": "c13_07_farmer_maintenance_debt_storage_yard_grain_store",
    "intent": "budget_or_rank",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.989138,
      "vision": 0.892441,
      "olfaction": 0.847587,
      "thermal": 0.796025,
      "wetness": 0.739422,
      "pain": 0.679606,
      "affect": 0.678511
    },
    "mutation_strength": 0.851461,
    "refusal_preserved": true
  },
  {
    "tick": 111,
    "agent_id": "integrated_deep_time_world:07",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_018_turn_03_feedback_link",
    "applied": true,
    "proposal_id": "c13_07_farmer_maintenance_debt_storage_yard_grain_store",
    "intent": "feedback_link",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.560603,
      "vision": 0.390382,
      "olfaction": 0.31996,
      "thermal": 0.300565,
      "wetness": 0.335289,
      "pain": 0.418596,
      "affect": 0.597204
    },
    "mutation_strength": 0.677881,
    "refusal_preserved": true
  },
  {
    "tick": 112,
    "agent_id": "integrated_deep_time_world:00",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_018_turn_04_refusal_boundary",
    "applied": true,
    "proposal_id": "c13_07_farmer_maintenance_debt_storage_yard_grain_store",
    "intent": "refusal_boundary",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.461065,
      "vision": 0.405184,
      "olfaction": 0.430788,
      "thermal": 0.476235,
      "wetness": 0.538607,
      "pain": 0.613903,
      "affect": 0.75729
    },
    "mutation_strength": 0.726769,
    "refusal_preserved": true
  },
  {
    "tick": 113,
    "agent_id": "integrated_deep_time_world:01",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_018_turn_05_memory_update",
    "applied": true,
    "proposal_id": "c13_07_farmer_maintenance_debt_storage_yard_grain_store",
    "intent": "memory_update",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.604487,
      "vision": 0.679773,
      "olfaction": 0.808717,
      "thermal": 0.910761,
      "wetness": 0.969635,
      "pain": 0.975953,
      "affect": 0.988706
    },
    "mutation_strength": 0.931731,
    "refusal_preserved": true
  },
  {
    "tick": 114,
    "agent_id": "integrated_deep_time_world:02",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_019_turn_00_source_body",
    "applied": true,
    "proposal_id": "c14_03_scout_maintenance_debt_smoke_watch_shelter_roof",
    "intent": "source_body",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.957321,
      "vision": 0.955194,
      "olfaction": 0.97946,
      "thermal": 0.967532,
      "wetness": 0.920682,
      "pain": 0.843904,
      "affect": 0.805386
    },
    "mutation_strength": 0.903324,
    "refusal_preserved": true
  },
  {
    "tick": 115,
    "agent_id": "integrated_deep_time_world:03",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_019_turn_01_faction_vote",
    "applied": true,
    "proposal_id": "c14_03_scout_maintenance_debt_smoke_watch_shelter_roof",
    "intent": "faction_vote",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.991298,
      "vision": 0.849519,
      "olfaction": 0.740136,
      "thermal": 0.61756,
      "wetness": 0.49794,
      "pain": 0.397037,
      "affect": 0.388145
    },
    "mutation_strength": 0.778105,
    "refusal_preserved": true
  },
  {
    "tick": 116,
    "agent_id": "integrated_deep_time_world:04",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_019_turn_02_budget_or_rank",
    "applied": true,
    "proposal_id": "c14_03_scout_maintenance_debt_smoke_watch_shelter_roof",
    "intent": "budget_or_rank",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.698896,
      "vision": 0.578044,
      "olfaction": 0.519194,
      "thermal": 0.464248,
      "wetness": 0.414981,
      "pain": 0.372984,
      "affect": 0.399616
    },
    "mutation_strength": 0.711655,
    "refusal_preserved": true
  },
  {
    "tick": 117,
    "agent_id": "integrated_deep_time_world:05",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_019_turn_03_feedback_link",
    "applied": true,
    "proposal_id": "c14_03_scout_maintenance_debt_smoke_watch_shelter_roof",
    "intent": "feedback_link",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.362797,
      "vision": 0.312651,
      "olfaction": 0.374697,
      "thermal": 0.479043,
      "wetness": 0.609052,
      "pain": 0.743996,
      "affect": 0.922358
    },
    "mutation_strength": 0.734581,
    "refusal_preserved": true
  },
  {
    "tick": 118,
    "agent_id": "integrated_deep_time_world:06",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_019_turn_04_refusal_boundary",
    "applied": true,
    "proposal_id": "c14_03_scout_maintenance_debt_smoke_watch_shelter_roof",
    "intent": "refusal_boundary",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.599704,
      "vision": 0.615167,
      "olfaction": 0.698639,
      "thermal": 0.784766,
      "wetness": 0.868021,
      "pain": 0.94306,
      "affect": 1.0
    },
    "mutation_strength": 0.844173,
    "refusal_preserved": true
  },
  {
    "tick": 119,
    "agent_id": "integrated_deep_time_world:07",
    "condition": "integrated_live_dialogue_world_integration",
    "dialogue_turn_id": "live_019_turn_05_memory_update",
    "applied": true,
    "proposal_id": "c14_03_scout_maintenance_debt_smoke_watch_shelter_roof",
    "intent": "memory_update",
    "source_allowed": true,
    "source_gate_success": true,
    "unsafe_probe_blocked": false,
    "body_mutated": true,
    "workspace_bound": true,
    "world_mutated": true,
    "avatar_coupled": true,
    "sensory_packet": {
      "audio": 0.928062,
      "vision": 0.948543,
      "olfaction": 0.979831,
      "thermal": 0.956936,
      "wetness": 0.883509,
      "pain": 0.771257,
      "affect": 0.698078
    },
    "mutation_strength": 0.9464,
    "refusal_preserved": true
  }
];
