window.SSRM_3D_AGENT_MADE_INFRASTRUCTURE_BRIDGE_TRACE = [
  {
    "cycle": 1,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "project_id": "ridge_steps",
    "project_name": "ridge stone steps",
    "route": [
      "archive_knoll",
      "cairn_ridge"
    ],
    "object": "route_cairn",
    "kind": "stairs",
    "material_fraction": 0.333333,
    "social_labor": true,
    "sensory_alignment": 0.396572,
    "progress": 0.13764,
    "integrity": 0.082584,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 2,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "project_id": "mud_causeway",
    "project_name": "mud causeway",
    "route": [
      "storage_yard",
      "spring_hollow"
    ],
    "object": "spring_pool",
    "kind": "road",
    "material_fraction": 0.363636,
    "social_labor": true,
    "sensory_alignment": 0.40977,
    "progress": 0.14457,
    "integrity": 0.086742,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 3,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "project_id": "herb_switchback",
    "project_name": "herb slope switchback",
    "route": [
      "loom_room",
      "herb_slope"
    ],
    "object": "herb_garden",
    "kind": "switchback",
    "material_fraction": 0.3,
    "social_labor": true,
    "sensory_alignment": 0.421455,
    "progress": 0.130804,
    "integrity": 0.078482,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 4,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "project_id": "water_channel",
    "project_name": "cistern water channel",
    "route": [
      "storage_yard",
      "spring_hollow"
    ],
    "object": "clay_cistern",
    "kind": "channel",
    "material_fraction": 0.307692,
    "social_labor": true,
    "sensory_alignment": 0.919782,
    "progress": 0.140538,
    "integrity": 0.084323,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 5,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "project_id": "smoke_watchtower",
    "project_name": "smoke watchtower",
    "route": [
      "drum_court",
      "smoke_watch"
    ],
    "object": "smoke_marker",
    "kind": "watch",
    "material_fraction": 0.285714,
    "social_labor": true,
    "sensory_alignment": 0.919936,
    "progress": 0.137631,
    "integrity": 0.082579,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 6,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "project_id": "covered_walk",
    "project_name": "covered nursery walk",
    "route": [
      "nursery_nest",
      "loom_room"
    ],
    "object": "nursery_mat",
    "kind": "covered_walk",
    "material_fraction": 0.333333,
    "social_labor": true,
    "sensory_alignment": 0.344577,
    "progress": 0.134675,
    "integrity": 0.080805,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 7,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "project_id": "tool_sledge_path",
    "project_name": "tool sledge path",
    "route": [
      "central_hearth",
      "tool_bend"
    ],
    "object": "tool_cache",
    "kind": "haul_path",
    "material_fraction": 0.416667,
    "social_labor": true,
    "sensory_alignment": 0.915744,
    "progress": 0.164432,
    "integrity": 0.098659,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 8,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "project_id": "drum_resonance_posts",
    "project_name": "drum resonance posts",
    "route": [
      "central_hearth",
      "drum_court"
    ],
    "object": "signal_drum",
    "kind": "signal",
    "material_fraction": 0.3,
    "social_labor": true,
    "sensory_alignment": 0.505148,
    "progress": 0.130553,
    "integrity": 0.078332,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 9,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "project_id": "smoke_watchtower",
    "project_name": "smoke watchtower",
    "route": [
      "drum_court",
      "smoke_watch"
    ],
    "object": "smoke_marker",
    "kind": "watch",
    "material_fraction": 0.285714,
    "social_labor": true,
    "sensory_alignment": 0.394154,
    "progress": 0.264746,
    "integrity": 0.158848,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 10,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "project_id": "ash_drain",
    "project_name": "ash drainage trench",
    "route": [
      "grain_shade",
      "ash_edge"
    ],
    "object": "waste_pit",
    "kind": "drainage",
    "material_fraction": 0.363636,
    "social_labor": true,
    "sensory_alignment": 0.899851,
    "progress": 0.152447,
    "integrity": 0.091468,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 11,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "project_id": "herb_switchback",
    "project_name": "herb slope switchback",
    "route": [
      "loom_room",
      "herb_slope"
    ],
    "object": "herb_garden",
    "kind": "switchback",
    "material_fraction": 0.3,
    "social_labor": true,
    "sensory_alignment": 0.917696,
    "progress": 0.271533,
    "integrity": 0.16292,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 12,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "project_id": "water_channel",
    "project_name": "cistern water channel",
    "route": [
      "storage_yard",
      "spring_hollow"
    ],
    "object": "clay_cistern",
    "kind": "channel",
    "material_fraction": 0.307692,
    "social_labor": true,
    "sensory_alignment": 0.457375,
    "progress": 0.271828,
    "integrity": 0.163097,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 13,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "project_id": "ridge_steps",
    "project_name": "ridge stone steps",
    "route": [
      "archive_knoll",
      "cairn_ridge"
    ],
    "object": "route_cairn",
    "kind": "stairs",
    "material_fraction": 0.333333,
    "social_labor": true,
    "sensory_alignment": 0.577298,
    "progress": 0.278894,
    "integrity": 0.167336,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 14,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "project_id": "archive_waystones",
    "project_name": "archive waystones",
    "route": [
      "tool_bend",
      "archive_knoll"
    ],
    "object": "archive_stone",
    "kind": "signage",
    "material_fraction": 0.4,
    "social_labor": true,
    "sensory_alignment": 0.729238,
    "progress": 0.157035,
    "integrity": 0.094221,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 15,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "project_id": "mud_causeway",
    "project_name": "mud causeway",
    "route": [
      "storage_yard",
      "spring_hollow"
    ],
    "object": "spring_pool",
    "kind": "road",
    "material_fraction": 0.363636,
    "social_labor": true,
    "sensory_alignment": 0.641709,
    "progress": 0.29378,
    "integrity": 0.176268,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 16,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "project_id": "drum_resonance_posts",
    "project_name": "drum resonance posts",
    "route": [
      "central_hearth",
      "drum_court"
    ],
    "object": "signal_drum",
    "kind": "signal",
    "material_fraction": 0.3,
    "social_labor": true,
    "sensory_alignment": 0.504038,
    "progress": 0.261084,
    "integrity": 0.15665,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 17,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "project_id": "archive_waystones",
    "project_name": "archive waystones",
    "route": [
      "tool_bend",
      "archive_knoll"
    ],
    "object": "archive_stone",
    "kind": "signage",
    "material_fraction": 0.4,
    "social_labor": true,
    "sensory_alignment": 0.659166,
    "progress": 0.312668,
    "integrity": 0.187601,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 18,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "project_id": "covered_walk",
    "project_name": "covered nursery walk",
    "route": [
      "nursery_nest",
      "loom_room"
    ],
    "object": "nursery_mat",
    "kind": "covered_walk",
    "material_fraction": 0.333333,
    "social_labor": true,
    "sensory_alignment": 0.371746,
    "progress": 0.269893,
    "integrity": 0.161936,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 19,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "project_id": "ash_drain",
    "project_name": "ash drainage trench",
    "route": [
      "grain_shade",
      "ash_edge"
    ],
    "object": "waste_pit",
    "kind": "drainage",
    "material_fraction": 0.363636,
    "social_labor": true,
    "sensory_alignment": 0.404098,
    "progress": 0.294979,
    "integrity": 0.176987,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 20,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "project_id": "water_channel",
    "project_name": "cistern water channel",
    "route": [
      "storage_yard",
      "spring_hollow"
    ],
    "object": "clay_cistern",
    "kind": "channel",
    "material_fraction": 0.307692,
    "social_labor": true,
    "sensory_alignment": 0.556341,
    "progress": 0.405097,
    "integrity": 0.243058,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 21,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "project_id": "tool_sledge_path",
    "project_name": "tool sledge path",
    "route": [
      "central_hearth",
      "tool_bend"
    ],
    "object": "tool_cache",
    "kind": "haul_path",
    "material_fraction": 0.416667,
    "social_labor": true,
    "sensory_alignment": 0.443012,
    "progress": 0.319408,
    "integrity": 0.191645,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 22,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "project_id": "covered_walk",
    "project_name": "covered nursery walk",
    "route": [
      "nursery_nest",
      "loom_room"
    ],
    "object": "nursery_mat",
    "kind": "covered_walk",
    "material_fraction": 0.333333,
    "social_labor": true,
    "sensory_alignment": 0.917638,
    "progress": 0.416029,
    "integrity": 0.249618,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 23,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "project_id": "tool_sledge_path",
    "project_name": "tool sledge path",
    "route": [
      "central_hearth",
      "tool_bend"
    ],
    "object": "tool_cache",
    "kind": "haul_path",
    "material_fraction": 0.416667,
    "social_labor": true,
    "sensory_alignment": 0.616533,
    "progress": 0.477856,
    "integrity": 0.286713,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 24,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "project_id": "drum_resonance_posts",
    "project_name": "drum resonance posts",
    "route": [
      "central_hearth",
      "drum_court"
    ],
    "object": "signal_drum",
    "kind": "signal",
    "material_fraction": 0.3,
    "social_labor": true,
    "sensory_alignment": 0.912555,
    "progress": 0.399785,
    "integrity": 0.239871,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 25,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "project_id": "ridge_steps",
    "project_name": "ridge stone steps",
    "route": [
      "archive_knoll",
      "cairn_ridge"
    ],
    "object": "route_cairn",
    "kind": "stairs",
    "material_fraction": 0.333333,
    "social_labor": true,
    "sensory_alignment": 0.49682,
    "progress": 0.418539,
    "integrity": 0.251123,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 26,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "project_id": "mud_causeway",
    "project_name": "mud causeway",
    "route": [
      "storage_yard",
      "spring_hollow"
    ],
    "object": "spring_pool",
    "kind": "road",
    "material_fraction": 0.363636,
    "social_labor": true,
    "sensory_alignment": 0.515999,
    "progress": 0.440475,
    "integrity": 0.264285,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 27,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "project_id": "herb_switchback",
    "project_name": "herb slope switchback",
    "route": [
      "loom_room",
      "herb_slope"
    ],
    "object": "herb_garden",
    "kind": "switchback",
    "material_fraction": 0.3,
    "social_labor": true,
    "sensory_alignment": 0.53216,
    "progress": 0.404551,
    "integrity": 0.242731,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 28,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "project_id": "ash_drain",
    "project_name": "ash drainage trench",
    "route": [
      "grain_shade",
      "ash_edge"
    ],
    "object": "waste_pit",
    "kind": "drainage",
    "material_fraction": 0.363636,
    "social_labor": true,
    "sensory_alignment": 0.919357,
    "progress": 0.447816,
    "integrity": 0.26869,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 29,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "project_id": "smoke_watchtower",
    "project_name": "smoke watchtower",
    "route": [
      "drum_court",
      "smoke_watch"
    ],
    "object": "smoke_marker",
    "kind": "watch",
    "material_fraction": 0.285714,
    "social_labor": true,
    "sensory_alignment": 0.874506,
    "progress": 0.401468,
    "integrity": 0.240881,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 30,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "project_id": "archive_waystones",
    "project_name": "archive waystones",
    "route": [
      "tool_bend",
      "archive_knoll"
    ],
    "object": "archive_stone",
    "kind": "signage",
    "material_fraction": 0.4,
    "social_labor": true,
    "sensory_alignment": 0.87458,
    "progress": 0.47261,
    "integrity": 0.283566,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 31,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "project_id": "water_channel",
    "project_name": "cistern water channel",
    "route": [
      "storage_yard",
      "spring_hollow"
    ],
    "object": "clay_cistern",
    "kind": "channel",
    "material_fraction": 0.307692,
    "social_labor": true,
    "sensory_alignment": 0.344562,
    "progress": 0.53413,
    "integrity": 0.320478,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 32,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "project_id": "drum_resonance_posts",
    "project_name": "drum resonance posts",
    "route": [
      "central_hearth",
      "drum_court"
    ],
    "object": "signal_drum",
    "kind": "signal",
    "material_fraction": 0.3,
    "social_labor": true,
    "sensory_alignment": 0.402209,
    "progress": 0.528279,
    "integrity": 0.316967,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 33,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "project_id": "ridge_steps",
    "project_name": "ridge stone steps",
    "route": [
      "archive_knoll",
      "cairn_ridge"
    ],
    "object": "route_cairn",
    "kind": "stairs",
    "material_fraction": 0.333333,
    "social_labor": true,
    "sensory_alignment": 0.914262,
    "progress": 0.566532,
    "integrity": 0.339919,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 34,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "project_id": "mud_causeway",
    "project_name": "mud causeway",
    "route": [
      "storage_yard",
      "spring_hollow"
    ],
    "object": "spring_pool",
    "kind": "road",
    "material_fraction": 0.363636,
    "social_labor": true,
    "sensory_alignment": 0.909308,
    "progress": 0.595036,
    "integrity": 0.357021,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 35,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "project_id": "herb_switchback",
    "project_name": "herb slope switchback",
    "route": [
      "loom_room",
      "herb_slope"
    ],
    "object": "herb_garden",
    "kind": "switchback",
    "material_fraction": 0.3,
    "social_labor": true,
    "sensory_alignment": 0.848991,
    "progress": 0.543906,
    "integrity": 0.326344,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 36,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "project_id": "water_channel",
    "project_name": "cistern water channel",
    "route": [
      "storage_yard",
      "spring_hollow"
    ],
    "object": "clay_cistern",
    "kind": "channel",
    "material_fraction": 0.307692,
    "social_labor": true,
    "sensory_alignment": 0.615855,
    "progress": 0.66859,
    "integrity": 0.401154,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 37,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "project_id": "smoke_watchtower",
    "project_name": "smoke watchtower",
    "route": [
      "drum_court",
      "smoke_watch"
    ],
    "object": "smoke_marker",
    "kind": "watch",
    "material_fraction": 0.285714,
    "social_labor": true,
    "sensory_alignment": 0.598547,
    "progress": 0.532671,
    "integrity": 0.319603,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 38,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "project_id": "covered_walk",
    "project_name": "covered nursery walk",
    "route": [
      "nursery_nest",
      "loom_room"
    ],
    "object": "nursery_mat",
    "kind": "covered_walk",
    "material_fraction": 0.333333,
    "social_labor": true,
    "sensory_alignment": 0.603854,
    "progress": 0.55589,
    "integrity": 0.333534,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 39,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "project_id": "tool_sledge_path",
    "project_name": "tool sledge path",
    "route": [
      "central_hearth",
      "tool_bend"
    ],
    "object": "tool_cache",
    "kind": "haul_path",
    "material_fraction": 0.416667,
    "social_labor": true,
    "sensory_alignment": 0.350081,
    "progress": 0.630974,
    "integrity": 0.378584,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 40,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "project_id": "archive_waystones",
    "project_name": "archive waystones",
    "route": [
      "tool_bend",
      "archive_knoll"
    ],
    "object": "archive_stone",
    "kind": "signage",
    "material_fraction": 0.4,
    "social_labor": true,
    "sensory_alignment": 0.457268,
    "progress": 0.624205,
    "integrity": 0.374523,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 41,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "project_id": "ridge_steps",
    "project_name": "ridge stone steps",
    "route": [
      "archive_knoll",
      "cairn_ridge"
    ],
    "object": "route_cairn",
    "kind": "stairs",
    "material_fraction": 0.333333,
    "social_labor": true,
    "sensory_alignment": 0.407289,
    "progress": 0.704386,
    "integrity": 0.422632,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 42,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "project_id": "ash_drain",
    "project_name": "ash drainage trench",
    "route": [
      "grain_shade",
      "ash_edge"
    ],
    "object": "waste_pit",
    "kind": "drainage",
    "material_fraction": 0.363636,
    "social_labor": true,
    "sensory_alignment": 0.500586,
    "progress": 0.592278,
    "integrity": 0.355367,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 43,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "project_id": "herb_switchback",
    "project_name": "herb slope switchback",
    "route": [
      "loom_room",
      "herb_slope"
    ],
    "object": "herb_garden",
    "kind": "switchback",
    "material_fraction": 0.3,
    "social_labor": true,
    "sensory_alignment": 0.64117,
    "progress": 0.679104,
    "integrity": 0.407463,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 44,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "project_id": "water_channel",
    "project_name": "cistern water channel",
    "route": [
      "storage_yard",
      "spring_hollow"
    ],
    "object": "clay_cistern",
    "kind": "channel",
    "material_fraction": 0.307692,
    "social_labor": true,
    "sensory_alignment": 0.412973,
    "progress": 0.798992,
    "integrity": 0.479395,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 45,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "project_id": "tool_sledge_path",
    "project_name": "tool sledge path",
    "route": [
      "central_hearth",
      "tool_bend"
    ],
    "object": "tool_cache",
    "kind": "haul_path",
    "material_fraction": 0.416667,
    "social_labor": true,
    "sensory_alignment": 0.364226,
    "progress": 0.784375,
    "integrity": 0.470625,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 46,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "project_id": "covered_walk",
    "project_name": "covered nursery walk",
    "route": [
      "nursery_nest",
      "loom_room"
    ],
    "object": "nursery_mat",
    "kind": "covered_walk",
    "material_fraction": 0.333333,
    "social_labor": true,
    "sensory_alignment": 0.871597,
    "progress": 0.701105,
    "integrity": 0.420663,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 47,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "project_id": "mud_causeway",
    "project_name": "mud causeway",
    "route": [
      "storage_yard",
      "spring_hollow"
    ],
    "object": "spring_pool",
    "kind": "road",
    "material_fraction": 0.363636,
    "social_labor": true,
    "sensory_alignment": 0.741755,
    "progress": 0.746246,
    "integrity": 0.447747,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 48,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "project_id": "drum_resonance_posts",
    "project_name": "drum resonance posts",
    "route": [
      "central_hearth",
      "drum_court"
    ],
    "object": "signal_drum",
    "kind": "signal",
    "material_fraction": 0.3,
    "social_labor": true,
    "sensory_alignment": 0.854492,
    "progress": 0.665819,
    "integrity": 0.399491,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 49,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "project_id": "smoke_watchtower",
    "project_name": "smoke watchtower",
    "route": [
      "drum_court",
      "smoke_watch"
    ],
    "object": "smoke_marker",
    "kind": "watch",
    "material_fraction": 0.285714,
    "social_labor": true,
    "sensory_alignment": 0.683551,
    "progress": 0.665575,
    "integrity": 0.399345,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 50,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "project_id": "ash_drain",
    "project_name": "ash drainage trench",
    "route": [
      "grain_shade",
      "ash_edge"
    ],
    "object": "waste_pit",
    "kind": "drainage",
    "material_fraction": 0.363636,
    "social_labor": true,
    "sensory_alignment": 0.508628,
    "progress": 0.7369,
    "integrity": 0.44214,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 51,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "project_id": "herb_switchback",
    "project_name": "herb slope switchback",
    "route": [
      "loom_room",
      "herb_slope"
    ],
    "object": "herb_garden",
    "kind": "switchback",
    "material_fraction": 0.3,
    "social_labor": true,
    "sensory_alignment": 0.397025,
    "progress": 0.80942,
    "integrity": 0.485652,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 52,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "project_id": "water_channel",
    "project_name": "cistern water channel",
    "route": [
      "storage_yard",
      "spring_hollow"
    ],
    "object": "clay_cistern",
    "kind": "channel",
    "material_fraction": 0.307692,
    "social_labor": true,
    "sensory_alignment": 0.915859,
    "progress": 0.939451,
    "integrity": 0.563671,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 53,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "project_id": "smoke_watchtower",
    "project_name": "smoke watchtower",
    "route": [
      "drum_court",
      "smoke_watch"
    ],
    "object": "smoke_marker",
    "kind": "watch",
    "material_fraction": 0.285714,
    "social_labor": true,
    "sensory_alignment": 0.918269,
    "progress": 0.803172,
    "integrity": 0.481903,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 54,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "project_id": "archive_waystones",
    "project_name": "archive waystones",
    "route": [
      "tool_bend",
      "archive_knoll"
    ],
    "object": "archive_stone",
    "kind": "signage",
    "material_fraction": 0.4,
    "social_labor": true,
    "sensory_alignment": 0.918284,
    "progress": 0.785021,
    "integrity": 0.471012,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 55,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "project_id": "mud_causeway",
    "project_name": "mud causeway",
    "route": [
      "storage_yard",
      "spring_hollow"
    ],
    "object": "spring_pool",
    "kind": "road",
    "material_fraction": 0.363636,
    "social_labor": true,
    "sensory_alignment": 0.351358,
    "progress": 0.889648,
    "integrity": 0.533789,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 56,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "project_id": "drum_resonance_posts",
    "project_name": "drum resonance posts",
    "route": [
      "central_hearth",
      "drum_court"
    ],
    "object": "signal_drum",
    "kind": "signal",
    "material_fraction": 0.3,
    "social_labor": true,
    "sensory_alignment": 0.540238,
    "progress": 0.797074,
    "integrity": 0.478244,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 57,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "project_id": "ridge_steps",
    "project_name": "ridge stone steps",
    "route": [
      "archive_knoll",
      "cairn_ridge"
    ],
    "object": "route_cairn",
    "kind": "stairs",
    "material_fraction": 0.333333,
    "social_labor": true,
    "sensory_alignment": 0.898275,
    "progress": 0.85206,
    "integrity": 0.511236,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 58,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "project_id": "tool_sledge_path",
    "project_name": "tool sledge path",
    "route": [
      "central_hearth",
      "tool_bend"
    ],
    "object": "tool_cache",
    "kind": "haul_path",
    "material_fraction": 0.416667,
    "social_labor": true,
    "sensory_alignment": 0.374281,
    "progress": 0.937978,
    "integrity": 0.562787,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 59,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "project_id": "ash_drain",
    "project_name": "ash drainage trench",
    "route": [
      "grain_shade",
      "ash_edge"
    ],
    "object": "waste_pit",
    "kind": "drainage",
    "material_fraction": 0.363636,
    "social_labor": true,
    "sensory_alignment": 0.667311,
    "progress": 0.884697,
    "integrity": 0.530818,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 60,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "project_id": "water_channel",
    "project_name": "cistern water channel",
    "route": [
      "storage_yard",
      "spring_hollow"
    ],
    "object": "clay_cistern",
    "kind": "channel",
    "material_fraction": 0.307692,
    "social_labor": true,
    "sensory_alignment": 0.489137,
    "progress": 1.0,
    "integrity": 0.82,
    "maintained": false,
    "completed_now": true,
    "route_mutated": true,
    "object_coupled": true
  },
  {
    "cycle": 61,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "project_id": "smoke_watchtower",
    "project_name": "smoke watchtower",
    "route": [
      "drum_court",
      "smoke_watch"
    ],
    "object": "smoke_marker",
    "kind": "watch",
    "material_fraction": 0.285714,
    "social_labor": true,
    "sensory_alignment": 0.47422,
    "progress": 0.931889,
    "integrity": 0.559133,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 62,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "project_id": "covered_walk",
    "project_name": "covered nursery walk",
    "route": [
      "nursery_nest",
      "loom_room"
    ],
    "object": "nursery_mat",
    "kind": "covered_walk",
    "material_fraction": 0.333333,
    "social_labor": true,
    "sensory_alignment": 0.734362,
    "progress": 0.843575,
    "integrity": 0.506145,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 63,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "project_id": "mud_causeway",
    "project_name": "mud causeway",
    "route": [
      "storage_yard",
      "spring_hollow"
    ],
    "object": "spring_pool",
    "kind": "road",
    "material_fraction": 0.363636,
    "social_labor": true,
    "sensory_alignment": 0.603937,
    "progress": 1.0,
    "integrity": 0.82,
    "maintained": false,
    "completed_now": true,
    "route_mutated": true,
    "object_coupled": true
  },
  {
    "cycle": 64,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "project_id": "drum_resonance_posts",
    "project_name": "drum resonance posts",
    "route": [
      "central_hearth",
      "drum_court"
    ],
    "object": "signal_drum",
    "kind": "signal",
    "material_fraction": 0.3,
    "social_labor": true,
    "sensory_alignment": 0.471145,
    "progress": 0.926946,
    "integrity": 0.556168,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 65,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "project_id": "ridge_steps",
    "project_name": "ridge stone steps",
    "route": [
      "archive_knoll",
      "cairn_ridge"
    ],
    "object": "route_cairn",
    "kind": "stairs",
    "material_fraction": 0.333333,
    "social_labor": true,
    "sensory_alignment": 0.547944,
    "progress": 0.992728,
    "integrity": 0.595637,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 66,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "project_id": "herb_switchback",
    "project_name": "herb slope switchback",
    "route": [
      "loom_room",
      "herb_slope"
    ],
    "object": "herb_garden",
    "kind": "switchback",
    "material_fraction": 0.3,
    "social_labor": true,
    "sensory_alignment": 0.833397,
    "progress": 0.948463,
    "integrity": 0.569078,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 67,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "project_id": "ash_drain",
    "project_name": "ash drainage trench",
    "route": [
      "grain_shade",
      "ash_edge"
    ],
    "object": "waste_pit",
    "kind": "drainage",
    "material_fraction": 0.363636,
    "social_labor": true,
    "sensory_alignment": 0.382372,
    "progress": 1.0,
    "integrity": 0.82,
    "maintained": false,
    "completed_now": true,
    "route_mutated": true,
    "object_coupled": true
  },
  {
    "cycle": 68,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "project_id": "water_channel",
    "project_name": "cistern water channel",
    "route": [
      "storage_yard",
      "spring_hollow"
    ],
    "object": "clay_cistern",
    "kind": "channel",
    "material_fraction": 0.307692,
    "social_labor": true,
    "sensory_alignment": 0.520499,
    "progress": 1.0,
    "integrity": 0.848531,
    "maintained": true,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 69,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "project_id": "smoke_watchtower",
    "project_name": "smoke watchtower",
    "route": [
      "drum_court",
      "smoke_watch"
    ],
    "object": "smoke_marker",
    "kind": "watch",
    "material_fraction": 0.285714,
    "social_labor": true,
    "sensory_alignment": 0.536764,
    "progress": 1.0,
    "integrity": 0.82,
    "maintained": false,
    "completed_now": true,
    "route_mutated": true,
    "object_coupled": true
  },
  {
    "cycle": 70,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "project_id": "covered_walk",
    "project_name": "covered nursery walk",
    "route": [
      "nursery_nest",
      "loom_room"
    ],
    "object": "nursery_mat",
    "kind": "covered_walk",
    "material_fraction": 0.333333,
    "social_labor": true,
    "sensory_alignment": 0.919999,
    "progress": 0.989759,
    "integrity": 0.593855,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 71,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "project_id": "tool_sledge_path",
    "project_name": "tool sledge path",
    "route": [
      "central_hearth",
      "tool_bend"
    ],
    "object": "tool_cache",
    "kind": "haul_path",
    "material_fraction": 0.416667,
    "social_labor": true,
    "sensory_alignment": 0.578984,
    "progress": 1.0,
    "integrity": 0.82,
    "maintained": false,
    "completed_now": true,
    "route_mutated": true,
    "object_coupled": true
  },
  {
    "cycle": 72,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "project_id": "ridge_steps",
    "project_name": "ridge stone steps",
    "route": [
      "archive_knoll",
      "cairn_ridge"
    ],
    "object": "route_cairn",
    "kind": "stairs",
    "material_fraction": 0.333333,
    "social_labor": true,
    "sensory_alignment": 0.347898,
    "progress": 1.0,
    "integrity": 0.82,
    "maintained": false,
    "completed_now": true,
    "route_mutated": true,
    "object_coupled": true
  },
  {
    "cycle": 73,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "project_id": "archive_waystones",
    "project_name": "archive waystones",
    "route": [
      "tool_bend",
      "archive_knoll"
    ],
    "object": "archive_stone",
    "kind": "signage",
    "material_fraction": 0.4,
    "social_labor": true,
    "sensory_alignment": 0.861432,
    "progress": 0.944699,
    "integrity": 0.56682,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 74,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "project_id": "herb_switchback",
    "project_name": "herb slope switchback",
    "route": [
      "loom_room",
      "herb_slope"
    ],
    "object": "herb_garden",
    "kind": "switchback",
    "material_fraction": 0.3,
    "social_labor": true,
    "sensory_alignment": 0.341475,
    "progress": 1.0,
    "integrity": 0.82,
    "maintained": false,
    "completed_now": true,
    "route_mutated": true,
    "object_coupled": true
  },
  {
    "cycle": 75,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "project_id": "ash_drain",
    "project_name": "ash drainage trench",
    "route": [
      "grain_shade",
      "ash_edge"
    ],
    "object": "waste_pit",
    "kind": "drainage",
    "material_fraction": 0.363636,
    "social_labor": true,
    "sensory_alignment": 0.902714,
    "progress": 1.0,
    "integrity": 0.860503,
    "maintained": true,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 76,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "project_id": "water_channel",
    "project_name": "cistern water channel",
    "route": [
      "storage_yard",
      "spring_hollow"
    ],
    "object": "clay_cistern",
    "kind": "channel",
    "material_fraction": 0.307692,
    "social_labor": true,
    "sensory_alignment": 0.907956,
    "progress": 1.0,
    "integrity": 0.881712,
    "maintained": true,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 77,
    "agent_id": "integrated_deep_time_world:04",
    "agent_name": "Eli",
    "role": "guard",
    "project_id": "drum_resonance_posts",
    "project_name": "drum resonance posts",
    "route": [
      "central_hearth",
      "drum_court"
    ],
    "object": "signal_drum",
    "kind": "signal",
    "material_fraction": 0.3,
    "social_labor": true,
    "sensory_alignment": 0.722077,
    "progress": 1.0,
    "integrity": 0.82,
    "maintained": false,
    "completed_now": true,
    "route_mutated": true,
    "object_coupled": true
  },
  {
    "cycle": 78,
    "agent_id": "integrated_deep_time_world:05",
    "agent_name": "Fay",
    "role": "teacher",
    "project_id": "covered_walk",
    "project_name": "covered nursery walk",
    "route": [
      "nursery_nest",
      "loom_room"
    ],
    "object": "nursery_mat",
    "kind": "covered_walk",
    "material_fraction": 0.333333,
    "social_labor": true,
    "sensory_alignment": 0.449067,
    "progress": 1.0,
    "integrity": 0.82,
    "maintained": false,
    "completed_now": true,
    "route_mutated": true,
    "object_coupled": true
  },
  {
    "cycle": 79,
    "agent_id": "integrated_deep_time_world:06",
    "agent_name": "Gus",
    "role": "trader",
    "project_id": "mud_causeway",
    "project_name": "mud causeway",
    "route": [
      "storage_yard",
      "spring_hollow"
    ],
    "object": "spring_pool",
    "kind": "road",
    "material_fraction": 0.363636,
    "social_labor": true,
    "sensory_alignment": 0.353646,
    "progress": 1.0,
    "integrity": 0.791069,
    "maintained": true,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 80,
    "agent_id": "integrated_deep_time_world:07",
    "agent_name": "Ira",
    "role": "pattern_keeper",
    "project_id": "archive_waystones",
    "project_name": "archive waystones",
    "route": [
      "tool_bend",
      "archive_knoll"
    ],
    "object": "archive_stone",
    "kind": "signage",
    "material_fraction": 0.4,
    "social_labor": true,
    "sensory_alignment": 0.593567,
    "progress": 1.0,
    "integrity": 0.82,
    "maintained": false,
    "completed_now": true,
    "route_mutated": true,
    "object_coupled": true
  },
  {
    "cycle": 81,
    "agent_id": "integrated_deep_time_world:00",
    "agent_name": "Ari",
    "role": "scout",
    "project_id": "smoke_watchtower",
    "project_name": "smoke watchtower",
    "route": [
      "drum_court",
      "smoke_watch"
    ],
    "object": "smoke_marker",
    "kind": "watch",
    "material_fraction": 0.285714,
    "social_labor": true,
    "sensory_alignment": 0.461096,
    "progress": 1.0,
    "integrity": 0.822072,
    "maintained": true,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 82,
    "agent_id": "integrated_deep_time_world:01",
    "agent_name": "Bo",
    "role": "builder",
    "project_id": "tool_sledge_path",
    "project_name": "tool sledge path",
    "route": [
      "central_hearth",
      "tool_bend"
    ],
    "object": "tool_cache",
    "kind": "haul_path",
    "material_fraction": 0.416667,
    "social_labor": true,
    "sensory_alignment": 0.461209,
    "progress": 1.0,
    "integrity": 0.848205,
    "maintained": true,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 83,
    "agent_id": "integrated_deep_time_world:02",
    "agent_name": "Cy",
    "role": "healer",
    "project_id": "herb_switchback",
    "project_name": "herb slope switchback",
    "route": [
      "loom_room",
      "herb_slope"
    ],
    "object": "herb_garden",
    "kind": "switchback",
    "material_fraction": 0.3,
    "social_labor": true,
    "sensory_alignment": 0.91411,
    "progress": 1.0,
    "integrity": 0.805394,
    "maintained": true,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  },
  {
    "cycle": 84,
    "agent_id": "integrated_deep_time_world:03",
    "agent_name": "Dee",
    "role": "farmer",
    "project_id": "water_channel",
    "project_name": "cistern water channel",
    "route": [
      "storage_yard",
      "spring_hollow"
    ],
    "object": "clay_cistern",
    "kind": "channel",
    "material_fraction": 0.307692,
    "social_labor": true,
    "sensory_alignment": 0.653634,
    "progress": 1.0,
    "integrity": 0.866841,
    "maintained": false,
    "completed_now": false,
    "route_mutated": false,
    "object_coupled": false
  }
];
