window.SSRM_3D_DEEP_TIME_CULTURAL_MEMORY_TRACE = [
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 0,
    "event_id": 0,
    "flower_bindings": {
      "boundary": "work_petal",
      "danger": "social_petal",
      "flower": "social_petal",
      "kin": "return_petal",
      "repair": "explore_petal",
      "return": "return_petal",
      "safe_place": "root_rest",
      "sleep": "dawn_breath",
      "song": "explore_petal",
      "tool": "root_rest",
      "warmth": "work_petal",
      "water": "dawn_breath"
    },
    "frequency_bindings": {
      "boundary": 0.316,
      "danger": 0.231,
      "flower": 0.333,
      "kin": 0.265,
      "repair": 0.248,
      "return": 0.367,
      "safe_place": 0.18,
      "sleep": 0.299,
      "song": 0.35,
      "tool": 0.282,
      "warmth": 0.214,
      "water": 0.197
    },
    "group": "hearth_circle",
    "innovation_count": 0,
    "lexicon": {
      "boundary": "bar-ha",
      "danger": "grak-ha",
      "flower": "fol-ha",
      "kin": "ari-ha",
      "repair": "mend-ha",
      "return": "tor-ha",
      "safe_place": "lum-ha",
      "sleep": "soma-ha",
      "song": "rin-ha",
      "tool": "tek-ha",
      "warmth": "ka-ha",
      "water": "wa-ha"
    },
    "lineage_record": {
      "ancestor_hash": "root-culture-seed",
      "culture_hash": "879e071caf92f773",
      "era": 0,
      "year_end": 200,
      "year_start": 0
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "warm_return_song@root_rest",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 200,
    "year_start": 0
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 0,
    "event_id": 1,
    "flower_bindings": {
      "boundary": "social_petal",
      "danger": "explore_petal",
      "flower": "explore_petal",
      "kin": "root_rest",
      "repair": "return_petal",
      "return": "root_rest",
      "safe_place": "dawn_breath",
      "sleep": "work_petal",
      "song": "return_petal",
      "tool": "dawn_breath",
      "warmth": "social_petal",
      "water": "work_petal"
    },
    "frequency_bindings": {
      "boundary": 0.327,
      "danger": 0.242,
      "flower": 0.344,
      "kin": 0.276,
      "repair": 0.259,
      "return": 0.378,
      "safe_place": 0.191,
      "sleep": 0.31,
      "song": 0.361,
      "tool": 0.293,
      "warmth": 0.225,
      "water": 0.208
    },
    "group": "work_band",
    "innovation_count": 0,
    "lexicon": {
      "boundary": "bar-wo",
      "danger": "grak-wo",
      "flower": "fol-wo",
      "kin": "ari-wo",
      "repair": "mend-wo",
      "return": "tor-wo",
      "safe_place": "lum-wo",
      "sleep": "soma-wo",
      "song": "rin-wo",
      "tool": "tek-wo",
      "warmth": "ka-wo",
      "water": "wa-wo"
    },
    "lineage_record": {
      "ancestor_hash": "root-culture-seed",
      "culture_hash": "363b9eca3bacf4f8",
      "era": 0,
      "year_end": 200,
      "year_start": 0
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "tool_mending_call@root_rest",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 200,
    "year_start": 0
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 0,
    "event_id": 2,
    "flower_bindings": {
      "boundary": "explore_petal",
      "danger": "return_petal",
      "flower": "return_petal",
      "kin": "dawn_breath",
      "repair": "root_rest",
      "return": "dawn_breath",
      "safe_place": "work_petal",
      "sleep": "social_petal",
      "song": "root_rest",
      "tool": "work_petal",
      "warmth": "explore_petal",
      "water": "social_petal"
    },
    "frequency_bindings": {
      "boundary": 0.338,
      "danger": 0.253,
      "flower": 0.355,
      "kin": 0.287,
      "repair": 0.27,
      "return": 0.389,
      "safe_place": 0.202,
      "sleep": 0.321,
      "song": 0.372,
      "tool": 0.304,
      "warmth": 0.236,
      "water": 0.219
    },
    "group": "edge_watch",
    "innovation_count": 0,
    "lexicon": {
      "boundary": "bar-ed",
      "danger": "grak-ed",
      "flower": "fol-ed",
      "kin": "ari-ed",
      "repair": "mend-ed",
      "return": "tor-ed",
      "safe_place": "lum-ed",
      "sleep": "soma-ed",
      "song": "rin-ed",
      "tool": "tek-ed",
      "warmth": "ka-ed",
      "water": "wa-ed"
    },
    "lineage_record": {
      "ancestor_hash": "root-culture-seed",
      "culture_hash": "a6cbf2cb99416240",
      "era": 0,
      "year_end": 200,
      "year_start": 0
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "safe_boundary_watch@root_rest",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 200,
    "year_start": 0
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 1,
    "event_id": 3,
    "flower_bindings": {
      "boundary": "social_petal",
      "danger": "explore_petal",
      "flower": "explore_petal",
      "kin": "root_rest",
      "repair": "return_petal",
      "return": "root_rest",
      "safe_place": "dawn_breath",
      "sleep": "work_petal",
      "song": "return_petal",
      "tool": "dawn_breath",
      "warmth": "social_petal",
      "water": "work_petal"
    },
    "frequency_bindings": {
      "boundary": 0.319,
      "danger": 0.234,
      "flower": 0.336,
      "kin": 0.268,
      "repair": 0.251,
      "return": 0.37,
      "safe_place": 0.183,
      "sleep": 0.302,
      "song": 0.353,
      "tool": 0.285,
      "warmth": 0.217,
      "water": 0.2
    },
    "group": "hearth_circle",
    "innovation_count": 2,
    "lexicon": {
      "boundary": "baru-ha",
      "danger": "grak-ha",
      "flower": "fol-ha",
      "kin": "arii-ha",
      "repair": "mend-ha",
      "return": "tor-ha",
      "safe_place": "lum-ha",
      "sleep": "somae-ha",
      "song": "rinu-ha",
      "tool": "teku-ha",
      "warmth": "ka-ha",
      "water": "wae-ha"
    },
    "lineage_record": {
      "ancestor_hash": "844ed5f47e6b7b0a",
      "culture_hash": "1b0682ff0eec2812",
      "era": 1,
      "year_end": 400,
      "year_start": 200
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "warm_return_song@dawn_breath",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 400,
    "year_start": 200
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 1,
    "event_id": 4,
    "flower_bindings": {
      "boundary": "explore_petal",
      "danger": "return_petal",
      "flower": "return_petal",
      "kin": "dawn_breath",
      "repair": "root_rest",
      "return": "dawn_breath",
      "safe_place": "work_petal",
      "sleep": "social_petal",
      "song": "root_rest",
      "tool": "work_petal",
      "warmth": "explore_petal",
      "water": "social_petal"
    },
    "frequency_bindings": {
      "boundary": 0.33,
      "danger": 0.245,
      "flower": 0.347,
      "kin": 0.279,
      "repair": 0.262,
      "return": 0.381,
      "safe_place": 0.194,
      "sleep": 0.313,
      "song": 0.364,
      "tool": 0.296,
      "warmth": 0.228,
      "water": 0.211
    },
    "group": "work_band",
    "innovation_count": 2,
    "lexicon": {
      "boundary": "baru-wo",
      "danger": "grak-wo",
      "flower": "fol-wo",
      "kin": "arii-wo",
      "repair": "mend-wo",
      "return": "tor-wo",
      "safe_place": "lum-wo",
      "sleep": "somae-wo",
      "song": "rinu-wo",
      "tool": "teku-wo",
      "warmth": "ka-wo",
      "water": "wae-wo"
    },
    "lineage_record": {
      "ancestor_hash": "844ed5f47e6b7b0a",
      "culture_hash": "e5940224c2ad21c4",
      "era": 1,
      "year_end": 400,
      "year_start": 200
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "tool_mending_call@dawn_breath",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 400,
    "year_start": 200
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 1,
    "event_id": 5,
    "flower_bindings": {
      "boundary": "return_petal",
      "danger": "root_rest",
      "flower": "root_rest",
      "kin": "work_petal",
      "repair": "dawn_breath",
      "return": "work_petal",
      "safe_place": "social_petal",
      "sleep": "explore_petal",
      "song": "dawn_breath",
      "tool": "social_petal",
      "warmth": "return_petal",
      "water": "explore_petal"
    },
    "frequency_bindings": {
      "boundary": 0.341,
      "danger": 0.256,
      "flower": 0.358,
      "kin": 0.29,
      "repair": 0.273,
      "return": 0.392,
      "safe_place": 0.205,
      "sleep": 0.324,
      "song": 0.375,
      "tool": 0.307,
      "warmth": 0.239,
      "water": 0.222
    },
    "group": "edge_watch",
    "innovation_count": 2,
    "lexicon": {
      "boundary": "bare-ed",
      "danger": "graki-ed",
      "flower": "foli-ed",
      "kin": "ariu-ed",
      "repair": "mendi-ed",
      "return": "tori-ed",
      "safe_place": "lumi-ed",
      "sleep": "soma-ed",
      "song": "rine-ed",
      "tool": "teke-ed",
      "warmth": "kai-ed",
      "water": "wa-ed"
    },
    "lineage_record": {
      "ancestor_hash": "844ed5f47e6b7b0a",
      "culture_hash": "2b0e0d9a53a4c956",
      "era": 1,
      "year_end": 400,
      "year_start": 200
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "safe_boundary_watch@dawn_breath",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 400,
    "year_start": 200
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 2,
    "event_id": 6,
    "flower_bindings": {
      "boundary": "explore_petal",
      "danger": "return_petal",
      "flower": "return_petal",
      "kin": "dawn_breath",
      "repair": "root_rest",
      "return": "dawn_breath",
      "safe_place": "work_petal",
      "sleep": "social_petal",
      "song": "root_rest",
      "tool": "work_petal",
      "warmth": "explore_petal",
      "water": "social_petal"
    },
    "frequency_bindings": {
      "boundary": 0.322,
      "danger": 0.237,
      "flower": 0.339,
      "kin": 0.271,
      "repair": 0.254,
      "return": 0.373,
      "safe_place": 0.186,
      "sleep": 0.305,
      "song": 0.356,
      "tool": 0.288,
      "warmth": 0.22,
      "water": 0.203
    },
    "group": "hearth_circle",
    "innovation_count": 2,
    "lexicon": {
      "boundary": "bare-ha",
      "danger": "graki-ha",
      "flower": "foli-ha",
      "kin": "ariu-ha",
      "repair": "mendi-ha",
      "return": "tori-ha",
      "safe_place": "lumi-ha",
      "sleep": "soma-ha",
      "song": "rine-ha",
      "tool": "teke-ha",
      "warmth": "kai-ha",
      "water": "wa-ha"
    },
    "lineage_record": {
      "ancestor_hash": "6493839f5eb9e628",
      "culture_hash": "3ce30ca9258d41ff",
      "era": 2,
      "year_end": 600,
      "year_start": 400
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "warm_return_song@work_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 600,
    "year_start": 400
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 2,
    "event_id": 7,
    "flower_bindings": {
      "boundary": "return_petal",
      "danger": "root_rest",
      "flower": "root_rest",
      "kin": "work_petal",
      "repair": "dawn_breath",
      "return": "work_petal",
      "safe_place": "social_petal",
      "sleep": "explore_petal",
      "song": "dawn_breath",
      "tool": "social_petal",
      "warmth": "return_petal",
      "water": "explore_petal"
    },
    "frequency_bindings": {
      "boundary": 0.333,
      "danger": 0.248,
      "flower": 0.35,
      "kin": 0.282,
      "repair": 0.265,
      "return": 0.384,
      "safe_place": 0.197,
      "sleep": 0.316,
      "song": 0.367,
      "tool": 0.299,
      "warmth": 0.231,
      "water": 0.214
    },
    "group": "work_band",
    "innovation_count": 2,
    "lexicon": {
      "boundary": "bare-wo",
      "danger": "graki-wo",
      "flower": "foli-wo",
      "kin": "ariu-wo",
      "repair": "mendi-wo",
      "return": "tori-wo",
      "safe_place": "lumi-wo",
      "sleep": "soma-wo",
      "song": "rine-wo",
      "tool": "teke-wo",
      "warmth": "kai-wo",
      "water": "wa-wo"
    },
    "lineage_record": {
      "ancestor_hash": "6493839f5eb9e628",
      "culture_hash": "65d07772d3b5b1ca",
      "era": 2,
      "year_end": 600,
      "year_start": 400
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "tool_mending_call@work_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 600,
    "year_start": 400
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 2,
    "event_id": 8,
    "flower_bindings": {
      "boundary": "root_rest",
      "danger": "dawn_breath",
      "flower": "dawn_breath",
      "kin": "social_petal",
      "repair": "work_petal",
      "return": "social_petal",
      "safe_place": "explore_petal",
      "sleep": "return_petal",
      "song": "work_petal",
      "tool": "explore_petal",
      "warmth": "root_rest",
      "water": "return_petal"
    },
    "frequency_bindings": {
      "boundary": 0.344,
      "danger": 0.259,
      "flower": 0.361,
      "kin": 0.293,
      "repair": 0.276,
      "return": 0.395,
      "safe_place": 0.208,
      "sleep": 0.327,
      "song": 0.378,
      "tool": 0.31,
      "warmth": 0.242,
      "water": 0.225
    },
    "group": "edge_watch",
    "innovation_count": 3,
    "lexicon": {
      "boundary": "bar-ed",
      "danger": "graku-ed",
      "flower": "folu-ed",
      "kin": "arie-ed",
      "repair": "mendu-ed",
      "return": "toru-ed",
      "safe_place": "lumu-ed",
      "sleep": "somai-ed",
      "song": "rin-ed",
      "tool": "tek-ed",
      "warmth": "kau-ed",
      "water": "wai-ed"
    },
    "lineage_record": {
      "ancestor_hash": "6493839f5eb9e628",
      "culture_hash": "ea96700551d51eec",
      "era": 2,
      "year_end": 600,
      "year_start": 400
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "safe_boundary_watch@work_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 600,
    "year_start": 400
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 3,
    "event_id": 9,
    "flower_bindings": {
      "boundary": "return_petal",
      "danger": "root_rest",
      "flower": "root_rest",
      "kin": "work_petal",
      "repair": "dawn_breath",
      "return": "work_petal",
      "safe_place": "social_petal",
      "sleep": "explore_petal",
      "song": "dawn_breath",
      "tool": "social_petal",
      "warmth": "return_petal",
      "water": "explore_petal"
    },
    "frequency_bindings": {
      "boundary": 0.325,
      "danger": 0.24,
      "flower": 0.342,
      "kin": 0.274,
      "repair": 0.257,
      "return": 0.376,
      "safe_place": 0.189,
      "sleep": 0.308,
      "song": 0.359,
      "tool": 0.291,
      "warmth": 0.223,
      "water": 0.206
    },
    "group": "hearth_circle",
    "innovation_count": 2,
    "lexicon": {
      "boundary": "bar-ha",
      "danger": "graku-ha",
      "flower": "folu-ha",
      "kin": "arie-ha",
      "repair": "mendu-ha",
      "return": "toru-ha",
      "safe_place": "lumu-ha",
      "sleep": "somai-ha",
      "song": "rin-ha",
      "tool": "tek-ha",
      "warmth": "kau-ha",
      "water": "wai-ha"
    },
    "lineage_record": {
      "ancestor_hash": "1aa55e56cb58fb2d",
      "culture_hash": "3a9b085b906c8fc1",
      "era": 3,
      "year_end": 800,
      "year_start": 600
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "warm_return_song@social_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 800,
    "year_start": 600
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 3,
    "event_id": 10,
    "flower_bindings": {
      "boundary": "root_rest",
      "danger": "dawn_breath",
      "flower": "dawn_breath",
      "kin": "social_petal",
      "repair": "work_petal",
      "return": "social_petal",
      "safe_place": "explore_petal",
      "sleep": "return_petal",
      "song": "work_petal",
      "tool": "explore_petal",
      "warmth": "root_rest",
      "water": "return_petal"
    },
    "frequency_bindings": {
      "boundary": 0.336,
      "danger": 0.251,
      "flower": 0.353,
      "kin": 0.285,
      "repair": 0.268,
      "return": 0.387,
      "safe_place": 0.2,
      "sleep": 0.319,
      "song": 0.37,
      "tool": 0.302,
      "warmth": 0.234,
      "water": 0.217
    },
    "group": "work_band",
    "innovation_count": 3,
    "lexicon": {
      "boundary": "bar-wo",
      "danger": "graku-wo",
      "flower": "folu-wo",
      "kin": "arie-wo",
      "repair": "mendu-wo",
      "return": "toru-wo",
      "safe_place": "lumu-wo",
      "sleep": "somai-wo",
      "song": "rin-wo",
      "tool": "tek-wo",
      "warmth": "kau-wo",
      "water": "wai-wo"
    },
    "lineage_record": {
      "ancestor_hash": "1aa55e56cb58fb2d",
      "culture_hash": "690f98cfa08ecf56",
      "era": 3,
      "year_end": 800,
      "year_start": 600
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "tool_mending_call@social_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 800,
    "year_start": 600
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 3,
    "event_id": 11,
    "flower_bindings": {
      "boundary": "dawn_breath",
      "danger": "work_petal",
      "flower": "work_petal",
      "kin": "explore_petal",
      "repair": "social_petal",
      "return": "explore_petal",
      "safe_place": "return_petal",
      "sleep": "root_rest",
      "song": "social_petal",
      "tool": "return_petal",
      "warmth": "dawn_breath",
      "water": "root_rest"
    },
    "frequency_bindings": {
      "boundary": 0.347,
      "danger": 0.262,
      "flower": 0.364,
      "kin": 0.296,
      "repair": 0.279,
      "return": 0.398,
      "safe_place": 0.211,
      "sleep": 0.33,
      "song": 0.381,
      "tool": 0.313,
      "warmth": 0.245,
      "water": 0.228
    },
    "group": "edge_watch",
    "innovation_count": 3,
    "lexicon": {
      "boundary": "bari-ed",
      "danger": "grake-ed",
      "flower": "fole-ed",
      "kin": "ari-ed",
      "repair": "mende-ed",
      "return": "tore-ed",
      "safe_place": "lume-ed",
      "sleep": "somau-ed",
      "song": "rini-ed",
      "tool": "teki-ed",
      "warmth": "kae-ed",
      "water": "wau-ed"
    },
    "lineage_record": {
      "ancestor_hash": "1aa55e56cb58fb2d",
      "culture_hash": "852794d2285ffbdc",
      "era": 3,
      "year_end": 800,
      "year_start": 600
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "safe_boundary_watch@social_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 800,
    "year_start": 600
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 4,
    "event_id": 12,
    "flower_bindings": {
      "boundary": "root_rest",
      "danger": "dawn_breath",
      "flower": "dawn_breath",
      "kin": "social_petal",
      "repair": "work_petal",
      "return": "social_petal",
      "safe_place": "explore_petal",
      "sleep": "return_petal",
      "song": "work_petal",
      "tool": "explore_petal",
      "warmth": "root_rest",
      "water": "return_petal"
    },
    "frequency_bindings": {
      "boundary": 0.328,
      "danger": 0.243,
      "flower": 0.345,
      "kin": 0.277,
      "repair": 0.26,
      "return": 0.379,
      "safe_place": 0.192,
      "sleep": 0.311,
      "song": 0.362,
      "tool": 0.294,
      "warmth": 0.226,
      "water": 0.209
    },
    "group": "hearth_circle",
    "innovation_count": 3,
    "lexicon": {
      "boundary": "bari-ha",
      "danger": "grake-ha",
      "flower": "fole-ha",
      "kin": "ari-ha",
      "repair": "mende-ha",
      "return": "tore-ha",
      "safe_place": "lume-ha",
      "sleep": "somau-ha",
      "song": "rini-ha",
      "tool": "teki-ha",
      "warmth": "kae-ha",
      "water": "wau-ha"
    },
    "lineage_record": {
      "ancestor_hash": "329d9e7cbbf1f0a7",
      "culture_hash": "2db66ffae22e9e4b",
      "era": 4,
      "year_end": 1000,
      "year_start": 800
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "warm_return_song@explore_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 1000,
    "year_start": 800
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 4,
    "event_id": 13,
    "flower_bindings": {
      "boundary": "dawn_breath",
      "danger": "work_petal",
      "flower": "work_petal",
      "kin": "explore_petal",
      "repair": "social_petal",
      "return": "explore_petal",
      "safe_place": "return_petal",
      "sleep": "root_rest",
      "song": "social_petal",
      "tool": "return_petal",
      "warmth": "dawn_breath",
      "water": "root_rest"
    },
    "frequency_bindings": {
      "boundary": 0.339,
      "danger": 0.254,
      "flower": 0.356,
      "kin": 0.288,
      "repair": 0.271,
      "return": 0.39,
      "safe_place": 0.203,
      "sleep": 0.322,
      "song": 0.373,
      "tool": 0.305,
      "warmth": 0.237,
      "water": 0.22
    },
    "group": "work_band",
    "innovation_count": 3,
    "lexicon": {
      "boundary": "bari-wo",
      "danger": "grake-wo",
      "flower": "fole-wo",
      "kin": "ari-wo",
      "repair": "mende-wo",
      "return": "tore-wo",
      "safe_place": "lume-wo",
      "sleep": "somau-wo",
      "song": "rini-wo",
      "tool": "teki-wo",
      "warmth": "kae-wo",
      "water": "wau-wo"
    },
    "lineage_record": {
      "ancestor_hash": "329d9e7cbbf1f0a7",
      "culture_hash": "d9cb15900644ee7e",
      "era": 4,
      "year_end": 1000,
      "year_start": 800
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "tool_mending_call@explore_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 1000,
    "year_start": 800
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 4,
    "event_id": 14,
    "flower_bindings": {
      "boundary": "work_petal",
      "danger": "social_petal",
      "flower": "social_petal",
      "kin": "return_petal",
      "repair": "explore_petal",
      "return": "return_petal",
      "safe_place": "root_rest",
      "sleep": "dawn_breath",
      "song": "explore_petal",
      "tool": "root_rest",
      "warmth": "work_petal",
      "water": "dawn_breath"
    },
    "frequency_bindings": {
      "boundary": 0.35,
      "danger": 0.265,
      "flower": 0.367,
      "kin": 0.299,
      "repair": 0.282,
      "return": 0.401,
      "safe_place": 0.214,
      "sleep": 0.333,
      "song": 0.384,
      "tool": 0.316,
      "warmth": 0.248,
      "water": 0.231
    },
    "group": "edge_watch",
    "innovation_count": 2,
    "lexicon": {
      "boundary": "baru-ed",
      "danger": "grak-ed",
      "flower": "fol-ed",
      "kin": "arii-ed",
      "repair": "mend-ed",
      "return": "tor-ed",
      "safe_place": "lum-ed",
      "sleep": "somae-ed",
      "song": "rinu-ed",
      "tool": "teku-ed",
      "warmth": "ka-ed",
      "water": "wae-ed"
    },
    "lineage_record": {
      "ancestor_hash": "329d9e7cbbf1f0a7",
      "culture_hash": "485eba9c0d4e61b8",
      "era": 4,
      "year_end": 1000,
      "year_start": 800
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "safe_boundary_watch@explore_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 1000,
    "year_start": 800
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 5,
    "event_id": 15,
    "flower_bindings": {
      "boundary": "dawn_breath",
      "danger": "work_petal",
      "flower": "work_petal",
      "kin": "explore_petal",
      "repair": "social_petal",
      "return": "explore_petal",
      "safe_place": "return_petal",
      "sleep": "root_rest",
      "song": "social_petal",
      "tool": "return_petal",
      "warmth": "dawn_breath",
      "water": "root_rest"
    },
    "frequency_bindings": {
      "boundary": 0.331,
      "danger": 0.246,
      "flower": 0.348,
      "kin": 0.28,
      "repair": 0.263,
      "return": 0.382,
      "safe_place": 0.195,
      "sleep": 0.314,
      "song": 0.365,
      "tool": 0.297,
      "warmth": 0.229,
      "water": 0.212
    },
    "group": "hearth_circle",
    "innovation_count": 3,
    "lexicon": {
      "boundary": "baru-ha",
      "danger": "grak-ha",
      "flower": "fol-ha",
      "kin": "arii-ha",
      "repair": "mend-ha",
      "return": "tor-ha",
      "safe_place": "lum-ha",
      "sleep": "somae-ha",
      "song": "rinu-ha",
      "tool": "teku-ha",
      "warmth": "ka-ha",
      "water": "wae-ha"
    },
    "lineage_record": {
      "ancestor_hash": "af2570ad61ee6e00",
      "culture_hash": "627ffca231ac8c78",
      "era": 5,
      "year_end": 1200,
      "year_start": 1000
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "warm_return_song@return_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 1200,
    "year_start": 1000
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 5,
    "event_id": 16,
    "flower_bindings": {
      "boundary": "work_petal",
      "danger": "social_petal",
      "flower": "social_petal",
      "kin": "return_petal",
      "repair": "explore_petal",
      "return": "return_petal",
      "safe_place": "root_rest",
      "sleep": "dawn_breath",
      "song": "explore_petal",
      "tool": "root_rest",
      "warmth": "work_petal",
      "water": "dawn_breath"
    },
    "frequency_bindings": {
      "boundary": 0.342,
      "danger": 0.257,
      "flower": 0.359,
      "kin": 0.291,
      "repair": 0.274,
      "return": 0.393,
      "safe_place": 0.206,
      "sleep": 0.325,
      "song": 0.376,
      "tool": 0.308,
      "warmth": 0.24,
      "water": 0.223
    },
    "group": "work_band",
    "innovation_count": 2,
    "lexicon": {
      "boundary": "baru-wo",
      "danger": "grak-wo",
      "flower": "fol-wo",
      "kin": "arii-wo",
      "repair": "mend-wo",
      "return": "tor-wo",
      "safe_place": "lum-wo",
      "sleep": "somae-wo",
      "song": "rinu-wo",
      "tool": "teku-wo",
      "warmth": "ka-wo",
      "water": "wae-wo"
    },
    "lineage_record": {
      "ancestor_hash": "af2570ad61ee6e00",
      "culture_hash": "f8e62922a2d9114e",
      "era": 5,
      "year_end": 1200,
      "year_start": 1000
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "tool_mending_call@return_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 1200,
    "year_start": 1000
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 5,
    "event_id": 17,
    "flower_bindings": {
      "boundary": "social_petal",
      "danger": "explore_petal",
      "flower": "explore_petal",
      "kin": "root_rest",
      "repair": "return_petal",
      "return": "root_rest",
      "safe_place": "dawn_breath",
      "sleep": "work_petal",
      "song": "return_petal",
      "tool": "dawn_breath",
      "warmth": "social_petal",
      "water": "work_petal"
    },
    "frequency_bindings": {
      "boundary": 0.353,
      "danger": 0.268,
      "flower": 0.37,
      "kin": 0.302,
      "repair": 0.285,
      "return": 0.404,
      "safe_place": 0.217,
      "sleep": 0.336,
      "song": 0.387,
      "tool": 0.319,
      "warmth": 0.251,
      "water": 0.234
    },
    "group": "edge_watch",
    "innovation_count": 2,
    "lexicon": {
      "boundary": "bare-ed",
      "danger": "graki-ed",
      "flower": "foli-ed",
      "kin": "ariu-ed",
      "repair": "mendi-ed",
      "return": "tori-ed",
      "safe_place": "lumi-ed",
      "sleep": "soma-ed",
      "song": "rine-ed",
      "tool": "teke-ed",
      "warmth": "kai-ed",
      "water": "wa-ed"
    },
    "lineage_record": {
      "ancestor_hash": "af2570ad61ee6e00",
      "culture_hash": "05e9802706c976ed",
      "era": 5,
      "year_end": 1200,
      "year_start": 1000
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "safe_boundary_watch@return_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 1200,
    "year_start": 1000
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 6,
    "event_id": 18,
    "flower_bindings": {
      "boundary": "work_petal",
      "danger": "social_petal",
      "flower": "social_petal",
      "kin": "return_petal",
      "repair": "explore_petal",
      "return": "return_petal",
      "safe_place": "root_rest",
      "sleep": "dawn_breath",
      "song": "explore_petal",
      "tool": "root_rest",
      "warmth": "work_petal",
      "water": "dawn_breath"
    },
    "frequency_bindings": {
      "boundary": 0.316,
      "danger": 0.231,
      "flower": 0.333,
      "kin": 0.265,
      "repair": 0.248,
      "return": 0.367,
      "safe_place": 0.18,
      "sleep": 0.299,
      "song": 0.35,
      "tool": 0.282,
      "warmth": 0.214,
      "water": 0.197
    },
    "group": "hearth_circle",
    "innovation_count": 2,
    "lexicon": {
      "boundary": "bare-ha",
      "danger": "graki-ha",
      "flower": "foli-ha",
      "kin": "ariu-ha",
      "repair": "mendi-ha",
      "return": "tori-ha",
      "safe_place": "lumi-ha",
      "sleep": "soma-ha",
      "song": "rine-ha",
      "tool": "teke-ha",
      "warmth": "kai-ha",
      "water": "wa-ha"
    },
    "lineage_record": {
      "ancestor_hash": "f53d7342a15762ef",
      "culture_hash": "abd966329965f5a9",
      "era": 6,
      "year_end": 1400,
      "year_start": 1200
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "warm_return_song@root_rest",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 1400,
    "year_start": 1200
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 6,
    "event_id": 19,
    "flower_bindings": {
      "boundary": "social_petal",
      "danger": "explore_petal",
      "flower": "explore_petal",
      "kin": "root_rest",
      "repair": "return_petal",
      "return": "root_rest",
      "safe_place": "dawn_breath",
      "sleep": "work_petal",
      "song": "return_petal",
      "tool": "dawn_breath",
      "warmth": "social_petal",
      "water": "work_petal"
    },
    "frequency_bindings": {
      "boundary": 0.327,
      "danger": 0.242,
      "flower": 0.344,
      "kin": 0.276,
      "repair": 0.259,
      "return": 0.378,
      "safe_place": 0.191,
      "sleep": 0.31,
      "song": 0.361,
      "tool": 0.293,
      "warmth": 0.225,
      "water": 0.208
    },
    "group": "work_band",
    "innovation_count": 2,
    "lexicon": {
      "boundary": "bare-wo",
      "danger": "graki-wo",
      "flower": "foli-wo",
      "kin": "ariu-wo",
      "repair": "mendi-wo",
      "return": "tori-wo",
      "safe_place": "lumi-wo",
      "sleep": "soma-wo",
      "song": "rine-wo",
      "tool": "teke-wo",
      "warmth": "kai-wo",
      "water": "wa-wo"
    },
    "lineage_record": {
      "ancestor_hash": "f53d7342a15762ef",
      "culture_hash": "84fd06777b8397fa",
      "era": 6,
      "year_end": 1400,
      "year_start": 1200
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "tool_mending_call@root_rest",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 1400,
    "year_start": 1200
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 6,
    "event_id": 20,
    "flower_bindings": {
      "boundary": "explore_petal",
      "danger": "return_petal",
      "flower": "return_petal",
      "kin": "dawn_breath",
      "repair": "root_rest",
      "return": "dawn_breath",
      "safe_place": "work_petal",
      "sleep": "social_petal",
      "song": "root_rest",
      "tool": "work_petal",
      "warmth": "explore_petal",
      "water": "social_petal"
    },
    "frequency_bindings": {
      "boundary": 0.338,
      "danger": 0.253,
      "flower": 0.355,
      "kin": 0.287,
      "repair": 0.27,
      "return": 0.389,
      "safe_place": 0.202,
      "sleep": 0.321,
      "song": 0.372,
      "tool": 0.304,
      "warmth": 0.236,
      "water": 0.219
    },
    "group": "edge_watch",
    "innovation_count": 2,
    "lexicon": {
      "boundary": "bar-ed",
      "danger": "graku-ed",
      "flower": "folu-ed",
      "kin": "arie-ed",
      "repair": "mendu-ed",
      "return": "toru-ed",
      "safe_place": "lumu-ed",
      "sleep": "somai-ed",
      "song": "rin-ed",
      "tool": "tek-ed",
      "warmth": "kau-ed",
      "water": "wai-ed"
    },
    "lineage_record": {
      "ancestor_hash": "f53d7342a15762ef",
      "culture_hash": "9f9837c012559e0a",
      "era": 6,
      "year_end": 1400,
      "year_start": 1200
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "safe_boundary_watch@root_rest",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 1400,
    "year_start": 1200
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 7,
    "event_id": 21,
    "flower_bindings": {
      "boundary": "social_petal",
      "danger": "explore_petal",
      "flower": "explore_petal",
      "kin": "root_rest",
      "repair": "return_petal",
      "return": "root_rest",
      "safe_place": "dawn_breath",
      "sleep": "work_petal",
      "song": "return_petal",
      "tool": "dawn_breath",
      "warmth": "social_petal",
      "water": "work_petal"
    },
    "frequency_bindings": {
      "boundary": 0.319,
      "danger": 0.234,
      "flower": 0.336,
      "kin": 0.268,
      "repair": 0.251,
      "return": 0.37,
      "safe_place": 0.183,
      "sleep": 0.302,
      "song": 0.353,
      "tool": 0.285,
      "warmth": 0.217,
      "water": 0.2
    },
    "group": "hearth_circle",
    "innovation_count": 2,
    "lexicon": {
      "boundary": "bar-ha",
      "danger": "graku-ha",
      "flower": "folu-ha",
      "kin": "arie-ha",
      "repair": "mendu-ha",
      "return": "toru-ha",
      "safe_place": "lumu-ha",
      "sleep": "somai-ha",
      "song": "rin-ha",
      "tool": "tek-ha",
      "warmth": "kau-ha",
      "water": "wai-ha"
    },
    "lineage_record": {
      "ancestor_hash": "a04ebbfa05683415",
      "culture_hash": "d429fb7c3b6735b2",
      "era": 7,
      "year_end": 1600,
      "year_start": 1400
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "warm_return_song@dawn_breath",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 1600,
    "year_start": 1400
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 7,
    "event_id": 22,
    "flower_bindings": {
      "boundary": "explore_petal",
      "danger": "return_petal",
      "flower": "return_petal",
      "kin": "dawn_breath",
      "repair": "root_rest",
      "return": "dawn_breath",
      "safe_place": "work_petal",
      "sleep": "social_petal",
      "song": "root_rest",
      "tool": "work_petal",
      "warmth": "explore_petal",
      "water": "social_petal"
    },
    "frequency_bindings": {
      "boundary": 0.33,
      "danger": 0.245,
      "flower": 0.347,
      "kin": 0.279,
      "repair": 0.262,
      "return": 0.381,
      "safe_place": 0.194,
      "sleep": 0.313,
      "song": 0.364,
      "tool": 0.296,
      "warmth": 0.228,
      "water": 0.211
    },
    "group": "work_band",
    "innovation_count": 2,
    "lexicon": {
      "boundary": "bar-wo",
      "danger": "graku-wo",
      "flower": "folu-wo",
      "kin": "arie-wo",
      "repair": "mendu-wo",
      "return": "toru-wo",
      "safe_place": "lumu-wo",
      "sleep": "somai-wo",
      "song": "rin-wo",
      "tool": "tek-wo",
      "warmth": "kau-wo",
      "water": "wai-wo"
    },
    "lineage_record": {
      "ancestor_hash": "a04ebbfa05683415",
      "culture_hash": "e5780208fdd9191b",
      "era": 7,
      "year_end": 1600,
      "year_start": 1400
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "tool_mending_call@dawn_breath",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 1600,
    "year_start": 1400
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 7,
    "event_id": 23,
    "flower_bindings": {
      "boundary": "return_petal",
      "danger": "root_rest",
      "flower": "root_rest",
      "kin": "work_petal",
      "repair": "dawn_breath",
      "return": "work_petal",
      "safe_place": "social_petal",
      "sleep": "explore_petal",
      "song": "dawn_breath",
      "tool": "social_petal",
      "warmth": "return_petal",
      "water": "explore_petal"
    },
    "frequency_bindings": {
      "boundary": 0.341,
      "danger": 0.256,
      "flower": 0.358,
      "kin": 0.29,
      "repair": 0.273,
      "return": 0.392,
      "safe_place": 0.205,
      "sleep": 0.324,
      "song": 0.375,
      "tool": 0.307,
      "warmth": 0.239,
      "water": 0.222
    },
    "group": "edge_watch",
    "innovation_count": 3,
    "lexicon": {
      "boundary": "bari-ed",
      "danger": "grake-ed",
      "flower": "fole-ed",
      "kin": "ari-ed",
      "repair": "mende-ed",
      "return": "tore-ed",
      "safe_place": "lume-ed",
      "sleep": "somau-ed",
      "song": "rini-ed",
      "tool": "teki-ed",
      "warmth": "kae-ed",
      "water": "wau-ed"
    },
    "lineage_record": {
      "ancestor_hash": "a04ebbfa05683415",
      "culture_hash": "ec333c32b5ea5891",
      "era": 7,
      "year_end": 1600,
      "year_start": 1400
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "safe_boundary_watch@dawn_breath",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 1600,
    "year_start": 1400
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 8,
    "event_id": 24,
    "flower_bindings": {
      "boundary": "explore_petal",
      "danger": "return_petal",
      "flower": "return_petal",
      "kin": "dawn_breath",
      "repair": "root_rest",
      "return": "dawn_breath",
      "safe_place": "work_petal",
      "sleep": "social_petal",
      "song": "root_rest",
      "tool": "work_petal",
      "warmth": "explore_petal",
      "water": "social_petal"
    },
    "frequency_bindings": {
      "boundary": 0.322,
      "danger": 0.237,
      "flower": 0.339,
      "kin": 0.271,
      "repair": 0.254,
      "return": 0.373,
      "safe_place": 0.186,
      "sleep": 0.305,
      "song": 0.356,
      "tool": 0.288,
      "warmth": 0.22,
      "water": 0.203
    },
    "group": "hearth_circle",
    "innovation_count": 2,
    "lexicon": {
      "boundary": "bari-ha",
      "danger": "grake-ha",
      "flower": "fole-ha",
      "kin": "ari-ha",
      "repair": "mende-ha",
      "return": "tore-ha",
      "safe_place": "lume-ha",
      "sleep": "somau-ha",
      "song": "rini-ha",
      "tool": "teki-ha",
      "warmth": "kae-ha",
      "water": "wau-ha"
    },
    "lineage_record": {
      "ancestor_hash": "423d15a47eb2e1c6",
      "culture_hash": "35a5585fc77b9e8d",
      "era": 8,
      "year_end": 1800,
      "year_start": 1600
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "warm_return_song@work_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 1800,
    "year_start": 1600
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 8,
    "event_id": 25,
    "flower_bindings": {
      "boundary": "return_petal",
      "danger": "root_rest",
      "flower": "root_rest",
      "kin": "work_petal",
      "repair": "dawn_breath",
      "return": "work_petal",
      "safe_place": "social_petal",
      "sleep": "explore_petal",
      "song": "dawn_breath",
      "tool": "social_petal",
      "warmth": "return_petal",
      "water": "explore_petal"
    },
    "frequency_bindings": {
      "boundary": 0.333,
      "danger": 0.248,
      "flower": 0.35,
      "kin": 0.282,
      "repair": 0.265,
      "return": 0.384,
      "safe_place": 0.197,
      "sleep": 0.316,
      "song": 0.367,
      "tool": 0.299,
      "warmth": 0.231,
      "water": 0.214
    },
    "group": "work_band",
    "innovation_count": 3,
    "lexicon": {
      "boundary": "bari-wo",
      "danger": "grake-wo",
      "flower": "fole-wo",
      "kin": "ari-wo",
      "repair": "mende-wo",
      "return": "tore-wo",
      "safe_place": "lume-wo",
      "sleep": "somau-wo",
      "song": "rini-wo",
      "tool": "teki-wo",
      "warmth": "kae-wo",
      "water": "wau-wo"
    },
    "lineage_record": {
      "ancestor_hash": "423d15a47eb2e1c6",
      "culture_hash": "62ca03ccd53024d6",
      "era": 8,
      "year_end": 1800,
      "year_start": 1600
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "tool_mending_call@work_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 1800,
    "year_start": 1600
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 8,
    "event_id": 26,
    "flower_bindings": {
      "boundary": "root_rest",
      "danger": "dawn_breath",
      "flower": "dawn_breath",
      "kin": "social_petal",
      "repair": "work_petal",
      "return": "social_petal",
      "safe_place": "explore_petal",
      "sleep": "return_petal",
      "song": "work_petal",
      "tool": "explore_petal",
      "warmth": "root_rest",
      "water": "return_petal"
    },
    "frequency_bindings": {
      "boundary": 0.344,
      "danger": 0.259,
      "flower": 0.361,
      "kin": 0.293,
      "repair": 0.276,
      "return": 0.395,
      "safe_place": 0.208,
      "sleep": 0.327,
      "song": 0.378,
      "tool": 0.31,
      "warmth": 0.242,
      "water": 0.225
    },
    "group": "edge_watch",
    "innovation_count": 3,
    "lexicon": {
      "boundary": "baru-ed",
      "danger": "grak-ed",
      "flower": "fol-ed",
      "kin": "arii-ed",
      "repair": "mend-ed",
      "return": "tor-ed",
      "safe_place": "lum-ed",
      "sleep": "somae-ed",
      "song": "rinu-ed",
      "tool": "teku-ed",
      "warmth": "ka-ed",
      "water": "wae-ed"
    },
    "lineage_record": {
      "ancestor_hash": "423d15a47eb2e1c6",
      "culture_hash": "96e77c7fe721b426",
      "era": 8,
      "year_end": 1800,
      "year_start": 1600
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "safe_boundary_watch@work_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 1800,
    "year_start": 1600
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 9,
    "event_id": 27,
    "flower_bindings": {
      "boundary": "return_petal",
      "danger": "root_rest",
      "flower": "root_rest",
      "kin": "work_petal",
      "repair": "dawn_breath",
      "return": "work_petal",
      "safe_place": "social_petal",
      "sleep": "explore_petal",
      "song": "dawn_breath",
      "tool": "social_petal",
      "warmth": "return_petal",
      "water": "explore_petal"
    },
    "frequency_bindings": {
      "boundary": 0.325,
      "danger": 0.24,
      "flower": 0.342,
      "kin": 0.274,
      "repair": 0.257,
      "return": 0.376,
      "safe_place": 0.189,
      "sleep": 0.308,
      "song": 0.359,
      "tool": 0.291,
      "warmth": 0.223,
      "water": 0.206
    },
    "group": "hearth_circle",
    "innovation_count": 3,
    "lexicon": {
      "boundary": "baru-ha",
      "danger": "grak-ha",
      "flower": "fol-ha",
      "kin": "arii-ha",
      "repair": "mend-ha",
      "return": "tor-ha",
      "safe_place": "lum-ha",
      "sleep": "somae-ha",
      "song": "rinu-ha",
      "tool": "teku-ha",
      "warmth": "ka-ha",
      "water": "wae-ha"
    },
    "lineage_record": {
      "ancestor_hash": "19a623cadb187c61",
      "culture_hash": "7d4285d959d0d8b2",
      "era": 9,
      "year_end": 2000,
      "year_start": 1800
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "warm_return_song@social_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 2000,
    "year_start": 1800
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 9,
    "event_id": 28,
    "flower_bindings": {
      "boundary": "root_rest",
      "danger": "dawn_breath",
      "flower": "dawn_breath",
      "kin": "social_petal",
      "repair": "work_petal",
      "return": "social_petal",
      "safe_place": "explore_petal",
      "sleep": "return_petal",
      "song": "work_petal",
      "tool": "explore_petal",
      "warmth": "root_rest",
      "water": "return_petal"
    },
    "frequency_bindings": {
      "boundary": 0.336,
      "danger": 0.251,
      "flower": 0.353,
      "kin": 0.285,
      "repair": 0.268,
      "return": 0.387,
      "safe_place": 0.2,
      "sleep": 0.319,
      "song": 0.37,
      "tool": 0.302,
      "warmth": 0.234,
      "water": 0.217
    },
    "group": "work_band",
    "innovation_count": 3,
    "lexicon": {
      "boundary": "baru-wo",
      "danger": "grak-wo",
      "flower": "fol-wo",
      "kin": "arii-wo",
      "repair": "mend-wo",
      "return": "tor-wo",
      "safe_place": "lum-wo",
      "sleep": "somae-wo",
      "song": "rinu-wo",
      "tool": "teku-wo",
      "warmth": "ka-wo",
      "water": "wae-wo"
    },
    "lineage_record": {
      "ancestor_hash": "19a623cadb187c61",
      "culture_hash": "6b466e84b53ccebb",
      "era": 9,
      "year_end": 2000,
      "year_start": 1800
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "tool_mending_call@social_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 2000,
    "year_start": 1800
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 9,
    "event_id": 29,
    "flower_bindings": {
      "boundary": "dawn_breath",
      "danger": "work_petal",
      "flower": "work_petal",
      "kin": "explore_petal",
      "repair": "social_petal",
      "return": "explore_petal",
      "safe_place": "return_petal",
      "sleep": "root_rest",
      "song": "social_petal",
      "tool": "return_petal",
      "warmth": "dawn_breath",
      "water": "root_rest"
    },
    "frequency_bindings": {
      "boundary": 0.347,
      "danger": 0.262,
      "flower": 0.364,
      "kin": 0.296,
      "repair": 0.279,
      "return": 0.398,
      "safe_place": 0.211,
      "sleep": 0.33,
      "song": 0.381,
      "tool": 0.313,
      "warmth": 0.245,
      "water": 0.228
    },
    "group": "edge_watch",
    "innovation_count": 2,
    "lexicon": {
      "boundary": "bare-ed",
      "danger": "graki-ed",
      "flower": "foli-ed",
      "kin": "ariu-ed",
      "repair": "mendi-ed",
      "return": "tori-ed",
      "safe_place": "lumi-ed",
      "sleep": "soma-ed",
      "song": "rine-ed",
      "tool": "teke-ed",
      "warmth": "kai-ed",
      "water": "wa-ed"
    },
    "lineage_record": {
      "ancestor_hash": "19a623cadb187c61",
      "culture_hash": "46f768fe5fd1c0d9",
      "era": 9,
      "year_end": 2000,
      "year_start": 1800
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "safe_boundary_watch@social_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 2000,
    "year_start": 1800
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 10,
    "event_id": 30,
    "flower_bindings": {
      "boundary": "root_rest",
      "danger": "dawn_breath",
      "flower": "dawn_breath",
      "kin": "social_petal",
      "repair": "work_petal",
      "return": "social_petal",
      "safe_place": "explore_petal",
      "sleep": "return_petal",
      "song": "work_petal",
      "tool": "explore_petal",
      "warmth": "root_rest",
      "water": "return_petal"
    },
    "frequency_bindings": {
      "boundary": 0.328,
      "danger": 0.243,
      "flower": 0.345,
      "kin": 0.277,
      "repair": 0.26,
      "return": 0.379,
      "safe_place": 0.192,
      "sleep": 0.311,
      "song": 0.362,
      "tool": 0.294,
      "warmth": 0.226,
      "water": 0.209
    },
    "group": "hearth_circle",
    "innovation_count": 3,
    "lexicon": {
      "boundary": "bare-ha",
      "danger": "graki-ha",
      "flower": "foli-ha",
      "kin": "ariu-ha",
      "repair": "mendi-ha",
      "return": "tori-ha",
      "safe_place": "lumi-ha",
      "sleep": "soma-ha",
      "song": "rine-ha",
      "tool": "teke-ha",
      "warmth": "kai-ha",
      "water": "wa-ha"
    },
    "lineage_record": {
      "ancestor_hash": "d3930d9fa3e5e407",
      "culture_hash": "d8ebf011b3f9f3c2",
      "era": 10,
      "year_end": 2200,
      "year_start": 2000
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "warm_return_song@explore_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 2200,
    "year_start": 2000
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 10,
    "event_id": 31,
    "flower_bindings": {
      "boundary": "dawn_breath",
      "danger": "work_petal",
      "flower": "work_petal",
      "kin": "explore_petal",
      "repair": "social_petal",
      "return": "explore_petal",
      "safe_place": "return_petal",
      "sleep": "root_rest",
      "song": "social_petal",
      "tool": "return_petal",
      "warmth": "dawn_breath",
      "water": "root_rest"
    },
    "frequency_bindings": {
      "boundary": 0.339,
      "danger": 0.254,
      "flower": 0.356,
      "kin": 0.288,
      "repair": 0.271,
      "return": 0.39,
      "safe_place": 0.203,
      "sleep": 0.322,
      "song": 0.373,
      "tool": 0.305,
      "warmth": 0.237,
      "water": 0.22
    },
    "group": "work_band",
    "innovation_count": 2,
    "lexicon": {
      "boundary": "bare-wo",
      "danger": "graki-wo",
      "flower": "foli-wo",
      "kin": "ariu-wo",
      "repair": "mendi-wo",
      "return": "tori-wo",
      "safe_place": "lumi-wo",
      "sleep": "soma-wo",
      "song": "rine-wo",
      "tool": "teke-wo",
      "warmth": "kai-wo",
      "water": "wa-wo"
    },
    "lineage_record": {
      "ancestor_hash": "d3930d9fa3e5e407",
      "culture_hash": "9b0a6e3e72365143",
      "era": 10,
      "year_end": 2200,
      "year_start": 2000
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "tool_mending_call@explore_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 2200,
    "year_start": 2000
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 10,
    "event_id": 32,
    "flower_bindings": {
      "boundary": "work_petal",
      "danger": "social_petal",
      "flower": "social_petal",
      "kin": "return_petal",
      "repair": "explore_petal",
      "return": "return_petal",
      "safe_place": "root_rest",
      "sleep": "dawn_breath",
      "song": "explore_petal",
      "tool": "root_rest",
      "warmth": "work_petal",
      "water": "dawn_breath"
    },
    "frequency_bindings": {
      "boundary": 0.35,
      "danger": 0.265,
      "flower": 0.367,
      "kin": 0.299,
      "repair": 0.282,
      "return": 0.401,
      "safe_place": 0.214,
      "sleep": 0.333,
      "song": 0.384,
      "tool": 0.316,
      "warmth": 0.248,
      "water": 0.231
    },
    "group": "edge_watch",
    "innovation_count": 2,
    "lexicon": {
      "boundary": "bar-ed",
      "danger": "graku-ed",
      "flower": "folu-ed",
      "kin": "arie-ed",
      "repair": "mendu-ed",
      "return": "toru-ed",
      "safe_place": "lumu-ed",
      "sleep": "somai-ed",
      "song": "rin-ed",
      "tool": "tek-ed",
      "warmth": "kau-ed",
      "water": "wai-ed"
    },
    "lineage_record": {
      "ancestor_hash": "d3930d9fa3e5e407",
      "culture_hash": "7df3fc64c9f1ed4a",
      "era": 10,
      "year_end": 2200,
      "year_start": 2000
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "safe_boundary_watch@explore_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 2200,
    "year_start": 2000
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 11,
    "event_id": 33,
    "flower_bindings": {
      "boundary": "dawn_breath",
      "danger": "work_petal",
      "flower": "work_petal",
      "kin": "explore_petal",
      "repair": "social_petal",
      "return": "explore_petal",
      "safe_place": "return_petal",
      "sleep": "root_rest",
      "song": "social_petal",
      "tool": "return_petal",
      "warmth": "dawn_breath",
      "water": "root_rest"
    },
    "frequency_bindings": {
      "boundary": 0.331,
      "danger": 0.246,
      "flower": 0.348,
      "kin": 0.28,
      "repair": 0.263,
      "return": 0.382,
      "safe_place": 0.195,
      "sleep": 0.314,
      "song": 0.365,
      "tool": 0.297,
      "warmth": 0.229,
      "water": 0.212
    },
    "group": "hearth_circle",
    "innovation_count": 2,
    "lexicon": {
      "boundary": "bar-ha",
      "danger": "graku-ha",
      "flower": "folu-ha",
      "kin": "arie-ha",
      "repair": "mendu-ha",
      "return": "toru-ha",
      "safe_place": "lumu-ha",
      "sleep": "somai-ha",
      "song": "rin-ha",
      "tool": "tek-ha",
      "warmth": "kau-ha",
      "water": "wai-ha"
    },
    "lineage_record": {
      "ancestor_hash": "1dfe622349375455",
      "culture_hash": "897cc22aebe41896",
      "era": 11,
      "year_end": 2400,
      "year_start": 2200
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "warm_return_song@return_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 2400,
    "year_start": 2200
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 11,
    "event_id": 34,
    "flower_bindings": {
      "boundary": "work_petal",
      "danger": "social_petal",
      "flower": "social_petal",
      "kin": "return_petal",
      "repair": "explore_petal",
      "return": "return_petal",
      "safe_place": "root_rest",
      "sleep": "dawn_breath",
      "song": "explore_petal",
      "tool": "root_rest",
      "warmth": "work_petal",
      "water": "dawn_breath"
    },
    "frequency_bindings": {
      "boundary": 0.342,
      "danger": 0.257,
      "flower": 0.359,
      "kin": 0.291,
      "repair": 0.274,
      "return": 0.393,
      "safe_place": 0.206,
      "sleep": 0.325,
      "song": 0.376,
      "tool": 0.308,
      "warmth": 0.24,
      "water": 0.223
    },
    "group": "work_band",
    "innovation_count": 2,
    "lexicon": {
      "boundary": "bar-wo",
      "danger": "graku-wo",
      "flower": "folu-wo",
      "kin": "arie-wo",
      "repair": "mendu-wo",
      "return": "toru-wo",
      "safe_place": "lumu-wo",
      "sleep": "somai-wo",
      "song": "rin-wo",
      "tool": "tek-wo",
      "warmth": "kau-wo",
      "water": "wai-wo"
    },
    "lineage_record": {
      "ancestor_hash": "1dfe622349375455",
      "culture_hash": "b9cad84fd36314a1",
      "era": 11,
      "year_end": 2400,
      "year_start": 2200
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "tool_mending_call@return_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 2400,
    "year_start": 2200
  },
  {
    "claim_boundary": {
      "full_natural_language_emergence": false,
      "moral_patienthood": false,
      "subjective_consciousness": false
    },
    "condition": "integrated_deep_time_cultural_memory_proto_language",
    "era": 11,
    "event_id": 35,
    "flower_bindings": {
      "boundary": "social_petal",
      "danger": "explore_petal",
      "flower": "explore_petal",
      "kin": "root_rest",
      "repair": "return_petal",
      "return": "root_rest",
      "safe_place": "dawn_breath",
      "sleep": "work_petal",
      "song": "return_petal",
      "tool": "dawn_breath",
      "warmth": "social_petal",
      "water": "work_petal"
    },
    "frequency_bindings": {
      "boundary": 0.353,
      "danger": 0.268,
      "flower": 0.37,
      "kin": 0.302,
      "repair": 0.285,
      "return": 0.404,
      "safe_place": 0.217,
      "sleep": 0.336,
      "song": 0.387,
      "tool": 0.319,
      "warmth": 0.251,
      "water": 0.234
    },
    "group": "edge_watch",
    "innovation_count": 2,
    "lexicon": {
      "boundary": "bari-ed",
      "danger": "grake-ed",
      "flower": "fole-ed",
      "kin": "ari-ed",
      "repair": "mende-ed",
      "return": "tore-ed",
      "safe_place": "lume-ed",
      "sleep": "somau-ed",
      "song": "rini-ed",
      "tool": "teki-ed",
      "warmth": "kae-ed",
      "water": "wau-ed"
    },
    "lineage_record": {
      "ancestor_hash": "1dfe622349375455",
      "culture_hash": "5068b7bc2ed74ad0",
      "era": 11,
      "year_end": 2400,
      "year_start": 2200
    },
    "private_workspace_hidden": true,
    "recalled_archive_concepts": [
      "boundary",
      "danger",
      "flower",
      "kin",
      "repair",
      "return",
      "safe_place",
      "sleep"
    ],
    "ritual": "safe_boundary_watch@return_petal",
    "roots": {
      "boundary": "bar",
      "danger": "grak",
      "flower": "fol",
      "kin": "ari",
      "repair": "mend",
      "return": "tor",
      "safe_place": "lum",
      "sleep": "soma",
      "song": "rin",
      "tool": "tek",
      "warmth": "ka",
      "water": "wa"
    },
    "year_end": 2400,
    "year_start": 2200
  }
];
