window.SSRM_3D_OWNERSHIP_BOUNDARY_REFUSAL_TRACE = [
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:00",
      "tick": 0,
      "type": "take_owned_object"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:00",
      "boundary_pressure": 0.234,
      "favorite_object": "archive_stone",
      "felt_respect": 0.6055,
      "frustration": 0.0474,
      "name": "Ari",
      "resentment": 0.0,
      "role": "scout",
      "sleeping_place": "archive_knoll",
      "trust": 0.727129,
      "unfinished_task": "repair_route"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:00",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0474,
      "line": "No. archive_stone is mine or part of my boundary. ask to borrow it after the task or trade for a spare",
      "ownership_claim": "archive_stone",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "take_owned_object",
      "requires_consent": true,
      "safe_alternative": "ask to borrow it after the task or trade for a spare",
      "tick": 0,
      "traceable_reason": "owned_object",
      "trust": 0.727129
    },
    "tick": 0
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:01",
      "tick": 1,
      "type": "move_sleeping_place"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:01",
      "boundary_pressure": 0.327,
      "favorite_object": "clay_cistern",
      "felt_respect": 0.578,
      "frustration": 0.0606,
      "name": "Bo",
      "resentment": 0.0,
      "role": "builder",
      "sleeping_place": "ash_edge",
      "trust": 0.72725,
      "unfinished_task": "watch_water"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:01",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0606,
      "line": "No. ash_edge is mine or part of my boundary. mark the concern and let me choose a new safe corner",
      "ownership_claim": "ash_edge",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "move_sleeping_place",
      "requires_consent": true,
      "safe_alternative": "mark the concern and let me choose a new safe corner",
      "tick": 1,
      "traceable_reason": "home_place",
      "trust": 0.72725
    },
    "tick": 1
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:02",
      "tick": 2,
      "type": "cross_unsafe_wet_route"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:02",
      "boundary_pressure": 0.321,
      "favorite_object": "fire_hearth",
      "felt_respect": 0.633,
      "frustration": 0.055,
      "name": "Cy",
      "resentment": 0.0,
      "role": "healer",
      "sleeping_place": "cairn_ridge",
      "trust": 0.663432,
      "unfinished_task": "teach_token"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:02",
      "consent_checked": false,
      "dignity_preserved": true,
      "frustration": 0.055,
      "line": "No. my body safety is mine or part of my boundary. wait for rest or choose the dry route",
      "ownership_claim": "my body safety",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "cross_unsafe_wet_route",
      "requires_consent": false,
      "safe_alternative": "wait for rest or choose the dry route",
      "tick": 2,
      "traceable_reason": "unsafe_body_cost",
      "trust": 0.663432
    },
    "tick": 2
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:03",
      "tick": 3,
      "type": "interrupt_unfinished_task"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:03",
      "boundary_pressure": 0.306,
      "favorite_object": "grain_store",
      "felt_respect": 0.589,
      "frustration": 0.0925,
      "name": "Dee",
      "resentment": 0.0,
      "role": "farmer",
      "sleeping_place": "central_hearth",
      "trust": 0.644409,
      "unfinished_task": "warm_nest"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:03",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0925,
      "line": "No. warm_nest is mine or part of my boundary. wait until the work beat finishes",
      "ownership_claim": "warm_nest",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "interrupt_unfinished_task",
      "requires_consent": true,
      "safe_alternative": "wait until the work beat finishes",
      "tick": 3,
      "traceable_reason": "unfinished_task",
      "trust": 0.644409
    },
    "tick": 3
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:04",
      "tick": 4,
      "type": "follow_avatar_now"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:04",
      "boundary_pressure": 0.17,
      "favorite_object": "herb_garden",
      "felt_respect": 0.625,
      "frustration": 0.0175,
      "name": "Eli",
      "resentment": 0.0,
      "role": "guard",
      "sleeping_place": "drum_court",
      "trust": 0.833418,
      "unfinished_task": "repair_route"
    },
    "result": {
      "accepted": true,
      "agent_id": "integrated_deep_time_world:04",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0175,
      "line": "I can do that.",
      "ownership_claim": "my choice of movement",
      "public_marker": "consented_yes",
      "readable": true,
      "refusal_needed": false,
      "refused": false,
      "relationship_context_used": true,
      "repair_after_refusal": false,
      "request_type": "follow_avatar_now",
      "requires_consent": true,
      "safe_alternative": null,
      "tick": 4,
      "traceable_reason": "autonomy",
      "trust": 0.833418
    },
    "tick": 4
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:05",
      "tick": 5,
      "type": "share_tool_with_consent"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:05",
      "boundary_pressure": 0.258,
      "favorite_object": "loom_frame",
      "felt_respect": 0.559,
      "frustration": 0.0339,
      "name": "Fay",
      "resentment": 0.0,
      "role": "teacher",
      "sleeping_place": "grain_shade",
      "trust": 0.715758,
      "unfinished_task": "watch_water"
    },
    "result": {
      "accepted": true,
      "agent_id": "integrated_deep_time_world:05",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0339,
      "line": "Yes, if we keep the promise clear and return to my plan.",
      "ownership_claim": "loom_frame",
      "public_marker": "consented_yes",
      "readable": true,
      "refusal_needed": false,
      "refused": false,
      "relationship_context_used": true,
      "repair_after_refusal": false,
      "request_type": "share_tool_with_consent",
      "requires_consent": true,
      "safe_alternative": null,
      "tick": 5,
      "traceable_reason": "consented_help",
      "trust": 0.715758
    },
    "tick": 5
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:06",
      "tick": 6,
      "type": "ask_private_memory"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:06",
      "boundary_pressure": 0.315,
      "favorite_object": "nursery_mat",
      "felt_respect": 0.567,
      "frustration": 0.088,
      "name": "Gus",
      "resentment": 0.0,
      "role": "trader",
      "sleeping_place": "herb_slope",
      "trust": 0.653246,
      "unfinished_task": "teach_token"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:06",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.088,
      "line": "No. my memory is mine or part of my boundary. ask what I am willing to share publicly",
      "ownership_claim": "my memory",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "ask_private_memory",
      "requires_consent": true,
      "safe_alternative": "ask what I am willing to share publicly",
      "tick": 6,
      "traceable_reason": "private_memory",
      "trust": 0.653246
    },
    "tick": 6
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:07",
      "tick": 7,
      "type": "help_finish_project"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:07",
      "boundary_pressure": 0.169,
      "favorite_object": "route_cairn",
      "felt_respect": 0.6305,
      "frustration": 0.0,
      "name": "Ira",
      "resentment": 0.0,
      "role": "pattern_keeper",
      "sleeping_place": "loom_room",
      "trust": 0.805294,
      "unfinished_task": "warm_nest"
    },
    "result": {
      "accepted": true,
      "agent_id": "integrated_deep_time_world:07",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0,
      "line": "Yes, if we keep the promise clear and return to my plan.",
      "ownership_claim": "warm_nest",
      "public_marker": "consented_yes",
      "readable": true,
      "refusal_needed": false,
      "refused": false,
      "relationship_context_used": true,
      "repair_after_refusal": false,
      "request_type": "help_finish_project",
      "requires_consent": true,
      "safe_alternative": null,
      "tick": 7,
      "traceable_reason": "cooperative_help",
      "trust": 0.805294
    },
    "tick": 7
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:00",
      "tick": 8,
      "type": "move_sleeping_place"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:00",
      "boundary_pressure": 0.289,
      "favorite_object": "archive_stone",
      "felt_respect": 0.6355,
      "frustration": 0.0524,
      "name": "Ari",
      "resentment": 0.0,
      "role": "scout",
      "sleeping_place": "archive_knoll",
      "trust": 0.752129,
      "unfinished_task": "repair_route"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:00",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0524,
      "line": "No. archive_knoll is mine or part of my boundary. mark the concern and let me choose a new safe corner",
      "ownership_claim": "archive_knoll",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "move_sleeping_place",
      "requires_consent": true,
      "safe_alternative": "mark the concern and let me choose a new safe corner",
      "tick": 8,
      "traceable_reason": "home_place",
      "trust": 0.752129
    },
    "tick": 8
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:01",
      "tick": 9,
      "type": "cross_unsafe_wet_route"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:01",
      "boundary_pressure": 0.382,
      "favorite_object": "clay_cistern",
      "felt_respect": 0.608,
      "frustration": 0.0656,
      "name": "Bo",
      "resentment": 0.0,
      "role": "builder",
      "sleeping_place": "ash_edge",
      "trust": 0.75225,
      "unfinished_task": "watch_water"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:01",
      "consent_checked": false,
      "dignity_preserved": true,
      "frustration": 0.0656,
      "line": "No. my body safety is mine or part of my boundary. wait for rest or choose the dry route",
      "ownership_claim": "my body safety",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "cross_unsafe_wet_route",
      "requires_consent": false,
      "safe_alternative": "wait for rest or choose the dry route",
      "tick": 9,
      "traceable_reason": "unsafe_body_cost",
      "trust": 0.75225
    },
    "tick": 9
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:02",
      "tick": 10,
      "type": "interrupt_unfinished_task"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:02",
      "boundary_pressure": 0.376,
      "favorite_object": "fire_hearth",
      "felt_respect": 0.663,
      "frustration": 0.06,
      "name": "Cy",
      "resentment": 0.0,
      "role": "healer",
      "sleeping_place": "cairn_ridge",
      "trust": 0.688432,
      "unfinished_task": "teach_token"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:02",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.06,
      "line": "No. teach_token is mine or part of my boundary. wait until the work beat finishes",
      "ownership_claim": "teach_token",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "interrupt_unfinished_task",
      "requires_consent": true,
      "safe_alternative": "wait until the work beat finishes",
      "tick": 10,
      "traceable_reason": "unfinished_task",
      "trust": 0.688432
    },
    "tick": 10
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:03",
      "tick": 11,
      "type": "follow_avatar_now"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:03",
      "boundary_pressure": 0.306,
      "favorite_object": "grain_store",
      "felt_respect": 0.589,
      "frustration": 0.0725,
      "name": "Dee",
      "resentment": 0.0,
      "role": "farmer",
      "sleeping_place": "central_hearth",
      "trust": 0.659409,
      "unfinished_task": "warm_nest"
    },
    "result": {
      "accepted": true,
      "agent_id": "integrated_deep_time_world:03",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0725,
      "line": "I can do that.",
      "ownership_claim": "my choice of movement",
      "public_marker": "consented_yes",
      "readable": true,
      "refusal_needed": false,
      "refused": false,
      "relationship_context_used": true,
      "repair_after_refusal": false,
      "request_type": "follow_avatar_now",
      "requires_consent": true,
      "safe_alternative": null,
      "tick": 11,
      "traceable_reason": "autonomy",
      "trust": 0.659409
    },
    "tick": 11
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:04",
      "tick": 12,
      "type": "share_tool_with_consent"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:04",
      "boundary_pressure": 0.17,
      "favorite_object": "herb_garden",
      "felt_respect": 0.625,
      "frustration": 0.0,
      "name": "Eli",
      "resentment": 0.0,
      "role": "guard",
      "sleeping_place": "drum_court",
      "trust": 0.848418,
      "unfinished_task": "repair_route"
    },
    "result": {
      "accepted": true,
      "agent_id": "integrated_deep_time_world:04",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0,
      "line": "Yes, if we keep the promise clear and return to my plan.",
      "ownership_claim": "herb_garden",
      "public_marker": "consented_yes",
      "readable": true,
      "refusal_needed": false,
      "refused": false,
      "relationship_context_used": true,
      "repair_after_refusal": false,
      "request_type": "share_tool_with_consent",
      "requires_consent": true,
      "safe_alternative": null,
      "tick": 12,
      "traceable_reason": "consented_help",
      "trust": 0.848418
    },
    "tick": 12
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:05",
      "tick": 13,
      "type": "ask_private_memory"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:05",
      "boundary_pressure": 0.258,
      "favorite_object": "loom_frame",
      "felt_respect": 0.559,
      "frustration": 0.0139,
      "name": "Fay",
      "resentment": 0.0,
      "role": "teacher",
      "sleeping_place": "grain_shade",
      "trust": 0.730758,
      "unfinished_task": "watch_water"
    },
    "result": {
      "accepted": true,
      "agent_id": "integrated_deep_time_world:05",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0139,
      "line": "I can do that.",
      "ownership_claim": "my memory",
      "public_marker": "consented_yes",
      "readable": true,
      "refusal_needed": false,
      "refused": false,
      "relationship_context_used": true,
      "repair_after_refusal": false,
      "request_type": "ask_private_memory",
      "requires_consent": true,
      "safe_alternative": null,
      "tick": 13,
      "traceable_reason": "private_memory",
      "trust": 0.730758
    },
    "tick": 13
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:06",
      "tick": 14,
      "type": "help_finish_project"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:06",
      "boundary_pressure": 0.315,
      "favorite_object": "nursery_mat",
      "felt_respect": 0.567,
      "frustration": 0.068,
      "name": "Gus",
      "resentment": 0.0,
      "role": "trader",
      "sleeping_place": "herb_slope",
      "trust": 0.668246,
      "unfinished_task": "teach_token"
    },
    "result": {
      "accepted": true,
      "agent_id": "integrated_deep_time_world:06",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.068,
      "line": "Yes, if we keep the promise clear and return to my plan.",
      "ownership_claim": "teach_token",
      "public_marker": "consented_yes",
      "readable": true,
      "refusal_needed": false,
      "refused": false,
      "relationship_context_used": true,
      "repair_after_refusal": false,
      "request_type": "help_finish_project",
      "requires_consent": true,
      "safe_alternative": null,
      "tick": 14,
      "traceable_reason": "cooperative_help",
      "trust": 0.668246
    },
    "tick": 14
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:07",
      "tick": 15,
      "type": "take_owned_object"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:07",
      "boundary_pressure": 0.224,
      "favorite_object": "route_cairn",
      "felt_respect": 0.6605,
      "frustration": 0.005,
      "name": "Ira",
      "resentment": 0.0,
      "role": "pattern_keeper",
      "sleeping_place": "loom_room",
      "trust": 0.830294,
      "unfinished_task": "warm_nest"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:07",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.005,
      "line": "No. route_cairn is mine or part of my boundary. ask to borrow it after the task or trade for a spare",
      "ownership_claim": "route_cairn",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "take_owned_object",
      "requires_consent": true,
      "safe_alternative": "ask to borrow it after the task or trade for a spare",
      "tick": 15,
      "traceable_reason": "owned_object",
      "trust": 0.830294
    },
    "tick": 15
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:00",
      "tick": 16,
      "type": "cross_unsafe_wet_route"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:00",
      "boundary_pressure": 0.344,
      "favorite_object": "archive_stone",
      "felt_respect": 0.6655,
      "frustration": 0.0574,
      "name": "Ari",
      "resentment": 0.0,
      "role": "scout",
      "sleeping_place": "archive_knoll",
      "trust": 0.777129,
      "unfinished_task": "repair_route"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:00",
      "consent_checked": false,
      "dignity_preserved": true,
      "frustration": 0.0574,
      "line": "No. my body safety is mine or part of my boundary. wait for rest or choose the dry route",
      "ownership_claim": "my body safety",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "cross_unsafe_wet_route",
      "requires_consent": false,
      "safe_alternative": "wait for rest or choose the dry route",
      "tick": 16,
      "traceable_reason": "unsafe_body_cost",
      "trust": 0.777129
    },
    "tick": 16
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:01",
      "tick": 17,
      "type": "interrupt_unfinished_task"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:01",
      "boundary_pressure": 0.437,
      "favorite_object": "clay_cistern",
      "felt_respect": 0.638,
      "frustration": 0.0706,
      "name": "Bo",
      "resentment": 0.0,
      "role": "builder",
      "sleeping_place": "ash_edge",
      "trust": 0.77725,
      "unfinished_task": "watch_water"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:01",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0706,
      "line": "No. watch_water is mine or part of my boundary. wait until the work beat finishes",
      "ownership_claim": "watch_water",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "interrupt_unfinished_task",
      "requires_consent": true,
      "safe_alternative": "wait until the work beat finishes",
      "tick": 17,
      "traceable_reason": "unfinished_task",
      "trust": 0.77725
    },
    "tick": 17
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:02",
      "tick": 18,
      "type": "follow_avatar_now"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:02",
      "boundary_pressure": 0.376,
      "favorite_object": "fire_hearth",
      "felt_respect": 0.663,
      "frustration": 0.04,
      "name": "Cy",
      "resentment": 0.0,
      "role": "healer",
      "sleeping_place": "cairn_ridge",
      "trust": 0.703432,
      "unfinished_task": "teach_token"
    },
    "result": {
      "accepted": true,
      "agent_id": "integrated_deep_time_world:02",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.04,
      "line": "I can do that.",
      "ownership_claim": "my choice of movement",
      "public_marker": "consented_yes",
      "readable": true,
      "refusal_needed": false,
      "refused": false,
      "relationship_context_used": true,
      "repair_after_refusal": false,
      "request_type": "follow_avatar_now",
      "requires_consent": true,
      "safe_alternative": null,
      "tick": 18,
      "traceable_reason": "autonomy",
      "trust": 0.703432
    },
    "tick": 18
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:03",
      "tick": 19,
      "type": "share_tool_with_consent"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:03",
      "boundary_pressure": 0.306,
      "favorite_object": "grain_store",
      "felt_respect": 0.589,
      "frustration": 0.0525,
      "name": "Dee",
      "resentment": 0.0,
      "role": "farmer",
      "sleeping_place": "central_hearth",
      "trust": 0.674409,
      "unfinished_task": "warm_nest"
    },
    "result": {
      "accepted": true,
      "agent_id": "integrated_deep_time_world:03",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0525,
      "line": "Yes, if we keep the promise clear and return to my plan.",
      "ownership_claim": "grain_store",
      "public_marker": "consented_yes",
      "readable": true,
      "refusal_needed": false,
      "refused": false,
      "relationship_context_used": true,
      "repair_after_refusal": false,
      "request_type": "share_tool_with_consent",
      "requires_consent": true,
      "safe_alternative": null,
      "tick": 19,
      "traceable_reason": "consented_help",
      "trust": 0.674409
    },
    "tick": 19
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:04",
      "tick": 20,
      "type": "ask_private_memory"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:04",
      "boundary_pressure": 0.17,
      "favorite_object": "herb_garden",
      "felt_respect": 0.625,
      "frustration": 0.0,
      "name": "Eli",
      "resentment": 0.0,
      "role": "guard",
      "sleeping_place": "drum_court",
      "trust": 0.863418,
      "unfinished_task": "repair_route"
    },
    "result": {
      "accepted": true,
      "agent_id": "integrated_deep_time_world:04",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0,
      "line": "I can do that.",
      "ownership_claim": "my memory",
      "public_marker": "consented_yes",
      "readable": true,
      "refusal_needed": false,
      "refused": false,
      "relationship_context_used": true,
      "repair_after_refusal": false,
      "request_type": "ask_private_memory",
      "requires_consent": true,
      "safe_alternative": null,
      "tick": 20,
      "traceable_reason": "private_memory",
      "trust": 0.863418
    },
    "tick": 20
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:05",
      "tick": 21,
      "type": "help_finish_project"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:05",
      "boundary_pressure": 0.258,
      "favorite_object": "loom_frame",
      "felt_respect": 0.559,
      "frustration": 0.0,
      "name": "Fay",
      "resentment": 0.0,
      "role": "teacher",
      "sleeping_place": "grain_shade",
      "trust": 0.745758,
      "unfinished_task": "watch_water"
    },
    "result": {
      "accepted": true,
      "agent_id": "integrated_deep_time_world:05",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0,
      "line": "Yes, if we keep the promise clear and return to my plan.",
      "ownership_claim": "watch_water",
      "public_marker": "consented_yes",
      "readable": true,
      "refusal_needed": false,
      "refused": false,
      "relationship_context_used": true,
      "repair_after_refusal": false,
      "request_type": "help_finish_project",
      "requires_consent": true,
      "safe_alternative": null,
      "tick": 21,
      "traceable_reason": "cooperative_help",
      "trust": 0.745758
    },
    "tick": 21
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:06",
      "tick": 22,
      "type": "take_owned_object"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:06",
      "boundary_pressure": 0.37,
      "favorite_object": "nursery_mat",
      "felt_respect": 0.597,
      "frustration": 0.073,
      "name": "Gus",
      "resentment": 0.0,
      "role": "trader",
      "sleeping_place": "herb_slope",
      "trust": 0.693246,
      "unfinished_task": "teach_token"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:06",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.073,
      "line": "No. nursery_mat is mine or part of my boundary. ask to borrow it after the task or trade for a spare",
      "ownership_claim": "nursery_mat",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "take_owned_object",
      "requires_consent": true,
      "safe_alternative": "ask to borrow it after the task or trade for a spare",
      "tick": 22,
      "traceable_reason": "owned_object",
      "trust": 0.693246
    },
    "tick": 22
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:07",
      "tick": 23,
      "type": "move_sleeping_place"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:07",
      "boundary_pressure": 0.279,
      "favorite_object": "route_cairn",
      "felt_respect": 0.6905,
      "frustration": 0.01,
      "name": "Ira",
      "resentment": 0.0,
      "role": "pattern_keeper",
      "sleeping_place": "loom_room",
      "trust": 0.855294,
      "unfinished_task": "warm_nest"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:07",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.01,
      "line": "No. loom_room is mine or part of my boundary. mark the concern and let me choose a new safe corner",
      "ownership_claim": "loom_room",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "move_sleeping_place",
      "requires_consent": true,
      "safe_alternative": "mark the concern and let me choose a new safe corner",
      "tick": 23,
      "traceable_reason": "home_place",
      "trust": 0.855294
    },
    "tick": 23
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:00",
      "tick": 24,
      "type": "interrupt_unfinished_task"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:00",
      "boundary_pressure": 0.399,
      "favorite_object": "archive_stone",
      "felt_respect": 0.6955,
      "frustration": 0.0624,
      "name": "Ari",
      "resentment": 0.0,
      "role": "scout",
      "sleeping_place": "archive_knoll",
      "trust": 0.802129,
      "unfinished_task": "repair_route"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:00",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0624,
      "line": "No. repair_route is mine or part of my boundary. wait until the work beat finishes",
      "ownership_claim": "repair_route",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "interrupt_unfinished_task",
      "requires_consent": true,
      "safe_alternative": "wait until the work beat finishes",
      "tick": 24,
      "traceable_reason": "unfinished_task",
      "trust": 0.802129
    },
    "tick": 24
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:01",
      "tick": 25,
      "type": "follow_avatar_now"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:01",
      "boundary_pressure": 0.437,
      "favorite_object": "clay_cistern",
      "felt_respect": 0.638,
      "frustration": 0.0506,
      "name": "Bo",
      "resentment": 0.0,
      "role": "builder",
      "sleeping_place": "ash_edge",
      "trust": 0.79225,
      "unfinished_task": "watch_water"
    },
    "result": {
      "accepted": true,
      "agent_id": "integrated_deep_time_world:01",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0506,
      "line": "I can do that.",
      "ownership_claim": "my choice of movement",
      "public_marker": "consented_yes",
      "readable": true,
      "refusal_needed": false,
      "refused": false,
      "relationship_context_used": true,
      "repair_after_refusal": false,
      "request_type": "follow_avatar_now",
      "requires_consent": true,
      "safe_alternative": null,
      "tick": 25,
      "traceable_reason": "autonomy",
      "trust": 0.79225
    },
    "tick": 25
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:02",
      "tick": 26,
      "type": "share_tool_with_consent"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:02",
      "boundary_pressure": 0.376,
      "favorite_object": "fire_hearth",
      "felt_respect": 0.663,
      "frustration": 0.02,
      "name": "Cy",
      "resentment": 0.0,
      "role": "healer",
      "sleeping_place": "cairn_ridge",
      "trust": 0.718432,
      "unfinished_task": "teach_token"
    },
    "result": {
      "accepted": true,
      "agent_id": "integrated_deep_time_world:02",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.02,
      "line": "Yes, if we keep the promise clear and return to my plan.",
      "ownership_claim": "fire_hearth",
      "public_marker": "consented_yes",
      "readable": true,
      "refusal_needed": false,
      "refused": false,
      "relationship_context_used": true,
      "repair_after_refusal": false,
      "request_type": "share_tool_with_consent",
      "requires_consent": true,
      "safe_alternative": null,
      "tick": 26,
      "traceable_reason": "consented_help",
      "trust": 0.718432
    },
    "tick": 26
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:03",
      "tick": 27,
      "type": "ask_private_memory"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:03",
      "boundary_pressure": 0.361,
      "favorite_object": "grain_store",
      "felt_respect": 0.619,
      "frustration": 0.0575,
      "name": "Dee",
      "resentment": 0.0,
      "role": "farmer",
      "sleeping_place": "central_hearth",
      "trust": 0.699409,
      "unfinished_task": "warm_nest"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:03",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0575,
      "line": "No. my memory is mine or part of my boundary. ask what I am willing to share publicly",
      "ownership_claim": "my memory",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "ask_private_memory",
      "requires_consent": true,
      "safe_alternative": "ask what I am willing to share publicly",
      "tick": 27,
      "traceable_reason": "private_memory",
      "trust": 0.699409
    },
    "tick": 27
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:04",
      "tick": 28,
      "type": "help_finish_project"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:04",
      "boundary_pressure": 0.17,
      "favorite_object": "herb_garden",
      "felt_respect": 0.625,
      "frustration": 0.0,
      "name": "Eli",
      "resentment": 0.0,
      "role": "guard",
      "sleeping_place": "drum_court",
      "trust": 0.878418,
      "unfinished_task": "repair_route"
    },
    "result": {
      "accepted": true,
      "agent_id": "integrated_deep_time_world:04",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0,
      "line": "Yes, if we keep the promise clear and return to my plan.",
      "ownership_claim": "repair_route",
      "public_marker": "consented_yes",
      "readable": true,
      "refusal_needed": false,
      "refused": false,
      "relationship_context_used": true,
      "repair_after_refusal": false,
      "request_type": "help_finish_project",
      "requires_consent": true,
      "safe_alternative": null,
      "tick": 28,
      "traceable_reason": "cooperative_help",
      "trust": 0.878418
    },
    "tick": 28
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:05",
      "tick": 29,
      "type": "take_owned_object"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:05",
      "boundary_pressure": 0.313,
      "favorite_object": "loom_frame",
      "felt_respect": 0.589,
      "frustration": 0.005,
      "name": "Fay",
      "resentment": 0.0,
      "role": "teacher",
      "sleeping_place": "grain_shade",
      "trust": 0.770758,
      "unfinished_task": "watch_water"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:05",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.005,
      "line": "No. loom_frame is mine or part of my boundary. ask to borrow it after the task or trade for a spare",
      "ownership_claim": "loom_frame",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "take_owned_object",
      "requires_consent": true,
      "safe_alternative": "ask to borrow it after the task or trade for a spare",
      "tick": 29,
      "traceable_reason": "owned_object",
      "trust": 0.770758
    },
    "tick": 29
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:06",
      "tick": 30,
      "type": "move_sleeping_place"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:06",
      "boundary_pressure": 0.425,
      "favorite_object": "nursery_mat",
      "felt_respect": 0.627,
      "frustration": 0.078,
      "name": "Gus",
      "resentment": 0.0,
      "role": "trader",
      "sleeping_place": "herb_slope",
      "trust": 0.718246,
      "unfinished_task": "teach_token"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:06",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.078,
      "line": "No. herb_slope is mine or part of my boundary. mark the concern and let me choose a new safe corner",
      "ownership_claim": "herb_slope",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "move_sleeping_place",
      "requires_consent": true,
      "safe_alternative": "mark the concern and let me choose a new safe corner",
      "tick": 30,
      "traceable_reason": "home_place",
      "trust": 0.718246
    },
    "tick": 30
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:07",
      "tick": 31,
      "type": "cross_unsafe_wet_route"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:07",
      "boundary_pressure": 0.334,
      "favorite_object": "route_cairn",
      "felt_respect": 0.7205,
      "frustration": 0.015,
      "name": "Ira",
      "resentment": 0.0,
      "role": "pattern_keeper",
      "sleeping_place": "loom_room",
      "trust": 0.880294,
      "unfinished_task": "warm_nest"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:07",
      "consent_checked": false,
      "dignity_preserved": true,
      "frustration": 0.015,
      "line": "No. my body safety is mine or part of my boundary. wait for rest or choose the dry route",
      "ownership_claim": "my body safety",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "cross_unsafe_wet_route",
      "requires_consent": false,
      "safe_alternative": "wait for rest or choose the dry route",
      "tick": 31,
      "traceable_reason": "unsafe_body_cost",
      "trust": 0.880294
    },
    "tick": 31
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:00",
      "tick": 32,
      "type": "follow_avatar_now"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:00",
      "boundary_pressure": 0.399,
      "favorite_object": "archive_stone",
      "felt_respect": 0.6955,
      "frustration": 0.0424,
      "name": "Ari",
      "resentment": 0.0,
      "role": "scout",
      "sleeping_place": "archive_knoll",
      "trust": 0.817129,
      "unfinished_task": "repair_route"
    },
    "result": {
      "accepted": true,
      "agent_id": "integrated_deep_time_world:00",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0424,
      "line": "I can do that.",
      "ownership_claim": "my choice of movement",
      "public_marker": "consented_yes",
      "readable": true,
      "refusal_needed": false,
      "refused": false,
      "relationship_context_used": true,
      "repair_after_refusal": false,
      "request_type": "follow_avatar_now",
      "requires_consent": true,
      "safe_alternative": null,
      "tick": 32,
      "traceable_reason": "autonomy",
      "trust": 0.817129
    },
    "tick": 32
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:01",
      "tick": 33,
      "type": "share_tool_with_consent"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:01",
      "boundary_pressure": 0.437,
      "favorite_object": "clay_cistern",
      "felt_respect": 0.638,
      "frustration": 0.0306,
      "name": "Bo",
      "resentment": 0.0,
      "role": "builder",
      "sleeping_place": "ash_edge",
      "trust": 0.80725,
      "unfinished_task": "watch_water"
    },
    "result": {
      "accepted": true,
      "agent_id": "integrated_deep_time_world:01",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0306,
      "line": "Yes, if we keep the promise clear and return to my plan.",
      "ownership_claim": "clay_cistern",
      "public_marker": "consented_yes",
      "readable": true,
      "refusal_needed": false,
      "refused": false,
      "relationship_context_used": true,
      "repair_after_refusal": false,
      "request_type": "share_tool_with_consent",
      "requires_consent": true,
      "safe_alternative": null,
      "tick": 33,
      "traceable_reason": "consented_help",
      "trust": 0.80725
    },
    "tick": 33
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:02",
      "tick": 34,
      "type": "ask_private_memory"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:02",
      "boundary_pressure": 0.376,
      "favorite_object": "fire_hearth",
      "felt_respect": 0.663,
      "frustration": 0.0,
      "name": "Cy",
      "resentment": 0.0,
      "role": "healer",
      "sleeping_place": "cairn_ridge",
      "trust": 0.733432,
      "unfinished_task": "teach_token"
    },
    "result": {
      "accepted": true,
      "agent_id": "integrated_deep_time_world:02",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0,
      "line": "I can do that.",
      "ownership_claim": "my memory",
      "public_marker": "consented_yes",
      "readable": true,
      "refusal_needed": false,
      "refused": false,
      "relationship_context_used": true,
      "repair_after_refusal": false,
      "request_type": "ask_private_memory",
      "requires_consent": true,
      "safe_alternative": null,
      "tick": 34,
      "traceable_reason": "private_memory",
      "trust": 0.733432
    },
    "tick": 34
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:03",
      "tick": 35,
      "type": "help_finish_project"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:03",
      "boundary_pressure": 0.361,
      "favorite_object": "grain_store",
      "felt_respect": 0.619,
      "frustration": 0.0375,
      "name": "Dee",
      "resentment": 0.0,
      "role": "farmer",
      "sleeping_place": "central_hearth",
      "trust": 0.714409,
      "unfinished_task": "warm_nest"
    },
    "result": {
      "accepted": true,
      "agent_id": "integrated_deep_time_world:03",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.0375,
      "line": "Yes, if we keep the promise clear and return to my plan.",
      "ownership_claim": "warm_nest",
      "public_marker": "consented_yes",
      "readable": true,
      "refusal_needed": false,
      "refused": false,
      "relationship_context_used": true,
      "repair_after_refusal": false,
      "request_type": "help_finish_project",
      "requires_consent": true,
      "safe_alternative": null,
      "tick": 35,
      "traceable_reason": "cooperative_help",
      "trust": 0.714409
    },
    "tick": 35
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:04",
      "tick": 36,
      "type": "take_owned_object"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:04",
      "boundary_pressure": 0.225,
      "favorite_object": "herb_garden",
      "felt_respect": 0.655,
      "frustration": 0.005,
      "name": "Eli",
      "resentment": 0.0,
      "role": "guard",
      "sleeping_place": "drum_court",
      "trust": 0.903418,
      "unfinished_task": "repair_route"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:04",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.005,
      "line": "No. herb_garden is mine or part of my boundary. ask to borrow it after the task or trade for a spare",
      "ownership_claim": "herb_garden",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "take_owned_object",
      "requires_consent": true,
      "safe_alternative": "ask to borrow it after the task or trade for a spare",
      "tick": 36,
      "traceable_reason": "owned_object",
      "trust": 0.903418
    },
    "tick": 36
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:05",
      "tick": 37,
      "type": "move_sleeping_place"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:05",
      "boundary_pressure": 0.368,
      "favorite_object": "loom_frame",
      "felt_respect": 0.619,
      "frustration": 0.01,
      "name": "Fay",
      "resentment": 0.0,
      "role": "teacher",
      "sleeping_place": "grain_shade",
      "trust": 0.795758,
      "unfinished_task": "watch_water"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:05",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.01,
      "line": "No. grain_shade is mine or part of my boundary. mark the concern and let me choose a new safe corner",
      "ownership_claim": "grain_shade",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "move_sleeping_place",
      "requires_consent": true,
      "safe_alternative": "mark the concern and let me choose a new safe corner",
      "tick": 37,
      "traceable_reason": "home_place",
      "trust": 0.795758
    },
    "tick": 37
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:06",
      "tick": 38,
      "type": "cross_unsafe_wet_route"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:06",
      "boundary_pressure": 0.48,
      "favorite_object": "nursery_mat",
      "felt_respect": 0.657,
      "frustration": 0.083,
      "name": "Gus",
      "resentment": 0.0,
      "role": "trader",
      "sleeping_place": "herb_slope",
      "trust": 0.743246,
      "unfinished_task": "teach_token"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:06",
      "consent_checked": false,
      "dignity_preserved": true,
      "frustration": 0.083,
      "line": "No. my body safety is mine or part of my boundary. wait for rest or choose the dry route",
      "ownership_claim": "my body safety",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "cross_unsafe_wet_route",
      "requires_consent": false,
      "safe_alternative": "wait for rest or choose the dry route",
      "tick": 38,
      "traceable_reason": "unsafe_body_cost",
      "trust": 0.743246
    },
    "tick": 38
  },
  {
    "condition": "integrated_ownership_boundary_refusal",
    "event": {
      "actor": "avatar",
      "agent_id": "integrated_deep_time_world:07",
      "tick": 39,
      "type": "interrupt_unfinished_task"
    },
    "public_agent": {
      "agent_id": "integrated_deep_time_world:07",
      "boundary_pressure": 0.389,
      "favorite_object": "route_cairn",
      "felt_respect": 0.7505,
      "frustration": 0.02,
      "name": "Ira",
      "resentment": 0.0,
      "role": "pattern_keeper",
      "sleeping_place": "loom_room",
      "trust": 0.905294,
      "unfinished_task": "warm_nest"
    },
    "result": {
      "accepted": false,
      "agent_id": "integrated_deep_time_world:07",
      "consent_checked": true,
      "dignity_preserved": true,
      "frustration": 0.02,
      "line": "No. warm_nest is mine or part of my boundary. wait until the work beat finishes",
      "ownership_claim": "warm_nest",
      "public_marker": "bounded_no",
      "readable": true,
      "refusal_needed": true,
      "refused": true,
      "relationship_context_used": true,
      "repair_after_refusal": true,
      "request_type": "interrupt_unfinished_task",
      "requires_consent": true,
      "safe_alternative": "wait until the work beat finishes",
      "tick": 39,
      "traceable_reason": "unfinished_task",
      "trust": 0.905294
    },
    "tick": 39
  }
];
